import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_067500_072500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_067500_072500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 27) 400), hi := (mkRat (Int.ofNat 29) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 7769999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 607500000000)])⟩,
      ⟨7, ([(Int.ofNat 7428750000000)], [(Int.ofNat 1875000000000)])⟩,
      ⟨1, ([(Int.ofNat 8250000000000)], [(Int.ofNat 405000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 2985000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
