import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_017500_022500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_017500_022500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 7) 400), hi := (mkRat (Int.ofNat 9) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨7, ([(Int.ofNat 8250000000000)], [(Int.ofNat 1143750000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 1260000000000)])⟩,
      ⟨0, ([(Int.ofNat 8100000000000)], [(Int.ofNat 795000000000)])⟩,
      ⟨0, ([(Int.ofNat 8625000000000)], [(Int.ofNat 105000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
