import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_012500_017500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_012500_017500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 1) 80), hi := (mkRat (Int.ofNat 7) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨7, ([(Int.ofNat 8325000000000)], [(Int.ofNat 1125000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 1125000000000)])⟩,
      ⟨0, ([(Int.ofNat 8250000000000)], [(Int.ofNat 675000000000)])⟩,
      ⟨0, ([(Int.ofNat 8625000000000)], [(Int.ofNat 150000000000)])⟩,
      ⟨6, ([(Int.ofNat 375000000000)], [(Int.negSucc 224999999999)])⟩,
      ⟨6, ([(Int.ofNat 3000000000000)], [(Int.negSucc 37499999999)])⟩],
    last := 6 }

end ConwaySoifer.Simplified.Certificates.Data
