import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_037500_042500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_037500_042500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 3) 80), hi := (mkRat (Int.ofNat 17) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 8324999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 337500000000)])⟩,
      ⟨7, ([(Int.ofNat 7837500000000)], [(Int.ofNat 1500000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 2325000000000)])⟩,
      ⟨0, ([(Int.ofNat 7706250000000)], [(Int.ofNat 1125000000000)])⟩,
      ⟨0, ([(Int.ofNat 8400000000000)], [(Int.ofNat 375000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
