import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_057500_062500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_057500_062500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 23) 400), hi := (mkRat (Int.ofNat 1) 16), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 7964999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 517500000000)])⟩,
      ⟨7, ([(Int.ofNat 7447500000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 8366250000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 2730000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
