import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_062500_067500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_062500_067500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 1) 16), hi := (mkRat (Int.ofNat 27) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 562500000000)])⟩,
      ⟨7, ([(Int.ofNat 7312500000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 8250000000000)], [(Int.ofNat 468750000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 3000000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
