import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_112500_117500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_112500_117500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 9) 80), hi := (mkRat (Int.ofNat 47) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 1368749999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 468749999999)], [(Int.ofNat 468750000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1012500000000)])⟩,
      ⟨7, ([(Int.ofNat 6975000000000)], [(Int.ofNat 2025000000000)])⟩,
      ⟨1, ([(Int.ofNat 7743750000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 3825000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
