import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_087500_092500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_087500_092500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 7) 80), hi := (mkRat (Int.ofNat 37) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 1387499999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 787500000000)])⟩,
      ⟨7, ([(Int.ofNat 7031250000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 7950000000000)], [(Int.ofNat 675000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 3375000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
