import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_117500_122500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_117500_122500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 47) 400), hi := (mkRat (Int.ofNat 49) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.ofNat 307500000000)], [(Int.ofNat 7942500000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
