import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_107500_112500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_107500_112500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 43) 400), hi := (mkRat (Int.ofNat 9) 80), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 1451249999999)], [(Int.ofNat 8951250000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 967500000000)])⟩,
      ⟨7, ([(Int.ofNat 6840000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 7766250000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 3615000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
