import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_097500_102500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_097500_102500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 39) 400), hi := (mkRat (Int.ofNat 41) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 1364999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 877500000000)])⟩,
      ⟨7, ([(Int.ofNat 7020000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 7830000000000)], [(Int.ofNat 795000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 3645000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
