import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_027500_032500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_027500_032500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 11) 400), hi := (mkRat (Int.ofNat 13) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨7, ([(Int.ofNat 7995000000000)], [(Int.ofNat 1500000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 1980000000000)])⟩,
      ⟨0, ([(Int.ofNat 7875000000000)], [(Int.ofNat 1001250000000)])⟩,
      ⟨0, ([(Int.ofNat 8625000000000)], [(Int.ofNat 82500000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
