import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_052500_057500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_052500_057500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 21) 400), hi := (mkRat (Int.ofNat 23) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 8054999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 472500000000)])⟩,
      ⟨7, ([(Int.ofNat 7582500000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 8388750000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 2655000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
