import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_047500_052500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_047500_052500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 19) 400), hi := (mkRat (Int.ofNat 21) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 8141249999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 427500000000)])⟩,
      ⟨7, ([(Int.ofNat 7717500000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 8411250000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 2670000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
