import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_077500_082500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_077500_082500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 31) 400), hi := (mkRat (Int.ofNat 33) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 1364999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 697500000000)])⟩,
      ⟨7, ([(Int.ofNat 7256250000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 8100000000000)], [(Int.ofNat 551250000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 3060000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
