import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_042500_047500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_042500_047500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 17) 400), hi := (mkRat (Int.ofNat 19) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨7, ([(Int.ofNat 7813500000000)], [(Int.ofNat 1875000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 2310000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 8426250000000)])⟩,
      ⟨0, ([(Int.ofNat 7683750000000)], [(Int.ofNat 1125000000000)])⟩,
      ⟨0, ([(Int.ofNat 8433750000000)], [(Int.ofNat 375000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
