import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_092500_097500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_092500_097500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 37) 400), hi := (mkRat (Int.ofNat 39) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 1376249999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 832500000000)])⟩,
      ⟨7, ([(Int.ofNat 7125000000000)], [(Int.ofNat 2081250000000)])⟩,
      ⟨1, ([(Int.ofNat 7890000000000)], [(Int.ofNat 735000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 3495000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
