import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_072500_077500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_072500_077500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 29) 400), hi := (mkRat (Int.ofNat 31) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 7679999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 652500000000)])⟩,
      ⟨7, ([(Int.ofNat 7342500000000)], [(Int.ofNat 1875000000000)])⟩,
      ⟨1, ([(Int.ofNat 8190000000000)], [(Int.ofNat 435000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 3165000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
