import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_022500_027500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_022500_027500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 9) 400), hi := (mkRat (Int.ofNat 11) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 8594999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 202500000000)])⟩,
      ⟨7, ([(Int.ofNat 8100000000000)], [(Int.ofNat 1305000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 1620000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 8696250000000)])⟩,
      ⟨0, ([(Int.ofNat 7998750000000)], [(Int.ofNat 900000000000)])⟩,
      ⟨0, ([(Int.ofNat 8625000000000)], [(Int.ofNat 101250000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
