import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_032500_037500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_032500_037500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 13) 400), hi := (mkRat (Int.ofNat 3) 80), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 8414999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 292500000000)])⟩,
      ⟨7, ([(Int.ofNat 7875000000000)], [(Int.ofNat 1515000000000)])⟩,
      ⟨1, ([(Int.ofNat 8625000000000)], [(Int.ofNat 195000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 2250000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
