import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Across_082500_087500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Across_082500_087500 : CertData :=
  { case := Case.Across,
    lo := (mkRat (Int.ofNat 33) 400), hi := (mkRat (Int.ofNat 7) 80), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 1364999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 359999999999)], [(Int.ofNat 360000000000)])⟩,
      ⟨7, ([(Int.ofNat 7143750000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 8100000000000)], [(Int.ofNat 528750000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 3375000000000)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
