import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_270000_280000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_270000_280000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 27) 100), hi := (mkRat (Int.ofNat 7) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1214999999999)], [(Int.ofNat 465000000000)])⟩,
      ⟨0, ([(Int.negSucc 1214999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 1004999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 1004999999999)], [(Int.ofNat 1005000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 464999999999)])⟩,
      ⟨0, ([(Int.negSucc 464999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 1004999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1184999999999)])⟩,
      ⟨2, ([(Int.ofNat 645000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.ofNat 5445000000000)], [(Int.ofNat 3555000000000)])⟩,
      ⟨2, ([(Int.ofNat 6075000000000)], [(Int.ofNat 2250000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4665000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 5415000000000)])⟩,
      ⟨0, ([(Int.ofNat 249000000000)], [(Int.ofNat 4626000000000)])⟩,
      ⟨2, ([(Int.ofNat 2430000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.ofNat 6075000000000)], [(Int.ofNat 3000000000000)])⟩,
      ⟨2, ([(Int.ofNat 6195000000000)], [(Int.ofNat 2430000000000)])⟩,
      ⟨6, ([(Int.ofNat 8250000000000)], [(Int.negSucc 2894999999999)])⟩,
      ⟨0, ([(Int.ofNat 270000000000)], [(Int.ofNat 5355000000000)])⟩,
      ⟨0, ([(Int.ofNat 1620000000000)], [(Int.negSucc 1874999999999)])⟩,
      ⟨0, ([(Int.ofNat 3750000000000)], [(Int.ofNat 2430000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
