import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_135000_140000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_135000_140000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 27) 200), hi := (mkRat (Int.ofNat 7) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.ofNat 570000000000)], [(Int.negSucc 569999999999)])⟩,
      ⟨2, ([(Int.ofNat 2535000000000)], [(Int.ofNat 6465000000000)])⟩,
      ⟨2, ([(Int.ofNat 7553250000000)], [(Int.ofNat 839250000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4665000000000)])⟩,
      ⟨0, ([(Int.ofNat 438000000000)], [(Int.ofNat 6375000000000)])⟩,
      ⟨0, ([(Int.ofNat 3037500000000)], [(Int.ofNat 4462500000000)])⟩,
      ⟨0, ([(Int.ofNat 4462500000000)], [(Int.ofNat 3037500000000)])⟩,
      ⟨0, ([(Int.ofNat 4860000000000)], [(Int.ofNat 2625000000000)])⟩,
      ⟨0, ([(Int.ofNat 7005000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨6, ([(Int.ofNat 750000000000)], [(Int.negSucc 809999999999)])⟩,
      ⟨6, ([(Int.ofNat 3087000000000)], [(Int.negSucc 899999999999)])⟩],
    last := 6 }

end ConwaySoifer.Simplified.Certificates.Data
