import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_100000_110000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_100000_110000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 1) 10), hi := (mkRat (Int.ofNat 11) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.ofNat 900000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 1800000000000)], [(Int.ofNat 7200000000000)])⟩,
      ⟨2, ([(Int.ofNat 7875000000000)], [(Int.ofNat 675000000000)])⟩,
      ⟨4, ([(Int.negSucc 8099999999999)], [(Int.ofNat 0)])⟩,
      ⟨3, ([(Int.negSucc 1724999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 600000000000)], [(Int.ofNat 6750000000000)])⟩,
      ⟨0, ([(Int.ofNat 630000000000)], [(Int.ofNat 6750000000000)])⟩,
      ⟨0, ([(Int.ofNat 3000000000000)], [(Int.ofNat 4800000000000)])⟩,
      ⟨0, ([(Int.ofNat 3600000000000)], [(Int.ofNat 4275000000000)])⟩,
      ⟨0, ([(Int.ofNat 5175000000000)], [(Int.ofNat 2625000000000)])⟩,
      ⟨0, ([(Int.ofNat 7275000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨8, ([(Int.negSucc 10724999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 1499999999999)], [(Int.ofNat 8100000000000)])⟩,
      ⟨3, ([(Int.negSucc 899999999999)], [(Int.ofNat 2775000000000)])⟩,
      ⟨4, ([(Int.negSucc 629999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 8699999999999)], [(Int.ofNat 7575000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
