import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_320000_330000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_320000_330000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 8) 25), hi := (mkRat (Int.ofNat 33) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1439999999999)], [(Int.ofNat 690000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 689999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 1440000000000)])⟩,
      ⟨2, ([(Int.ofNat 1965000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.ofNat 5415000000000)], [(Int.ofNat 3585000000000)])⟩,
      ⟨2, ([(Int.ofNat 5760000000000)], [(Int.ofNat 2865000000000)])⟩,
      ⟨6, ([(Int.ofNat 8625000000000)], [(Int.negSucc 3239999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4770000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4950000000000)])⟩,
      ⟨0, ([(Int.ofNat 195000000000)], [(Int.ofNat 4680000000000)])⟩,
      ⟨0, ([(Int.ofNat 2670000000000)], [(Int.negSucc 2669999999999)])⟩,
      ⟨2, ([(Int.ofNat 3309000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 3375000000000)], [(Int.ofNat 2385000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
