import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_150000_160000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_150000_160000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 3) 20), hi := (mkRat (Int.ofNat 4) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 300000000000)])⟩,
      ⟨0, ([(Int.negSucc 299999999999)], [(Int.negSucc 449999999999)])⟩,
      ⟨0, ([(Int.ofNat 300000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 1350000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 7125000000000)], [(Int.ofNat 1425000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 6179999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4725000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 6975000000000)])⟩,
      ⟨3, ([(Int.negSucc 2849999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1275000000000)])⟩,
      ⟨0, ([(Int.ofNat 1125000000000)], [(Int.ofNat 1305000000000)])⟩,
      ⟨5, ([(Int.ofNat 1200000000000)], [(Int.negSucc 8324999999999)])⟩,
      ⟨0, ([(Int.ofNat 2430000000000)], [(Int.ofNat 1320000000000)])⟩,
      ⟨2, ([(Int.ofNat 2925000000000)], [(Int.ofNat 6075000000000)])⟩,
      ⟨0, ([(Int.ofNat 3375000000000)], [(Int.ofNat 1350000000000)])⟩,
      ⟨0, ([(Int.ofNat 5400000000000)], [(Int.ofNat 1350000000000)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.ofNat 570000000000)])⟩,
      ⟨2, ([(Int.ofNat 6975000000000)], [(Int.ofNat 1650000000000)])⟩,
      ⟨9, ([(Int.ofNat 8100000000000)], [(Int.negSucc 15974999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 6074999999999)])⟩,
      ⟨8, ([(Int.negSucc 11849999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 7874999999999)], [(Int.ofNat 3600000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 525000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 675000000000)])⟩,
      ⟨3, ([(Int.negSucc 4124999999999)], [(Int.ofNat 4800000000000)])⟩,
      ⟨5, ([(Int.ofNat 555000000000)], [(Int.negSucc 7124999999999)])⟩,
      ⟨2, ([(Int.ofNat 5700000000000)], [(Int.ofNat 3300000000000)])⟩,
      ⟨2, ([(Int.ofNat 6975000000000)], [(Int.ofNat 1275000000000)])⟩,
      ⟨2, ([(Int.ofNat 7200000000000)], [(Int.ofNat 1125000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5549999999999)])⟩,
      ⟨8, ([(Int.negSucc 13349999999999)], [(Int.ofNat 4350000000000)])⟩,
      ⟨4, ([(Int.negSucc 8249999999999)], [(Int.ofNat 5400000000000)])⟩,
      ⟨3, ([(Int.negSucc 3899999999999)], [(Int.ofNat 3900000000000)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.ofNat 450000000000)])⟩,
      ⟨3, ([(Int.negSucc 2624999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 6225000000000)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 7350000000000)])⟩,
      ⟨0, ([(Int.negSucc 824999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨5, ([(Int.negSucc 74999999999)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.ofNat 657000000000)], [(Int.ofNat 5913000000000)])⟩,
      ⟨5, ([(Int.ofNat 1500000000000)], [(Int.negSucc 8099999999999)])⟩,
      ⟨0, ([(Int.ofNat 2250000000000)], [(Int.ofNat 4725000000000)])⟩,
      ⟨0, ([(Int.ofNat 3075000000000)], [(Int.ofNat 4050000000000)])⟩,
      ⟨0, ([(Int.ofNat 6375000000000)], [(Int.ofNat 450000000000)])⟩,
      ⟨8, ([(Int.negSucc 11624999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 10799999999999)], [(Int.ofNat 1800000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨4, ([(Int.negSucc 7499999999999)], [(Int.negSucc 1499999999999)])⟩,
      ⟨5, ([(Int.negSucc 5849999999999)], [(Int.negSucc 3149999999999)])⟩,
      ⟨3, ([(Int.negSucc 5174999999999)], [(Int.ofNat 4050000000000)])⟩,
      ⟨2, ([(Int.negSucc 1349999999999)], [(Int.ofNat 8475000000000)])⟩,
      ⟨6, ([(Int.ofNat 675000000000)], [(Int.negSucc 1049999999999)])⟩,
      ⟨0, ([(Int.ofNat 3075000000000)], [(Int.ofNat 4125000000000)])⟩,
      ⟨6, ([(Int.ofNat 4125000000000)], [(Int.negSucc 674999999999)])⟩],
    last := 6 }

end ConwaySoifer.Simplified.Certificates.Data
