import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_240000_250000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_240000_250000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 6) 25), hi := (mkRat (Int.ofNat 1) 4), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 405000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 720000000000)])⟩,
      ⟨0, ([(Int.negSucc 929999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 929999999999)], [(Int.ofNat 930000000000)])⟩,
      ⟨0, ([(Int.negSucc 719999999999)], [(Int.negSucc 404999999999)])⟩,
      ⟨0, ([(Int.negSucc 404999999999)], [(Int.negSucc 719999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 929999999999)])⟩,
      ⟨0, ([(Int.ofNat 405000000000)], [(Int.negSucc 1124999999999)])⟩,
      ⟨0, ([(Int.ofNat 720000000000)], [(Int.negSucc 1124999999999)])⟩,
      ⟨0, ([(Int.ofNat 2160000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 5400000000000)], [(Int.ofNat 3600000000000)])⟩,
      ⟨2, ([(Int.ofNat 6120000000000)], [(Int.ofNat 2505000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4815000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 5730000000000)])⟩,
      ⟨3, ([(Int.negSucc 5624999999999)], [(Int.ofNat 7920000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1890000000000)])⟩,
      ⟨2, ([(Int.ofNat 1650000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.ofNat 6405000000000)], [(Int.ofNat 1875000000000)])⟩,
      ⟨2, ([(Int.ofNat 6480000000000)], [(Int.ofNat 2145000000000)])⟩,
      ⟨2, ([(Int.ofNat 6480000000000)], [(Int.ofNat 2250000000000)])⟩,
      ⟨1, ([(Int.ofNat 7185000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨6, ([(Int.ofNat 8625000000000)], [(Int.negSucc 2864999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 2999999999999)])⟩,
      ⟨0, ([(Int.ofNat 360000000000)], [(Int.ofNat 5640000000000)])⟩,
      ⟨0, ([(Int.ofNat 5112000000000)], [(Int.negSucc 2111999999999)])⟩,
      ⟨0, ([(Int.ofNat 5400000000000)], [(Int.ofNat 975000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
