import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_200000_210000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_200000_210000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 1) 5), hi := (mkRat (Int.ofNat 21) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 974999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 974999999999)], [(Int.ofNat 600000000000)])⟩,
      ⟨0, ([(Int.negSucc 599999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 599999999999)], [(Int.ofNat 975000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 599999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 974999999999)])⟩,
      ⟨0, ([(Int.ofNat 600000000000)], [(Int.negSucc 974999999999)])⟩,
      ⟨2, ([(Int.ofNat 5325000000000)], [(Int.ofNat 3675000000000)])⟩,
      ⟨2, ([(Int.ofNat 6750000000000)], [(Int.ofNat 1650000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4800000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 6300000000000)])⟩,
      ⟨0, ([(Int.ofNat 510000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 600000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 2475000000000)], [(Int.ofNat 4125000000000)])⟩,
      ⟨0, ([(Int.ofNat 3240000000000)], [(Int.ofNat 3375000000000)])⟩,
      ⟨0, ([(Int.ofNat 5250000000000)], [(Int.ofNat 1200000000000)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.ofNat 300000000000)])⟩,
      ⟨2, ([(Int.ofNat 6000000000000)], [(Int.ofNat 3000000000000)])⟩,
      ⟨2, ([(Int.ofNat 6825000000000)], [(Int.ofNat 1800000000000)])⟩,
      ⟨3, ([(Int.negSucc 3134999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 1874999999999)], [(Int.ofNat 3240000000000)])⟩,
      ⟨4, ([(Int.negSucc 1499999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 7199999999999)], [(Int.ofNat 5250000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
