import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_120000_130000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_120000_130000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 3) 25), hi := (mkRat (Int.ofNat 13) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 510000000000)])⟩,
      ⟨0, ([(Int.ofNat 510000000000)], [(Int.negSucc 509999999999)])⟩,
      ⟨0, ([(Int.ofNat 1080000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 2220000000000)], [(Int.ofNat 6780000000000)])⟩,
      ⟨2, ([(Int.ofNat 7500000000000)], [(Int.ofNat 1080000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 6779999999999)])⟩,
      ⟨4, ([(Int.negSucc 7919999999999)], [(Int.ofNat 0)])⟩,
      ⟨3, ([(Int.negSucc 2294999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1080000000000)])⟩,
      ⟨0, ([(Int.ofNat 5295000000000)], [(Int.ofNat 1080000000000)])⟩,
      ⟨0, ([(Int.ofNat 6156000000000)], [(Int.ofNat 900000000000)])⟩,
      ⟨0, ([(Int.ofNat 6300000000000)], [(Int.ofNat 825000000000)])⟩,
      ⟨0, ([(Int.ofNat 6585000000000)], [(Int.ofNat 540000000000)])⟩,
      ⟨9, ([(Int.ofNat 8640000000000)], [(Int.negSucc 15764999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4680000000000)])⟩,
      ⟨8, ([(Int.negSucc 11324999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 7919999999999)], [(Int.ofNat 4170000000000)])⟩,
      ⟨4, ([(Int.negSucc 3719999999999)], [(Int.ofNat 720000000000)])⟩,
      ⟨3, ([(Int.negSucc 3569999999999)], [(Int.ofNat 4320000000000)])⟩,
      ⟨6, ([(Int.ofNat 7695000000000)], [(Int.negSucc 3374999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3494999999999)])⟩,
      ⟨8, ([(Int.negSucc 11864999999999)], [(Int.ofNat 2865000000000)])⟩,
      ⟨4, ([(Int.negSucc 8249999999999)], [(Int.ofNat 5760000000000)])⟩,
      ⟨5, ([(Int.negSucc 5459999999999)], [(Int.negSucc 3539999999999)])⟩,
      ⟨5, ([(Int.negSucc 5249999999999)], [(Int.negSucc 3209999999999)])⟩,
      ⟨5, ([(Int.ofNat 360000000000)], [(Int.negSucc 4109999999999)])⟩,
      ⟨5, ([(Int.ofNat 3420000000000)], [(Int.negSucc 7919999999999)])⟩],
    last := 5 }

end ConwaySoifer.Simplified.Certificates.Data
