import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_190000_200000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_190000_200000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 19) 100), hi := (mkRat (Int.ofNat 1) 5), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 944999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 944999999999)], [(Int.ofNat 570000000000)])⟩,
      ⟨0, ([(Int.negSucc 764999999999)], [(Int.ofNat 765000000000)])⟩,
      ⟨0, ([(Int.negSucc 569999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 569999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 764999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 944999999999)])⟩,
      ⟨0, ([(Int.ofNat 570000000000)], [(Int.negSucc 944999999999)])⟩,
      ⟨0, ([(Int.ofNat 1710000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 5310000000000)], [(Int.ofNat 3690000000000)])⟩,
      ⟨2, ([(Int.ofNat 6930000000000)], [(Int.ofNat 1500000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4755000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 6435000000000)])⟩,
      ⟨3, ([(Int.negSucc 3059999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 420000000000)], [(Int.ofNat 5580000000000)])⟩,
      ⟨0, ([(Int.ofNat 2625000000000)], [(Int.ofNat 4275000000000)])⟩,
      ⟨0, ([(Int.ofNat 3840000000000)], [(Int.ofNat 3000000000000)])⟩,
      ⟨0, ([(Int.ofNat 5250000000000)], [(Int.ofNat 1470000000000)])⟩,
      ⟨0, ([(Int.ofNat 6060000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨2, ([(Int.ofNat 6840000000000)], [(Int.ofNat 1410000000000)])⟩,
      ⟨2, ([(Int.ofNat 6915000000000)], [(Int.ofNat 1710000000000)])⟩,
      ⟨8, ([(Int.negSucc 12077999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 2894999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 1334999999999)], [(Int.ofNat 1710000000000)])⟩,
      ⟨4, ([(Int.negSucc 1259999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 8624999999999)], [(Int.ofNat 6465000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
