import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_110000_120000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_110000_120000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 11) 100), hi := (mkRat (Int.ofNat 3) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.ofNat 990000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 2025000000000)], [(Int.ofNat 6975000000000)])⟩,
      ⟨2, ([(Int.ofNat 7755000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨4, ([(Int.negSucc 8009999999999)], [(Int.ofNat 0)])⟩,
      ⟨3, ([(Int.negSucc 1859999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 468000000000)], [(Int.ofNat 6750000000000)])⟩,
      ⟨0, ([(Int.ofNat 495000000000)], [(Int.ofNat 6750000000000)])⟩,
      ⟨0, ([(Int.ofNat 3000000000000)], [(Int.ofNat 4680000000000)])⟩,
      ⟨0, ([(Int.ofNat 3750000000000)], [(Int.ofNat 3960000000000)])⟩,
      ⟨0, ([(Int.ofNat 4875000000000)], [(Int.ofNat 2805000000000)])⟩,
      ⟨0, ([(Int.ofNat 7140000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 7218000000000)], [(Int.ofNat 282000000000)])⟩,
      ⟨8, ([(Int.negSucc 10919999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 1499999999999)], [(Int.ofNat 7680000000000)])⟩,
      ⟨4, ([(Int.negSucc 749999999999)], [(Int.ofNat 90000000000)])⟩,
      ⟨3, ([(Int.negSucc 749999999999)], [(Int.ofNat 660000000000)])⟩,
      ⟨0, ([(Int.negSucc 8669999999999)], [(Int.ofNat 7500000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
