import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_180000_190000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_180000_190000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 9) 50), hi := (mkRat (Int.ofNat 19) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 914999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 914999999999)], [(Int.ofNat 540000000000)])⟩,
      ⟨0, ([(Int.negSucc 539999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 539999999999)], [(Int.ofNat 915000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 539999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 734999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 914999999999)])⟩,
      ⟨0, ([(Int.ofNat 540000000000)], [(Int.negSucc 914999999999)])⟩,
      ⟨0, ([(Int.ofNat 1620000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 3459000000000)], [(Int.ofNat 5541000000000)])⟩,
      ⟨2, ([(Int.ofNat 6960000000000)], [(Int.ofNat 1500000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5540999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4710000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 6570000000000)])⟩,
      ⟨3, ([(Int.negSucc 3239999999999)], [(Int.ofNat 8865000000000)])⟩,
      ⟨3, ([(Int.negSucc 3044999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 180000000000)], [(Int.ofNat 2250000000000)])⟩,
      ⟨5, ([(Int.ofNat 1620000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨0, ([(Int.ofNat 3000000000000)], [(Int.ofNat 1950000000000)])⟩,
      ⟨2, ([(Int.ofNat 4860000000000)], [(Int.ofNat 4140000000000)])⟩,
      ⟨0, ([(Int.ofNat 4875000000000)], [(Int.ofNat 1695000000000)])⟩,
      ⟨2, ([(Int.ofNat 5925000000000)], [(Int.ofNat 3075000000000)])⟩,
      ⟨0, ([(Int.ofNat 6195000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨2, ([(Int.ofNat 6750000000000)], [(Int.ofNat 1620000000000)])⟩,
      ⟨1, ([(Int.ofNat 7500000000000)], [(Int.ofNat 420000000000)])⟩,
      ⟨9, ([(Int.ofNat 8250000000000)], [(Int.negSucc 14729999999999)])⟩,
      ⟨6, ([(Int.ofNat 8865000000000)], [(Int.negSucc 3239999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3209999999999)])⟩,
      ⟨8, ([(Int.negSucc 12104999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 7919999999999)], [(Int.ofNat 3420000000000)])⟩,
      ⟨4, ([(Int.negSucc 4049999999999)], [(Int.ofNat 300000000000)])⟩,
      ⟨3, ([(Int.negSucc 2999999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 2249999999999)], [(Int.ofNat 2430000000000)])⟩,
      ⟨5, ([(Int.ofNat 540000000000)], [(Int.negSucc 4289999999999)])⟩,
      ⟨0, ([(Int.ofNat 2250000000000)], [(Int.ofNat 4500000000000)])⟩,
      ⟨0, ([(Int.ofNat 2625000000000)], [(Int.ofNat 4215000000000)])⟩,
      ⟨5, ([(Int.ofNat 3240000000000)], [(Int.negSucc 8114999999999)])⟩,
      ⟨0, ([(Int.ofNat 3840000000000)], [(Int.ofNat 3000000000000)])⟩,
      ⟨8, ([(Int.negSucc 13334999999999)], [(Int.ofNat 4335000000000)])⟩,
      ⟨8, ([(Int.negSucc 11540999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8459999999999)], [(Int.ofNat 5835000000000)])⟩,
      ⟨4, ([(Int.negSucc 5804999999999)], [(Int.negSucc 3194999999999)])⟩,
      ⟨5, ([(Int.negSucc 3329999999999)], [(Int.negSucc 5669999999999)])⟩,
      ⟨3, ([(Int.negSucc 1619999999999)], [(Int.ofNat 1620000000000)])⟩,
      ⟨0, ([(Int.negSucc 1619999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨6, ([(Int.ofNat 1305000000000)], [(Int.negSucc 1304999999999)])⟩,
      ⟨0, ([(Int.ofNat 5460000000000)], [(Int.negSucc 1499999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
