import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_170000_180000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_170000_180000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 17) 100), hi := (mkRat (Int.ofNat 9) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 884999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 884999999999)], [(Int.ofNat 510000000000)])⟩,
      ⟨0, ([(Int.negSucc 509999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 509999999999)], [(Int.ofNat 885000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 509999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 884999999999)])⟩,
      ⟨0, ([(Int.ofNat 510000000000)], [(Int.negSucc 884999999999)])⟩,
      ⟨0, ([(Int.ofNat 1530000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 3240000000000)], [(Int.ofNat 5760000000000)])⟩,
      ⟨2, ([(Int.ofNat 6990000000000)], [(Int.ofNat 1500000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5759999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4740000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 6705000000000)])⟩,
      ⟨3, ([(Int.negSucc 3239999999999)], [(Int.ofNat 8865000000000)])⟩,
      ⟨3, ([(Int.negSucc 2999999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1530000000000)])⟩,
      ⟨5, ([(Int.ofNat 1485000000000)], [(Int.negSucc 8234999999999)])⟩,
      ⟨0, ([(Int.ofNat 2880000000000)], [(Int.ofNat 1620000000000)])⟩,
      ⟨2, ([(Int.ofNat 4860000000000)], [(Int.ofNat 4140000000000)])⟩,
      ⟨0, ([(Int.ofNat 4875000000000)], [(Int.ofNat 1530000000000)])⟩,
      ⟨2, ([(Int.ofNat 5871000000000)], [(Int.ofNat 3129000000000)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.ofNat 510000000000)])⟩,
      ⟨0, ([(Int.ofNat 6120000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨2, ([(Int.ofNat 7110000000000)], [(Int.ofNat 1125000000000)])⟩,
      ⟨2, ([(Int.ofNat 7125000000000)], [(Int.ofNat 1365000000000)])⟩,
      ⟨9, ([(Int.ofNat 8250000000000)], [(Int.negSucc 15119999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3239999999999)])⟩,
      ⟨8, ([(Int.negSucc 12059999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8099999999999)], [(Int.ofNat 3690000000000)])⟩,
      ⟨4, ([(Int.negSucc 3824999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨3, ([(Int.negSucc 3824999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨3, ([(Int.negSucc 2609999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 6120000000000)])⟩,
      ⟨0, ([(Int.ofNat 390000000000)], [(Int.negSucc 899999999999)])⟩,
      ⟨5, ([(Int.ofNat 585000000000)], [(Int.negSucc 4409999999999)])⟩,
      ⟨0, ([(Int.ofNat 2535000000000)], [(Int.ofNat 4590000000000)])⟩,
      ⟨0, ([(Int.ofNat 2880000000000)], [(Int.ofNat 4245000000000)])⟩,
      ⟨5, ([(Int.ofNat 3240000000000)], [(Int.negSucc 8114999999999)])⟩,
      ⟨0, ([(Int.ofNat 6120000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.ofNat 6375000000000)], [(Int.ofNat 330000000000)])⟩,
      ⟨2, ([(Int.ofNat 6855000000000)], [(Int.ofNat 1125000000000)])⟩,
      ⟨8, ([(Int.negSucc 12869999999999)], [(Int.ofNat 3870000000000)])⟩,
      ⟨8, ([(Int.negSucc 11684999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8378999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨4, ([(Int.negSucc 5834999999999)], [(Int.negSucc 3164999999999)])⟩,
      ⟨3, ([(Int.negSucc 5174999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨3, ([(Int.negSucc 2459999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 1124999999999)], [(Int.ofNat 765000000000)])⟩,
      ⟨3, ([(Int.negSucc 1019999999999)], [(Int.ofNat 1125000000000)])⟩],
    last := 3 }

end ConwaySoifer.Simplified.Certificates.Data
