import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_340000_350000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_340000_350000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 17) 50), hi := (mkRat (Int.ofNat 7) 20), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1529999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 779999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.negSucc 779999999999)], [(Int.ofNat 1530000000000)])⟩,
      ⟨2, ([(Int.ofNat 2370000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.ofNat 4395000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨2, ([(Int.ofNat 5565000000000)], [(Int.ofNat 3060000000000)])⟩,
      ⟨2, ([(Int.ofNat 5625000000000)], [(Int.ofNat 3060000000000)])⟩,
      ⟨6, ([(Int.ofNat 8490000000000)], [(Int.negSucc 3239999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4758000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4920000000000)])⟩,
      ⟨0, ([(Int.ofNat 180000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 2970000000000)], [(Int.negSucc 2969999999999)])⟩,
      ⟨2, ([(Int.ofNat 3555000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 3585000000000)], [(Int.ofNat 2040000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
