import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_310000_320000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_310000_320000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 31) 100), hi := (mkRat (Int.ofNat 8) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1394999999999)], [(Int.ofNat 645000000000)])⟩,
      ⟨0, ([(Int.negSucc 1394999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 1080000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 644999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 1079999999999)])⟩,
      ⟨2, ([(Int.ofNat 5625000000000)], [(Int.ofNat 2745000000000)])⟩,
      ⟨2, ([(Int.ofNat 5835000000000)], [(Int.ofNat 2790000000000)])⟩,
      ⟨6, ([(Int.ofNat 8625000000000)], [(Int.negSucc 3344999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4785000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 5022000000000)])⟩,
      ⟨0, ([(Int.ofNat 2025000000000)], [(Int.negSucc 2249999999999)])⟩,
      ⟨2, ([(Int.ofNat 3330000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 3978000000000)], [(Int.ofNat 1647000000000)])⟩,
      ⟨0, ([(Int.ofNat 153000000000)], [(Int.ofNat 5022000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
