import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_330000_340000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_330000_340000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 33) 100), hi := (mkRat (Int.ofNat 17) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1484999999999)], [(Int.ofNat 735000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 734999999999)])⟩,
      ⟨2, ([(Int.ofNat 2175000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.ofNat 4500000000000)], [(Int.ofNat 5346000000000)])⟩,
      ⟨2, ([(Int.ofNat 5625000000000)], [(Int.ofNat 2970000000000)])⟩,
      ⟨6, ([(Int.ofNat 8625000000000)], [(Int.negSucc 3278999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4785000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4971000000000)])⟩,
      ⟨0, ([(Int.ofNat 171000000000)], [(Int.ofNat 5175000000000)])⟩,
      ⟨0, ([(Int.ofNat 2790000000000)], [(Int.negSucc 2789999999999)])⟩,
      ⟨2, ([(Int.ofNat 3471000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 3654000000000)], [(Int.ofNat 1971000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
