import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_230000_240000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_230000_240000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 23) 100), hi := (mkRat (Int.ofNat 6) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1064999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1064999999999)], [(Int.ofNat 690000000000)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 900000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 284999999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 689999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 899999999999)])⟩,
      ⟨0, ([(Int.ofNat 285000000000)], [(Int.negSucc 1034999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1064999999999)])⟩,
      ⟨0, ([(Int.ofNat 690000000000)], [(Int.negSucc 1064999999999)])⟩,
      ⟨2, ([(Int.ofNat 5385000000000)], [(Int.ofNat 3615000000000)])⟩,
      ⟨2, ([(Int.ofNat 6210000000000)], [(Int.ofNat 2415000000000)])⟩,
      ⟨2, ([(Int.ofNat 6375000000000)], [(Int.ofNat 2070000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4800000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 5835000000000)])⟩,
      ⟨2, ([(Int.ofNat 351000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 360000000000)], [(Int.ofNat 4500000000000)])⟩,
      ⟨2, ([(Int.ofNat 1335000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 2490000000000)], [(Int.ofNat 3750000000000)])⟩,
      ⟨0, ([(Int.ofNat 5175000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.ofNat 5274000000000)], [(Int.ofNat 351000000000)])⟩,
      ⟨2, ([(Int.ofNat 6405000000000)], [(Int.ofNat 1875000000000)])⟩,
      ⟨2, ([(Int.ofNat 6555000000000)], [(Int.ofNat 2070000000000)])⟩,
      ⟨3, ([(Int.negSucc 3398999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 2009999999999)], [(Int.ofNat 0)])⟩,
      ⟨3, ([(Int.negSucc 1994999999999)], [(Int.ofNat 1995000000000)])⟩,
      ⟨0, ([(Int.ofNat 270000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.ofNat 2760000000000)], [(Int.ofNat 3750000000000)])⟩,
      ⟨0, ([(Int.negSucc 5999999999999)], [(Int.ofNat 3930000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
