import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_290000_300000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_290000_300000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 29) 100), hi := (mkRat (Int.ofNat 3) 10), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1304999999999)], [(Int.ofNat 555000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 554999999999)])⟩,
      ⟨0, ([(Int.negSucc 554999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨2, ([(Int.ofNat 1230000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.ofNat 5448000000000)], [(Int.ofNat 3552000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3359999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4815000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 5190000000000)])⟩,
      ⟨0, ([(Int.ofNat 210000000000)], [(Int.ofNat 3915000000000)])⟩,
      ⟨0, ([(Int.ofNat 1440000000000)], [(Int.negSucc 1814999999999)])⟩,
      ⟨2, ([(Int.ofNat 2970000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 3960000000000)], [(Int.ofNat 1125000000000)])⟩,
      ⟨6, ([(Int.ofNat 8100000000000)], [(Int.negSucc 2579999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 2999999999999)])⟩,
      ⟨0, ([(Int.ofNat 3480000000000)], [(Int.negSucc 3374999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
