import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_130000_135000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_130000_135000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 13) 100), hi := (mkRat (Int.ofNat 27) 200), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.ofNat 540000000000)], [(Int.negSucc 539999999999)])⟩,
      ⟨0, ([(Int.ofNat 1170000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 7573500000000)], [(Int.ofNat 841500000000)])⟩,
      ⟨4, ([(Int.negSucc 7829999999999)], [(Int.ofNat 0)])⟩,
      ⟨3, ([(Int.negSucc 2084999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 519000000000)], [(Int.ofNat 6375000000000)])⟩,
      ⟨0, ([(Int.ofNat 645000000000)], [(Int.ofNat 6375000000000)])⟩,
      ⟨0, ([(Int.ofNat 1500000000000)], [(Int.ofNat 5745000000000)])⟩,
      ⟨0, ([(Int.ofNat 2820000000000)], [(Int.ofNat 4680000000000)])⟩,
      ⟨0, ([(Int.ofNat 4680000000000)], [(Int.ofNat 2820000000000)])⟩,
      ⟨0, ([(Int.ofNat 6870000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨8, ([(Int.negSucc 11105999999999)], [(Int.ofNat 8856000000000)])⟩,
      ⟨3, ([(Int.negSucc 1874999999999)], [(Int.ofNat 8220000000000)])⟩,
      ⟨4, ([(Int.negSucc 899999999999)], [(Int.ofNat 120000000000)])⟩,
      ⟨3, ([(Int.negSucc 899999999999)], [(Int.ofNat 1290000000000)])⟩,
      ⟨0, ([(Int.negSucc 8624999999999)], [(Int.ofNat 7245000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
