import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_220000_230000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_220000_230000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 11) 50), hi := (mkRat (Int.ofNat 23) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 459000000000)])⟩,
      ⟨0, ([(Int.negSucc 1034999999999)], [(Int.ofNat 660000000000)])⟩,
      ⟨0, ([(Int.negSucc 854999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 854999999999)], [(Int.ofNat 855000000000)])⟩,
      ⟨0, ([(Int.negSucc 659999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 620999999999)], [(Int.ofNat 1080000000000)])⟩,
      ⟨0, ([(Int.negSucc 539999999999)], [(Int.negSucc 539999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 854999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1034999999999)])⟩,
      ⟨0, ([(Int.ofNat 540000000000)], [(Int.negSucc 1079999999999)])⟩,
      ⟨0, ([(Int.ofNat 621000000000)], [(Int.negSucc 1079999999999)])⟩,
      ⟨0, ([(Int.ofNat 1980000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 5385000000000)], [(Int.ofNat 3615000000000)])⟩,
      ⟨2, ([(Int.ofNat 6030000000000)], [(Int.ofNat 2595000000000)])⟩,
      ⟨1, ([(Int.ofNat 7215000000000)], [(Int.ofNat 660000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3389999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4755000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 6030000000000)])⟩,
      ⟨3, ([(Int.negSucc 5999999999999)], [(Int.ofNat 7920000000000)])⟩,
      ⟨0, ([(Int.negSucc 464999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 7259999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1290000000000)])⟩,
      ⟨2, ([(Int.ofNat 855000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 4215000000000)], [(Int.ofNat 660000000000)])⟩,
      ⟨2, ([(Int.ofNat 6360000000000)], [(Int.ofNat 1890000000000)])⟩,
      ⟨2, ([(Int.ofNat 6645000000000)], [(Int.ofNat 1980000000000)])⟩,
      ⟨9, ([(Int.ofNat 8130000000000)], [(Int.negSucc 11879999999999)])⟩,
      ⟨6, ([(Int.ofNat 8595000000000)], [(Int.negSucc 2969999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3089999999999)])⟩,
      ⟨0, ([(Int.ofNat 315000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨5, ([(Int.ofNat 450000000000)], [(Int.negSucc 4949999999999)])⟩,
      ⟨0, ([(Int.ofNat 2880000000000)], [(Int.ofNat 3750000000000)])⟩,
      ⟨5, ([(Int.ofNat 3564000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨0, ([(Int.ofNat 4125000000000)], [(Int.negSucc 1154999999999)])⟩,
      ⟨0, ([(Int.ofNat 5175000000000)], [(Int.ofNat 1320000000000)])⟩,
      ⟨4, ([(Int.negSucc 5654999999999)], [(Int.negSucc 3344999999999)])⟩,
      ⟨3, ([(Int.negSucc 1319999999999)], [(Int.ofNat 900000000000)])⟩,
      ⟨3, ([(Int.negSucc 1319999999999)], [(Int.ofNat 6570000000000)])⟩],
    last := 3 }

end ConwaySoifer.Simplified.Certificates.Data
