import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_280000_290000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_280000_290000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 7) 25), hi := (mkRat (Int.ofNat 29) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1259999999999)], [(Int.ofNat 510000000000)])⟩,
      ⟨0, ([(Int.negSucc 1259999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 839999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 509999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 839999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1214999999999)])⟩,
      ⟨2, ([(Int.ofNat 930000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.ofNat 5445000000000)], [(Int.ofNat 3555000000000)])⟩,
      ⟨2, ([(Int.ofNat 5925000000000)], [(Int.ofNat 2700000000000)])⟩,
      ⟨2, ([(Int.ofNat 6000000000000)], [(Int.ofNat 2520000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4800000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 5310000000000)])⟩,
      ⟨0, ([(Int.ofNat 339000000000)], [(Int.ofNat 4536000000000)])⟩,
      ⟨2, ([(Int.ofNat 1485000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 1515000000000)], [(Int.ofNat 4125000000000)])⟩,
      ⟨2, ([(Int.ofNat 2700000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 4500000000000)], [(Int.ofNat 1260000000000)])⟩,
      ⟨6, ([(Int.ofNat 8160000000000)], [(Int.negSucc 2624999999999)])⟩,
      ⟨0, ([(Int.ofNat 2160000000000)], [(Int.negSucc 2159999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
