import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_140000_150000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_140000_150000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 7) 50), hi := (mkRat (Int.ofNat 3) 20), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 330000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 420000000000)])⟩,
      ⟨0, ([(Int.negSucc 419999999999)], [(Int.negSucc 329999999999)])⟩,
      ⟨0, ([(Int.negSucc 419999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 329999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨2, ([(Int.ofNat 0)], [(Int.ofNat 7965000000000)])⟩,
      ⟨0, ([(Int.ofNat 330000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 420000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨2, ([(Int.ofNat 2610000000000)], [(Int.ofNat 6390000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 6389999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4665000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 7080000000000)])⟩,
      ⟨0, ([(Int.ofNat 1410000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 2895000000000)], [(Int.ofNat 6105000000000)])⟩,
      ⟨2, ([(Int.ofNat 7185000000000)], [(Int.ofNat 1440000000000)])⟩,
      ⟨2, ([(Int.ofNat 7455000000000)], [(Int.ofNat 1125000000000)])⟩,
      ⟨0, ([(Int.ofNat 420000000000)], [(Int.ofNat 6330000000000)])⟩,
      ⟨0, ([(Int.ofNat 2625000000000)], [(Int.ofNat 4695000000000)])⟩,
      ⟨0, ([(Int.ofNat 5250000000000)], [(Int.ofNat 2070000000000)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.ofNat 1260000000000)])⟩,
      ⟨0, ([(Int.ofNat 6750000000000)], [(Int.ofNat 420000000000)])⟩,
      ⟨6, ([(Int.ofNat 930000000000)], [(Int.negSucc 929999999999)])⟩,
      ⟨6, ([(Int.ofNat 5010000000000)], [(Int.negSucc 1259999999999)])⟩,
      ⟨6, ([(Int.ofNat 6375000000000)], [(Int.negSucc 1439999999999)])⟩],
    last := 6 }

end ConwaySoifer.Simplified.Certificates.Data
