import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_160000_170000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_160000_170000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 4) 25), hi := (mkRat (Int.ofNat 17) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 659999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 659999999999)], [(Int.ofNat 660000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 659999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 660000000000)])⟩,
      ⟨0, ([(Int.ofNat 660000000000)], [(Int.negSucc 659999999999)])⟩,
      ⟨0, ([(Int.ofNat 1440000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 3000000000000)], [(Int.ofNat 6000000000000)])⟩,
      ⟨2, ([(Int.ofNat 7125000000000)], [(Int.ofNat 1395000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5984999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4680000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 6840000000000)])⟩,
      ⟨3, ([(Int.negSucc 2819999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1440000000000)])⟩,
      ⟨5, ([(Int.ofNat 1170000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨0, ([(Int.ofNat 2592000000000)], [(Int.ofNat 1533000000000)])⟩,
      ⟨2, ([(Int.ofNat 3285000000000)], [(Int.ofNat 5715000000000)])⟩,
      ⟨0, ([(Int.ofNat 4320000000000)], [(Int.ofNat 1500000000000)])⟩,
      ⟨0, ([(Int.ofNat 5310000000000)], [(Int.ofNat 1440000000000)])⟩,
      ⟨2, ([(Int.ofNat 5790000000000)], [(Int.ofNat 3210000000000)])⟩,
      ⟨0, ([(Int.ofNat 6390000000000)], [(Int.ofNat 360000000000)])⟩,
      ⟨2, ([(Int.ofNat 7125000000000)], [(Int.ofNat 1440000000000)])⟩,
      ⟨9, ([(Int.ofNat 8385000000000)], [(Int.negSucc 14759999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5714999999999)])⟩,
      ⟨8, ([(Int.negSucc 11819999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8039999999999)], [(Int.ofNat 3825000000000)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.ofNat 480000000000)])⟩,
      ⟨3, ([(Int.negSucc 2804999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 2249999999999)], [(Int.ofNat 2970000000000)])⟩,
      ⟨5, ([(Int.ofNat 342000000000)], [(Int.negSucc 6749999999999)])⟩,
      ⟨0, ([(Int.ofNat 495000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨5, ([(Int.ofNat 1530000000000)], [(Int.negSucc 8279999999999)])⟩,
      ⟨0, ([(Int.ofNat 2955000000000)], [(Int.ofNat 4125000000000)])⟩,
      ⟨2, ([(Int.ofNat 5250000000000)], [(Int.ofNat 2520000000000)])⟩,
      ⟨6, ([(Int.ofNat 6840000000000)], [(Int.negSucc 3089999999999)])⟩,
      ⟨2, ([(Int.ofNat 6915000000000)], [(Int.ofNat 1125000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3314999999999)])⟩,
      ⟨8, ([(Int.negSucc 12134999999999)], [(Int.ofNat 3135000000000)])⟩,
      ⟨8, ([(Int.negSucc 11444999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8384999999999)], [(Int.ofNat 5760000000000)])⟩,
      ⟨4, ([(Int.negSucc 7469999999999)], [(Int.negSucc 1529999999999)])⟩,
      ⟨3, ([(Int.negSucc 5399999999999)], [(Int.ofNat 4275000000000)])⟩,
      ⟨5, ([(Int.negSucc 4379999999999)], [(Int.negSucc 4619999999999)])⟩,
      ⟨3, ([(Int.negSucc 2459999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1439999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.negSucc 1184999999999)], [(Int.ofNat 7560000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 1334999999999)])⟩,
      ⟨6, ([(Int.ofNat 1275000000000)], [(Int.negSucc 1274999999999)])⟩,
      ⟨5, ([(Int.ofNat 4125000000000)], [(Int.negSucc 8039999999999)])⟩],
    last := 5 }

end ConwaySoifer.Simplified.Certificates.Data
