import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_250000_260000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_250000_260000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 1) 4), hi := (mkRat (Int.ofNat 13) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1124999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.negSucc 1124999999999)])⟩,
      ⟨2, ([(Int.ofNat 2250000000000)], [(Int.ofNat 6375000000000)])⟩,
      ⟨0, ([(Int.ofNat 2550000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 5325000000000)], [(Int.ofNat 3675000000000)])⟩,
      ⟨2, ([(Int.ofNat 6000000000000)], [(Int.ofNat 2625000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3374999999999)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨3, ([(Int.negSucc 4949999999999)], [(Int.ofNat 8100000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1950000000000)])⟩,
      ⟨2, ([(Int.ofNat 1875000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 2625000000000)], [(Int.ofNat 2250000000000)])⟩,
      ⟨5, ([(Int.ofNat 3375000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨0, ([(Int.ofNat 3750000000000)], [(Int.negSucc 1124999999999)])⟩,
      ⟨0, ([(Int.ofNat 4500000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨2, ([(Int.ofNat 5625000000000)], [(Int.ofNat 3750000000000)])⟩,
      ⟨2, ([(Int.ofNat 6000000000000)], [(Int.ofNat 2250000000000)])⟩,
      ⟨2, ([(Int.ofNat 6075000000000)], [(Int.ofNat 2925000000000)])⟩,
      ⟨2, ([(Int.ofNat 6375000000000)], [(Int.ofNat 2250000000000)])⟩,
      ⟨3, ([(Int.negSucc 3674999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 3074999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.ofNat 300000000000)], [(Int.ofNat 4950000000000)])⟩,
      ⟨5, ([(Int.ofNat 375000000000)], [(Int.negSucc 4424999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 1050000000000)], [(Int.ofNat 4950000000000)])⟩,
      ⟨2, ([(Int.ofNat 6000000000000)], [(Int.ofNat 1875000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.negSucc 2999999999999)])⟩,
      ⟨3, ([(Int.negSucc 5999999999999)], [(Int.ofNat 3825000000000)])⟩,
      ⟨3, ([(Int.negSucc 3449999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 2249999999999)], [(Int.ofNat 7500000000000)])⟩],
    last := 3 }

end ConwaySoifer.Simplified.Certificates.Data
