import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_300000_310000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_300000_310000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 3) 10), hi := (mkRat (Int.ofNat 31) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 600000000000)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 599999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 1350000000000)])⟩,
      ⟨0, ([(Int.ofNat 600000000000)], [(Int.negSucc 1349999999999)])⟩,
      ⟨2, ([(Int.ofNat 1500000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.ofNat 5400000000000)], [(Int.ofNat 3225000000000)])⟩,
      ⟨6, ([(Int.ofNat 8625000000000)], [(Int.negSucc 3224999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3374999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4800000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 5100000000000)])⟩,
      ⟨0, ([(Int.ofNat 360000000000)], [(Int.ofNat 4140000000000)])⟩,
      ⟨0, ([(Int.ofNat 2265000000000)], [(Int.negSucc 2264999999999)])⟩,
      ⟨2, ([(Int.ofNat 3150000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 3750000000000)], [(Int.ofNat 1350000000000)])⟩,
      ⟨0, ([(Int.ofNat 4875000000000)], [(Int.negSucc 899999999999)])⟩,
      ⟨6, ([(Int.ofNat 8025000000000)], [(Int.negSucc 2624999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3074999999999)])⟩,
      ⟨0, ([(Int.ofNat 3600000000000)], [(Int.negSucc 3374999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
