import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_210000_220000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_210000_220000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 21) 100), hi := (mkRat (Int.ofNat 11) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1004999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1004999999999)], [(Int.ofNat 630000000000)])⟩,
      ⟨0, ([(Int.negSucc 629999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 629999999999)], [(Int.ofNat 1005000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 629999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1004999999999)])⟩,
      ⟨0, ([(Int.ofNat 630000000000)], [(Int.negSucc 1004999999999)])⟩,
      ⟨0, ([(Int.ofNat 1890000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 6165000000000)], [(Int.ofNat 2460000000000)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3401999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4725000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 6090000000000)])⟩,
      ⟨3, ([(Int.negSucc 4109999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 494999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 7304999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1275000000000)])⟩,
      ⟨2, ([(Int.ofNat 600000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 1260000000000)], [(Int.ofNat 1500000000000)])⟩,
      ⟨5, ([(Int.ofNat 2055000000000)], [(Int.negSucc 8054999999999)])⟩,
      ⟨0, ([(Int.ofNat 3285000000000)], [(Int.ofNat 1890000000000)])⟩,
      ⟨0, ([(Int.ofNat 4275000000000)], [(Int.ofNat 600000000000)])⟩,
      ⟨2, ([(Int.ofNat 4500000000000)], [(Int.ofNat 4725000000000)])⟩,
      ⟨2, ([(Int.ofNat 6750000000000)], [(Int.ofNat 1620000000000)])⟩,
      ⟨2, ([(Int.ofNat 6750000000000)], [(Int.ofNat 1890000000000)])⟩,
      ⟨1, ([(Int.ofNat 7365000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨9, ([(Int.ofNat 8250000000000)], [(Int.negSucc 11651999999999)])⟩,
      ⟨6, ([(Int.ofNat 8670000000000)], [(Int.negSucc 2999999999999)])⟩,
      ⟨6, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3134999999999)])⟩,
      ⟨8, ([(Int.negSucc 13169999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8054999999999)], [(Int.ofNat 2625000000000)])⟩,
      ⟨3, ([(Int.negSucc 5669999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨4, ([(Int.negSucc 4724999999999)], [(Int.ofNat 225000000000)])⟩,
      ⟨3, ([(Int.negSucc 3179999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 330000000000)], [(Int.ofNat 5670000000000)])⟩,
      ⟨5, ([(Int.ofNat 600000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.ofNat 2250000000000)], [(Int.ofNat 4500000000000)])⟩,
      ⟨0, ([(Int.ofNat 2970000000000)], [(Int.ofNat 3780000000000)])⟩,
      ⟨5, ([(Int.ofNat 3780000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨0, ([(Int.ofNat 5670000000000)], [(Int.ofNat 330000000000)])⟩,
      ⟨0, ([(Int.ofNat 5670000000000)], [(Int.ofNat 900000000000)])⟩,
      ⟨2, ([(Int.ofNat 6480000000000)], [(Int.ofNat 1770000000000)])⟩,
      ⟨8, ([(Int.negSucc 14597999999999)], [(Int.ofNat 5598000000000)])⟩,
      ⟨8, ([(Int.negSucc 12224999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8249999999999)], [(Int.ofNat 3975000000000)])⟩,
      ⟨4, ([(Int.negSucc 5414999999999)], [(Int.negSucc 3584999999999)])⟩,
      ⟨4, ([(Int.negSucc 3374999999999)], [(Int.ofNat 45000000000)])⟩,
      ⟨3, ([(Int.negSucc 3134999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨5, ([(Int.negSucc 2597999999999)], [(Int.negSucc 6401999999999)])⟩,
      ⟨4, ([(Int.negSucc 1319999999999)], [(Int.ofNat 0)])⟩],
    last := 4 }

end ConwaySoifer.Simplified.Certificates.Data
