import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Aown_260000_270000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Aown_260000_270000 : CertData :=
  { case := Case.Aown,
    lo := (mkRat (Int.ofNat 13) 50), hi := (mkRat (Int.ofNat 27) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1169999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1169999999999)], [(Int.ofNat 795000000000)])⟩,
      ⟨0, ([(Int.negSucc 794999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 794999999999)])⟩,
      ⟨2, ([(Int.ofNat 270000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1169999999999)])⟩,
      ⟨0, ([(Int.ofNat 795000000000)], [(Int.negSucc 1169999999999)])⟩,
      ⟨2, ([(Int.ofNat 2340000000000)], [(Int.ofNat 6750000000000)])⟩,
      ⟨0, ([(Int.ofNat 2685000000000)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.ofNat 5430000000000)], [(Int.ofNat 3570000000000)])⟩,
      ⟨2, ([(Int.ofNat 5850000000000)], [(Int.ofNat 2625000000000)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4788000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 5490000000000)])⟩,
      ⟨3, ([(Int.negSucc 5249999999999)], [(Int.ofNat 7830000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 2595000000000)])⟩,
      ⟨2, ([(Int.ofNat 2250000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 4320000000000)], [(Int.ofNat 930000000000)])⟩,
      ⟨2, ([(Int.ofNat 6000000000000)], [(Int.ofNat 2220000000000)])⟩,
      ⟨2, ([(Int.ofNat 6180000000000)], [(Int.ofNat 2820000000000)])⟩,
      ⟨2, ([(Int.ofNat 6375000000000)], [(Int.ofNat 2340000000000)])⟩,
      ⟨6, ([(Int.ofNat 8850000000000)], [(Int.negSucc 2999999999999)])⟩,
      ⟨0, ([(Int.ofNat 225000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.ofNat 1125000000000)], [(Int.negSucc 1559999999999)])⟩,
      ⟨0, ([(Int.ofNat 1560000000000)], [(Int.ofNat 4815000000000)])⟩,
      ⟨0, ([(Int.ofNat 4212000000000)], [(Int.ofNat 2163000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
