import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_200000_210000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_200000_210000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 1) 5), hi := (mkRat (Int.ofNat 21) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 974999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 974999999999)], [(Int.ofNat 600000000000)])⟩,
      ⟨0, ([(Int.negSucc 599999999999)], [(Int.ofNat 975000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 975000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 600000000000)])⟩,
      ⟨0, ([(Int.ofNat 6300000000000)], [(Int.negSucc 5999999999999)])⟩,
      ⟨0, ([(Int.ofNat 6375000000000)], [(Int.negSucc 5774999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10124999999999)])⟩,
      ⟨5, ([(Int.ofNat 5925000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.negSucc 4499999999999)])⟩,
      ⟨4, ([(Int.negSucc 3974999999999)], [(Int.negSucc 1199999999999)])⟩,
      ⟨4, ([(Int.negSucc 3899999999999)], [(Int.negSucc 599999999999)])⟩,
      ⟨8, ([(Int.negSucc 13049999999999)], [(Int.ofNat 4050000000000)])⟩,
      ⟨3, ([(Int.negSucc 8099999999999)], [(Int.ofNat 3975000000000)])⟩,
      ⟨3, ([(Int.negSucc 7499999999999)], [(Int.ofNat 3900000000000)])⟩,
      ⟨3, ([(Int.negSucc 6374999999999)], [(Int.ofNat 3975000000000)])⟩,
      ⟨3, ([(Int.negSucc 4724999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨5, ([(Int.negSucc 1649999999999)], [(Int.negSucc 6599999999999)])⟩,
      ⟨8, ([(Int.negSucc 13949999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 3989999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 509999999999)], [(Int.ofNat 5760000000000)])⟩,
      ⟨0, ([(Int.ofNat 3240000000000)], [(Int.negSucc 4499999999999)])⟩,
      ⟨0, ([(Int.ofNat 3600000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨3, ([(Int.negSucc 8399999999999)], [(Int.ofNat 3900000000000)])⟩,
      ⟨3, ([(Int.negSucc 6749999999999)], [(Int.ofNat 8400000000000)])⟩,
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨4, ([(Int.negSucc 3599999999999)], [(Int.negSucc 524999999999)])⟩,
      ⟨4, ([(Int.negSucc 3599999999999)], [(Int.negSucc 149999999999)])⟩,
      ⟨8, ([(Int.negSucc 12824999999999)], [(Int.ofNat 3825000000000)])⟩,
      ⟨8, ([(Int.negSucc 12374999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨8, ([(Int.negSucc 11174999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3825000000000)])⟩,
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 3600000000000)])⟩,
      ⟨3, ([(Int.negSucc 5099999999999)], [(Int.ofNat 3600000000000)])⟩,
      ⟨3, ([(Int.negSucc 4349999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨4, ([(Int.negSucc 3374999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 599999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨8, ([(Int.negSucc 12749999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨8, ([(Int.negSucc 10799999999999)], [(Int.ofNat 8550000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 3600000000000)])⟩,
      ⟨3, ([(Int.negSucc 6974999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨2, ([(Int.negSucc 5399999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 4949999999999)], [(Int.ofNat 6750000000000)])⟩,
      ⟨2, ([(Int.negSucc 599999999999)], [(Int.ofNat 4350000000000)])⟩,
      ⟨7, ([(Int.ofNat 3900000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 5624999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 4874999999999)], [(Int.ofNat 6675000000000)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.ofNat 1800000000000)])⟩,
      ⟨3, ([(Int.negSucc 2759999999999)], [(Int.ofNat 2760000000000)])⟩,
      ⟨2, ([(Int.negSucc 1799999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨1, ([(Int.ofNat 3600000000000)], [(Int.ofNat 4650000000000)])⟩,
      ⟨0, ([(Int.ofNat 6675000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.negSucc 1799999999999)], [(Int.ofNat 0)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
