import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_230000_240000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_230000_240000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 23) 100), hi := (mkRat (Int.ofNat 6) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1064999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1064999999999)], [(Int.ofNat 690000000000)])⟩,
      ⟨0, ([(Int.negSucc 1034999999999)], [(Int.ofNat 285000000000)])⟩,
      ⟨0, ([(Int.negSucc 1034999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 1035000000000)])⟩,
      ⟨0, ([(Int.negSucc 689999999999)], [(Int.ofNat 1065000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 1065000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 900000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 690000000000)])⟩,
      ⟨0, ([(Int.ofNat 690000000000)], [(Int.ofNat 435000000000)])⟩,
      ⟨0, ([(Int.ofNat 5895000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨0, ([(Int.ofNat 6240000000000)], [(Int.negSucc 5489999999999)])⟩,
      ⟨9, ([(Int.ofNat 8280000000000)], [(Int.negSucc 10154999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10319999999999)])⟩,
      ⟨5, ([(Int.ofNat 5175000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨5, ([(Int.ofNat 5640000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 4634999999999)], [(Int.negSucc 4364999999999)])⟩,
      ⟨4, ([(Int.negSucc 4139999999999)], [(Int.negSucc 359999999999)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.negSucc 1034999999999)])⟩,
      ⟨8, ([(Int.negSucc 13139999999999)], [(Int.ofNat 4140000000000)])⟩,
      ⟨3, ([(Int.negSucc 8309999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨3, ([(Int.negSucc 5174999999999)], [(Int.ofNat 4275000000000)])⟩,
      ⟨3, ([(Int.negSucc 4859999999999)], [(Int.ofNat 4374000000000)])⟩,
      ⟨5, ([(Int.negSucc 1904999999999)], [(Int.negSucc 6374999999999)])⟩,
      ⟨0, ([(Int.negSucc 689999999999)], [(Int.negSucc 434999999999)])⟩,
      ⟨8, ([(Int.negSucc 14084999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 4034999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 374999999999)], [(Int.ofNat 5274000000000)])⟩,
      ⟨0, ([(Int.ofNat 3105000000000)], [(Int.negSucc 4499999999999)])⟩,
      ⟨9, ([(Int.ofNat 6405000000000)], [(Int.negSucc 15404999999999)])⟩,
      ⟨3, ([(Int.negSucc 8900999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨3, ([(Int.negSucc 6404999999999)], [(Int.ofNat 8280000000000)])⟩,
      ⟨4, ([(Int.negSucc 3725999999999)], [(Int.negSucc 398999999999)])⟩,
      ⟨3, ([(Int.negSucc 2384999999999)], [(Int.ofNat 2385000000000)])⟩,
      ⟨0, ([(Int.negSucc 434999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨7, ([(Int.ofNat 4905000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 5145000000000)], [(Int.ofNat 3105000000000)])⟩,
      ⟨8, ([(Int.negSucc 12959999999999)], [(Int.ofNat 3960000000000)])⟩,
      ⟨8, ([(Int.negSucc 10799999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8309999999999)], [(Int.ofNat 3810000000000)])⟩,
      ⟨4, ([(Int.negSucc 5819999999999)], [(Int.ofNat 2070000000000)])⟩,
      ⟨4, ([(Int.negSucc 2999999999999)], [(Int.ofNat 1035000000000)])⟩,
      ⟨2, ([(Int.negSucc 2759999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨5, ([(Int.ofNat 4500000000000)], [(Int.negSucc 8225999999999)])⟩,
      ⟨0, ([(Int.ofNat 6375000000000)], [(Int.negSucc 5339999999999)])⟩,
      ⟨8, ([(Int.negSucc 12794999999999)], [(Int.ofNat 3795000000000)])⟩,
      ⟨8, ([(Int.negSucc 10379999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3810000000000)])⟩,
      ⟨2, ([(Int.negSucc 5879999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 4559999999999)], [(Int.negSucc 4439999999999)])⟩,
      ⟨4, ([(Int.negSucc 2759999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨5, ([(Int.negSucc 2069999999999)], [(Int.negSucc 5999999999999)])⟩,
      ⟨0, ([(Int.negSucc 1859999999999)], [(Int.ofNat 0)])⟩,
      ⟨1, ([(Int.ofNat 2415000000000)], [(Int.ofNat 6210000000000)])⟩,
      ⟨1, ([(Int.ofNat 2460000000000)], [(Int.ofNat 3750000000000)])⟩,
      ⟨0, ([(Int.ofNat 3105000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.ofNat 4860000000000)], [(Int.negSucc 2984999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
