import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_330000_340000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_330000_340000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 33) 100), hi := (mkRat (Int.ofNat 17) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1484999999999)], [(Int.ofNat 735000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 734999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 1485000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1125000000000)])⟩,
      ⟨0, ([(Int.ofNat 735000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.ofNat 5175000000000)], [(Int.negSucc 5039999999999)])⟩,
      ⟨0, ([(Int.ofNat 5346000000000)], [(Int.negSucc 4595999999999)])⟩,
      ⟨9, ([(Int.ofNat 6720000000000)], [(Int.negSucc 11969999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 11069999999999)])⟩,
      ⟨3, ([(Int.negSucc 2759999999999)], [(Int.ofNat 2760000000000)])⟩,
      ⟨5, ([(Int.ofNat 3750000000000)], [(Int.negSucc 8204999999999)])⟩,
      ⟨5, ([(Int.ofNat 4545000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12284999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 7514999999999)], [(Int.ofNat 3193875000000)])⟩,
      ⟨4, ([(Int.negSucc 6749999999999)], [(Int.ofNat 3096000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.ofNat 2565000000000)])⟩,
      ⟨4, ([(Int.negSucc 5594999999999)], [(Int.negSucc 3404999999999)])⟩,
      ⟨4, ([(Int.negSucc 4709999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 2249999999999)], [(Int.ofNat 5040000000000)])⟩,
      ⟨2, ([(Int.negSucc 134999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨8, ([(Int.negSucc 13970999999999)], [(Int.ofNat 4971000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4830000000000)])⟩,
      ⟨3, ([(Int.negSucc 5234999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨5, ([(Int.negSucc 3164999999999)], [(Int.negSucc 5834999999999)])⟩,
      ⟨0, ([(Int.negSucc 1604999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.ofNat 5250000000000)], [(Int.negSucc 5159999999999)])⟩,
      ⟨0, ([(Int.negSucc 2729999999999)], [(Int.ofNat 2730000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
