import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_300000_310000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_300000_310000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 3) 10), hi := (mkRat (Int.ofNat 31) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 600000000000)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 1350000000000)])⟩,
      ⟨0, ([(Int.ofNat 600000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.ofNat 5400000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.negSucc 4949999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10799999999999)])⟩,
      ⟨3, ([(Int.negSucc 2609999999999)], [(Int.ofNat 2610000000000)])⟩,
      ⟨5, ([(Int.ofNat 4860000000000)], [(Int.negSucc 8984999999999)])⟩,
      ⟨5, ([(Int.ofNat 4875000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12524999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 6374999999999)], [(Int.ofNat 2700000000000)])⟩,
      ⟨4, ([(Int.negSucc 5549999999999)], [(Int.negSucc 3449999999999)])⟩,
      ⟨4, ([(Int.negSucc 5174999999999)], [(Int.ofNat 2250000000000)])⟩,
      ⟨4, ([(Int.negSucc 4049999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 1799999999999)], [(Int.ofNat 4425000000000)])⟩,
      ⟨8, ([(Int.negSucc 13424999999999)], [(Int.ofNat 4425000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4575000000000)])⟩,
      ⟨2, ([(Int.negSucc 5399999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 4139999999999)], [(Int.ofNat 7125000000000)])⟩],
    last := 2 }

end ConwaySoifer.Simplified.Certificates.Data
