import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_100000_110000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_100000_110000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 1) 10), hi := (mkRat (Int.ofNat 11) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.ofNat 900000000000)], [(Int.negSucc 899999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 9599999999999)])⟩,
      ⟨5, ([(Int.ofNat 7245000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 6599999999999)], [(Int.negSucc 2399999999999)])⟩,
      ⟨0, ([(Int.ofNat 4500000000000)], [(Int.negSucc 5399999999999)])⟩,
      ⟨0, ([(Int.ofNat 5250000000000)], [(Int.negSucc 6149999999999)])⟩,
      ⟨0, ([(Int.ofNat 5550000000000)], [(Int.negSucc 5999999999999)])⟩,
      ⟨3, ([(Int.negSucc 7499999999999)], [(Int.ofNat 7050000000000)])⟩,
      ⟨4, ([(Int.negSucc 4724999999999)], [(Int.negSucc 899999999999)])⟩,
      ⟨4, ([(Int.negSucc 2849999999999)], [(Int.negSucc 6149999999999)])⟩,
      ⟨8, ([(Int.negSucc 16649999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 15299999999999)], [(Int.ofNat 6300000000000)])⟩,
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 3600000000000)])⟩,
      ⟨5, ([(Int.negSucc 899999999999)], [(Int.negSucc 7874999999999)])⟩,
      ⟨5, ([(Int.negSucc 824999999999)], [(Int.negSucc 7799999999999)])⟩,
      ⟨8, ([(Int.negSucc 12524999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 12149999999999)], [(Int.ofNat 3150000000000)])⟩,
      ⟨3, ([(Int.negSucc 8099999999999)], [(Int.ofNat 3225000000000)])⟩,
      ⟨4, ([(Int.negSucc 5099999999999)], [(Int.ofNat 600000000000)])⟩,
      ⟨2, ([(Int.negSucc 899999999999)], [(Int.ofNat 5775000000000)])⟩,
      ⟨0, ([(Int.ofNat 4275000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨0, ([(Int.ofNat 5625000000000)], [(Int.negSucc 6524999999999)])⟩,
      ⟨8, ([(Int.negSucc 11699999999999)], [(Int.ofNat 8325000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 2850000000000)])⟩,
      ⟨2, ([(Int.negSucc 5399999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 3974999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨7, ([(Int.ofNat 6300000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 6149999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 5249999999999)], [(Int.ofNat 8100000000000)])⟩,
      ⟨2, ([(Int.negSucc 899999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨1, ([(Int.ofNat 4050000000000)], [(Int.ofNat 3750000000000)])⟩,
      ⟨1, ([(Int.ofNat 4125000000000)], [(Int.ofNat 3255000000000)])⟩,
      ⟨0, ([(Int.ofNat 7380000000000)], [(Int.negSucc 7004999999999)])⟩,
      ⟨0, ([(Int.ofNat 7650000000000)], [(Int.negSucc 5999999999999)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 7650000000000)])⟩,
      ⟨3, ([(Int.negSucc 4874999999999)], [(Int.ofNat 5775000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.ofNat 900000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 600000000000)])⟩,
      ⟨1, ([(Int.ofNat 2850000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 7500000000000)], [(Int.negSucc 5249999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
