import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_150000_160000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_150000_160000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 3) 20), hi := (mkRat (Int.ofNat 4) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 449999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.ofNat 450000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 1350000000000)], [(Int.negSucc 1349999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 9824999999999)])⟩,
      ⟨5, ([(Int.ofNat 6600000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 5399999999999)], [(Int.negSucc 3599999999999)])⟩,
      ⟨0, ([(Int.ofNat 3600000000000)], [(Int.negSucc 4499999999999)])⟩,
      ⟨0, ([(Int.ofNat 4050000000000)], [(Int.negSucc 4949999999999)])⟩,
      ⟨0, ([(Int.ofNat 4050000000000)], [(Int.negSucc 4424999999999)])⟩,
      ⟨8, ([(Int.negSucc 14399999999999)], [(Int.ofNat 5400000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 6570000000000)])⟩,
      ⟨3, ([(Int.negSucc 6569999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.negSucc 569999999999)])⟩,
      ⟨4, ([(Int.negSucc 4049999999999)], [(Int.negSucc 4499999999999)])⟩,
      ⟨4, ([(Int.negSucc 3674999999999)], [(Int.negSucc 5324999999999)])⟩,
      ⟨0, ([(Int.negSucc 449999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨8, ([(Int.negSucc 15599999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 12674999999999)], [(Int.ofNat 3675000000000)])⟩,
      ⟨3, ([(Int.negSucc 8024999999999)], [(Int.ofNat 5400000000000)])⟩,
      ⟨3, ([(Int.negSucc 5624999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨3, ([(Int.negSucc 5174999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨0, ([(Int.negSucc 824999999999)], [(Int.ofNat 450000000000)])⟩,
      ⟨8, ([(Int.negSucc 15224999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8399999999999)], [(Int.ofNat 5400000000000)])⟩,
      ⟨3, ([(Int.negSucc 8099999999999)], [(Int.ofNat 5100000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 2399999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨5, ([(Int.negSucc 1349999999999)], [(Int.negSucc 7274999999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 825000000000)])⟩,
      ⟨0, ([(Int.ofNat 4125000000000)], [(Int.negSucc 5399999999999)])⟩,
      ⟨0, ([(Int.ofNat 4725000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨8, ([(Int.negSucc 14924999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8549999999999)], [(Int.ofNat 4800000000000)])⟩,
      ⟨4, ([(Int.negSucc 6299999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨4, ([(Int.negSucc 5324999999999)], [(Int.ofNat 0)])⟩,
      ⟨5, ([(Int.negSucc 1349999999999)], [(Int.negSucc 7124999999999)])⟩,
      ⟨0, ([(Int.ofNat 3900000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨0, ([(Int.ofNat 4500000000000)], [(Int.negSucc 5849999999999)])⟩,
      ⟨0, ([(Int.ofNat 5550000000000)], [(Int.negSucc 5549999999999)])⟩,
      ⟨8, ([(Int.negSucc 14549999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8624999999999)], [(Int.ofNat 4050000000000)])⟩,
      ⟨4, ([(Int.negSucc 4424999999999)], [(Int.negSucc 449999999999)])⟩,
      ⟨2, ([(Int.negSucc 3554999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 674999999999)], [(Int.ofNat 5925000000000)])⟩,
      ⟨0, ([(Int.ofNat 3750000000000)], [(Int.negSucc 5099999999999)])⟩,
      ⟨0, ([(Int.ofNat 4650000000000)], [(Int.negSucc 5999999999999)])⟩,
      ⟨0, ([(Int.ofNat 6750000000000)], [(Int.negSucc 6569999999999)])⟩,
      ⟨8, ([(Int.negSucc 14399999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8549999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨3, ([(Int.negSucc 8324999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨3, ([(Int.negSucc 4574999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨2, ([(Int.negSucc 4424999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 2699999999999)], [(Int.negSucc 299999999999)])⟩,
      ⟨2, ([(Int.negSucc 674999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨7, ([(Int.ofNat 5400000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 7500000000000)], [(Int.negSucc 4124999999999)])⟩,
      ⟨8, ([(Int.negSucc 12149999999999)], [(Int.ofNat 3150000000000)])⟩,
      ⟨8, ([(Int.negSucc 11774999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3075000000000)])⟩,
      ⟨3, ([(Int.negSucc 6824999999999)], [(Int.ofNat 2700000000000)])⟩,
      ⟨2, ([(Int.negSucc 4949999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 3749999999999)], [(Int.ofNat 3300000000000)])⟩,
      ⟨2, ([(Int.ofNat 0)], [(Int.ofNat 4575000000000)])⟩,
      ⟨2, ([(Int.ofNat 2700000000000)], [(Int.ofNat 5550000000000)])⟩,
      ⟨0, ([(Int.negSucc 4124999999999)], [(Int.ofNat 6825000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
