import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_252500_255000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_252500_255000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 101) 400), hi := (mkRat (Int.ofNat 51) 200), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1136249999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1136249999999)], [(Int.ofNat 761250000000)])⟩,
      ⟨0, ([(Int.negSucc 761249999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 761249999999)], [(Int.ofNat 1136250000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 761249999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 1136250000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 761250000000)])⟩,
      ⟨0, ([(Int.ofNat 761250000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 5970000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨0, ([(Int.ofNat 6007500000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨9, ([(Int.ofNat 8250000000000)], [(Int.negSucc 10514999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10465499999999)])⟩,
      ⟨3, ([(Int.negSucc 2414999999999)], [(Int.ofNat 2415000000000)])⟩,
      ⟨5, ([(Int.ofNat 4909500000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨5, ([(Int.ofNat 5445000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12715499999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 2272500000000)])⟩,
      ⟨4, ([(Int.negSucc 4909499999999)], [(Int.ofNat 1909500000000)])⟩,
      ⟨4, ([(Int.negSucc 4859999999999)], [(Int.negSucc 4139999999999)])⟩,
      ⟨4, ([(Int.negSucc 4159499999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨4, ([(Int.negSucc 4090499999999)], [(Int.ofNat 715500000000)])⟩,
      ⟨2, ([(Int.negSucc 1514999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨2, ([(Int.negSucc 409499999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨8, ([(Int.negSucc 13214999999999)], [(Int.ofNat 4215000000000)])⟩,
      ⟨3, ([(Int.negSucc 8242499999999)], [(Int.ofNat 4117500000000)])⟩,
      ⟨3, ([(Int.negSucc 4567499999999)], [(Int.ofNat 6750000000000)])⟩,
      ⟨0, ([(Int.negSucc 1657499999999)], [(Int.ofNat 0)])⟩,
      ⟨8, ([(Int.negSucc 9757499999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4455000000000)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.ofNat 2272500000000)])⟩,
      ⟨0, ([(Int.negSucc 1139999999999)], [(Int.ofNat 1140000000000)])⟩,
      ⟨5, ([(Int.ofNat 4090500000000)], [(Int.negSucc 6340499999999)])⟩,
      ⟨1, ([(Int.ofNat 6375000000000)], [(Int.negSucc 1919999999999)])⟩,
      ⟨4, ([(Int.negSucc 3761249999999)], [(Int.negSucc 5238749999999)])⟩,
      ⟨0, ([(Int.negSucc 2272499999999)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.negSucc 2272499999999)], [(Int.ofNat 900000000000)])⟩,
      ⟨0, ([(Int.ofNat 1125000000000)], [(Int.ofNat 390000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
