import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_255000_260000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_255000_260000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 51) 200), hi := (mkRat (Int.ofNat 13) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1147499999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1147499999999)], [(Int.ofNat 772500000000)])⟩,
      ⟨0, ([(Int.negSucc 772499999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 772499999999)], [(Int.ofNat 1147500000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 772499999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 1147500000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 772500000000)])⟩,
      ⟨0, ([(Int.ofNat 772500000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 5940000000000)], [(Int.negSucc 5564999999999)])⟩,
      ⟨0, ([(Int.ofNat 6015000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨9, ([(Int.ofNat 8250000000000)], [(Int.negSucc 10529999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10505999999999)])⟩,
      ⟨3, ([(Int.negSucc 2429999999999)], [(Int.ofNat 2430000000000)])⟩,
      ⟨5, ([(Int.ofNat 4770000000000)], [(Int.negSucc 8519999999999)])⟩,
      ⟨5, ([(Int.ofNat 5340000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12755999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 2295000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.ofNat 2182500000000)])⟩,
      ⟨4, ([(Int.negSucc 4919999999999)], [(Int.negSucc 4079999999999)])⟩,
      ⟨4, ([(Int.negSucc 4868999999999)], [(Int.ofNat 1875000000000)])⟩,
      ⟨4, ([(Int.negSucc 4214999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨4, ([(Int.negSucc 4130999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨8, ([(Int.negSucc 13304999999999)], [(Int.ofNat 4305000000000)])⟩,
      ⟨3, ([(Int.negSucc 7880999999999)], [(Int.ofNat 4131000000000)])⟩,
      ⟨0, ([(Int.negSucc 1589999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 1499999999999)], [(Int.negSucc 179999999999)])⟩,
      ⟨8, ([(Int.negSucc 10880999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4410000000000)])⟩,
      ⟨2, ([(Int.negSucc 3442499999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨5, ([(Int.ofNat 3442500000000)], [(Int.negSucc 6374999999999)])⟩,
      ⟨5, ([(Int.ofNat 4125000000000)], [(Int.negSucc 6419999999999)])⟩,
      ⟨1, ([(Int.ofNat 6375000000000)], [(Int.negSucc 2294999999999)])⟩,
      ⟨4, ([(Int.negSucc 3968999999999)], [(Int.negSucc 5030999999999)])⟩,
      ⟨0, ([(Int.negSucc 2294999999999)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.ofNat 2295000000000)], [(Int.ofNat 0)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
