import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_190000_200000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_190000_200000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 19) 100), hi := (mkRat (Int.ofNat 1) 5), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 944999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 944999999999)], [(Int.ofNat 570000000000)])⟩,
      ⟨0, ([(Int.negSucc 764999999999)], [(Int.ofNat 765000000000)])⟩,
      ⟨0, ([(Int.negSucc 569999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 569999999999)], [(Int.ofNat 945000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 945000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 570000000000)])⟩,
      ⟨0, ([(Int.ofNat 6375000000000)], [(Int.negSucc 5804999999999)])⟩,
      ⟨0, ([(Int.ofNat 6435000000000)], [(Int.negSucc 6059999999999)])⟩,
      ⟨9, ([(Int.ofNat 8625000000000)], [(Int.negSucc 10139999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10064999999999)])⟩,
      ⟨5, ([(Int.ofNat 4725000000000)], [(Int.negSucc 8099999999999)])⟩,
      ⟨5, ([(Int.ofNat 6105000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 3959999999999)], [(Int.negSucc 5039999999999)])⟩,
      ⟨4, ([(Int.negSucc 3929999999999)], [(Int.negSucc 569999999999)])⟩,
      ⟨4, ([(Int.negSucc 3869999999999)], [(Int.negSucc 1379999999999)])⟩,
      ⟨8, ([(Int.negSucc 12869999999999)], [(Int.ofNat 3870000000000)])⟩,
      ⟨3, ([(Int.negSucc 8144999999999)], [(Int.ofNat 4020000000000)])⟩,
      ⟨3, ([(Int.negSucc 5624999999999)], [(Int.ofNat 3870000000000)])⟩,
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 3930000000000)])⟩,
      ⟨5, ([(Int.negSucc 1709999999999)], [(Int.negSucc 6749999999999)])⟩,
      ⟨8, ([(Int.negSucc 13589999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 3870000000000)])⟩,
      ⟨2, ([(Int.negSucc 4064999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 3854999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 557999999999)], [(Int.ofNat 5580000000000)])⟩,
      ⟨0, ([(Int.ofNat 3465000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3870000000000)])⟩,
      ⟨3, ([(Int.negSucc 6719999999999)], [(Int.ofNat 8250000000000)])⟩,
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 3870000000000)])⟩,
      ⟨2, ([(Int.negSucc 4349999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 4274999999999)], [(Int.ofNat 3900000000000)])⟩,
      ⟨2, ([(Int.negSucc 4072499999999)], [(Int.ofNat 8145000000000)])⟩,
      ⟨4, ([(Int.negSucc 2999999999999)], [(Int.negSucc 77999999999)])⟩,
      ⟨5, ([(Int.negSucc 1709999999999)], [(Int.negSucc 6539999999999)])⟩,
      ⟨1, ([(Int.ofNat 5172000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨8, ([(Int.negSucc 12374999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨8, ([(Int.negSucc 11279999999999)], [(Int.ofNat 8100000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3330000000000)])⟩,
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 3150000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 1710000000000)])⟩,
      ⟨2, ([(Int.negSucc 5129999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 3419999999999)], [(Int.ofNat 3000000000000)])⟩,
      ⟨4, ([(Int.negSucc 2294999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 629999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨0, ([(Int.ofNat 3165000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.ofNat 3915000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨7, ([(Int.ofNat 4170000000000)], [(Int.ofNat 8250000000000)])⟩,
      ⟨1, ([(Int.ofNat 4770000000000)], [(Int.ofNat 855000000000)])⟩,
      ⟨1, ([(Int.ofNat 5130000000000)], [(Int.ofNat 3000000000000)])⟩,
      ⟨0, ([(Int.ofNat 6720000000000)], [(Int.negSucc 5594999999999)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 6180000000000)])⟩,
      ⟨8, ([(Int.negSucc 12044999999999)], [(Int.ofNat 3045000000000)])⟩,
      ⟨8, ([(Int.negSucc 10439999999999)], [(Int.ofNat 7875000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3078000000000)])⟩,
      ⟨3, ([(Int.negSucc 6749999999999)], [(Int.ofNat 2565000000000)])⟩,
      ⟨3, ([(Int.negSucc 5999999999999)], [(Int.ofNat 7710000000000)])⟩,
      ⟨2, ([(Int.negSucc 5999999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5834999999999)], [(Int.ofNat 1710000000000)])⟩,
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 569999999999)], [(Int.ofNat 3570000000000)])⟩,
      ⟨1, ([(Int.ofNat 3870000000000)], [(Int.ofNat 4755000000000)])⟩,
      ⟨1, ([(Int.ofNat 3900000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 6435000000000)], [(Int.negSucc 3824999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
