import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_290000_300000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_290000_300000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 29) 100), hi := (mkRat (Int.ofNat 3) 10), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1304999999999)], [(Int.ofNat 555000000000)])⟩,
      ⟨0, ([(Int.negSucc 1304999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 554999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 1305000000000)])⟩,
      ⟨0, ([(Int.negSucc 554999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 270000000000)], [(Int.ofNat 900000000000)])⟩,
      ⟨0, ([(Int.ofNat 555000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 555000000000)])⟩,
      ⟨0, ([(Int.ofNat 5520000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨0, ([(Int.ofNat 5745000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10709999999999)])⟩,
      ⟨3, ([(Int.negSucc 2594999999999)], [(Int.ofNat 2595000000000)])⟩,
      ⟨5, ([(Int.ofNat 4980000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12524999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 2520000000000)])⟩,
      ⟨4, ([(Int.negSucc 5414999999999)], [(Int.negSucc 3584999999999)])⟩,
      ⟨4, ([(Int.negSucc 4334999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 2639999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 1889999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨2, ([(Int.negSucc 1874999999999)], [(Int.ofNat 4485000000000)])⟩,
      ⟨2, ([(Int.negSucc 947999999999)], [(Int.ofNat 4698000000000)])⟩,
      ⟨8, ([(Int.negSucc 13649999999999)], [(Int.ofNat 4650000000000)])⟩,
      ⟨3, ([(Int.negSucc 8414999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨3, ([(Int.negSucc 4874999999999)], [(Int.ofNat 7485000000000)])⟩,
      ⟨8, ([(Int.negSucc 9854999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4605000000000)])⟩,
      ⟨2, ([(Int.negSucc 3014999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.negSucc 5414999999999)], [(Int.ofNat 9000000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
