import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_320000_330000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_320000_330000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 8) 25), hi := (mkRat (Int.ofNat 33) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1439999999999)], [(Int.ofNat 690000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 689999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 1440000000000)])⟩,
      ⟨0, ([(Int.ofNat 690000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 690000000000)])⟩,
      ⟨0, ([(Int.ofNat 4875000000000)], [(Int.negSucc 4679999999999)])⟩,
      ⟨0, ([(Int.ofNat 5160000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.ofNat 5250000000000)], [(Int.negSucc 4889999999999)])⟩,
      ⟨0, ([(Int.ofNat 5835000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨9, ([(Int.ofNat 6750000000000)], [(Int.negSucc 12374999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10919999999999)])⟩,
      ⟨3, ([(Int.negSucc 2834999999999)], [(Int.ofNat 2835000000000)])⟩,
      ⟨5, ([(Int.ofNat 3840000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨5, ([(Int.ofNat 4680000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12509999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 6749999999999)], [(Int.ofNat 2934000000000)])⟩,
      ⟨4, ([(Int.negSucc 5504999999999)], [(Int.negSucc 3494999999999)])⟩,
      ⟨4, ([(Int.negSucc 5129999999999)], [(Int.ofNat 2250000000000)])⟩,
      ⟨4, ([(Int.negSucc 4334999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 2954999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 2249999999999)], [(Int.ofNat 5130000000000)])⟩,
      ⟨2, ([(Int.negSucc 1994999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨2, ([(Int.negSucc 284999999999)], [(Int.ofNat 5160000000000)])⟩,
      ⟨8, ([(Int.negSucc 13634999999999)], [(Int.ofNat 4635000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 4434000000000)])⟩,
      ⟨3, ([(Int.negSucc 5459999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 5183999999999)], [(Int.ofNat 8559000000000)])⟩,
      ⟨8, ([(Int.negSucc 9194999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4620000000000)])⟩,
      ⟨2, ([(Int.negSucc 2624999999999)], [(Int.ofNat 5160000000000)])⟩,
      ⟨0, ([(Int.negSucc 5339999999999)], [(Int.ofNat 9000000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
