import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_210000_220000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_210000_220000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 21) 100), hi := (mkRat (Int.ofNat 11) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1004999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1004999999999)], [(Int.ofNat 630000000000)])⟩,
      ⟨0, ([(Int.negSucc 629999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 629999999999)], [(Int.ofNat 1005000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 1005000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 630000000000)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.negSucc 5669999999999)])⟩,
      ⟨0, ([(Int.ofNat 6165000000000)], [(Int.negSucc 5789999999999)])⟩,
      ⟨0, ([(Int.ofNat 6375000000000)], [(Int.negSucc 5669999999999)])⟩,
      ⟨9, ([(Int.ofNat 8250000000000)], [(Int.negSucc 10139999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10184999999999)])⟩,
      ⟨5, ([(Int.ofNat 5250000000000)], [(Int.negSucc 8651999999999)])⟩,
      ⟨5, ([(Int.ofNat 5865000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 4454999999999)], [(Int.negSucc 4544999999999)])⟩,
      ⟨4, ([(Int.negSucc 3869999999999)], [(Int.negSucc 629999999999)])⟩,
      ⟨8, ([(Int.negSucc 12974999999999)], [(Int.ofNat 3975000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 3975000000000)])⟩,
      ⟨3, ([(Int.negSucc 4724999999999)], [(Int.ofNat 3975000000000)])⟩,
      ⟨5, ([(Int.negSucc 1769999999999)], [(Int.negSucc 6479999999999)])⟩,
      ⟨8, ([(Int.negSucc 13919999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 4154999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.negSucc 149999999999)])⟩,
      ⟨2, ([(Int.negSucc 749999999999)], [(Int.ofNat 5670000000000)])⟩,
      ⟨0, ([(Int.ofNat 3330000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.ofNat 6165000000000)], [(Int.negSucc 5999999999999)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3945000000000)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 629999999999)])⟩,
      ⟨3, ([(Int.negSucc 2114999999999)], [(Int.ofNat 2115000000000)])⟩,
      ⟨7, ([(Int.ofNat 4875000000000)], [(Int.ofNat 8850000000000)])⟩,
      ⟨1, ([(Int.ofNat 5175000000000)], [(Int.ofNat 2835000000000)])⟩,
      ⟨1, ([(Int.ofNat 5220000000000)], [(Int.ofNat 1530000000000)])⟩,
      ⟨8, ([(Int.negSucc 10544999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3855000000000)])⟩,
      ⟨2, ([(Int.negSucc 5894999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.ofNat 1890000000000)])⟩,
      ⟨2, ([(Int.negSucc 3001499999999)], [(Int.ofNat 5220000000000)])⟩,
      ⟨4, ([(Int.negSucc 2834999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨4, ([(Int.negSucc 2222999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 1889999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨0, ([(Int.ofNat 6480000000000)], [(Int.negSucc 5579999999999)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 6750000000000)])⟩,
      ⟨8, ([(Int.negSucc 11501999999999)], [(Int.ofNat 2502000000000)])⟩,
      ⟨8, ([(Int.negSucc 10439999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3402000000000)])⟩,
      ⟨2, ([(Int.negSucc 6029999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 4484999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1772999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 1529999999999)], [(Int.ofNat 630000000000)])⟩,
      ⟨1, ([(Int.ofNat 2220000000000)], [(Int.ofNat 3780000000000)])⟩,
      ⟨7, ([(Int.ofNat 2250000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 2340000000000)], [(Int.ofNat 6375000000000)])⟩,
      ⟨0, ([(Int.ofNat 4725000000000)], [(Int.negSucc 2624999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
