import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_260000_270000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_260000_270000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 13) 50), hi := (mkRat (Int.ofNat 27) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1169999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1169999999999)], [(Int.ofNat 795000000000)])⟩,
      ⟨0, ([(Int.negSucc 794999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 794999999999)], [(Int.ofNat 1170000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 794999999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 1170000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 795000000000)])⟩,
      ⟨0, ([(Int.ofNat 795000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 5490000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨0, ([(Int.ofNat 5850000000000)], [(Int.negSucc 5474999999999)])⟩,
      ⟨0, ([(Int.ofNat 6030000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨9, ([(Int.ofNat 8250000000000)], [(Int.negSucc 10559999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10559999999999)])⟩,
      ⟨3, ([(Int.negSucc 2504999999999)], [(Int.ofNat 2505000000000)])⟩,
      ⟨5, ([(Int.ofNat 4788000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨5, ([(Int.ofNat 5310000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12836999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 2340000000000)])⟩,
      ⟨4, ([(Int.negSucc 5009999999999)], [(Int.negSucc 3989999999999)])⟩,
      ⟨4, ([(Int.negSucc 4679999999999)], [(Int.ofNat 1875000000000)])⟩,
      ⟨4, ([(Int.negSucc 4211999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨2, ([(Int.negSucc 1694999999999)], [(Int.ofNat 4320000000000)])⟩,
      ⟨2, ([(Int.negSucc 374999999999)], [(Int.ofNat 4680000000000)])⟩,
      ⟨8, ([(Int.negSucc 13319999999999)], [(Int.ofNat 4320000000000)])⟩,
      ⟨3, ([(Int.negSucc 8336999999999)], [(Int.ofNat 4212000000000)])⟩,
      ⟨3, ([(Int.negSucc 4679999999999)], [(Int.ofNat 6930000000000)])⟩,
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 6660000000000)])⟩,
      ⟨0, ([(Int.negSucc 1739999999999)], [(Int.ofNat 0)])⟩,
      ⟨8, ([(Int.negSucc 9809999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4320000000000)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.ofNat 2340000000000)])⟩,
      ⟨0, ([(Int.negSucc 1169999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨5, ([(Int.ofNat 2625000000000)], [(Int.negSucc 6134999999999)])⟩,
      ⟨5, ([(Int.ofNat 4395000000000)], [(Int.negSucc 6374999999999)])⟩,
      ⟨1, ([(Int.ofNat 6375000000000)], [(Int.negSucc 2339999999999)])⟩,
      ⟨4, ([(Int.negSucc 3944999999999)], [(Int.negSucc 5054999999999)])⟩,
      ⟨0, ([(Int.negSucc 2339999999999)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.ofNat 2340000000000)], [(Int.ofNat 0)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
