import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_170000_180000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_170000_180000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 17) 100), hi := (mkRat (Int.ofNat 9) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 884999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 509999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 509999999999)], [(Int.ofNat 885000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 510000000000)])⟩,
      ⟨0, ([(Int.ofNat 6375000000000)], [(Int.negSucc 5939999999999)])⟩,
      ⟨0, ([(Int.ofNat 6495000000000)], [(Int.negSucc 6119999999999)])⟩,
      ⟨9, ([(Int.ofNat 8520000000000)], [(Int.negSucc 10019999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 9929999999999)])⟩,
      ⟨5, ([(Int.ofNat 6000000000000)], [(Int.negSucc 8753999999999)])⟩,
      ⟨5, ([(Int.ofNat 6345000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 4109999999999)], [(Int.negSucc 764999999999)])⟩,
      ⟨4, ([(Int.negSucc 4049999999999)], [(Int.negSucc 1124999999999)])⟩,
      ⟨4, ([(Int.negSucc 3878999999999)], [(Int.negSucc 5120999999999)])⟩,
      ⟨4, ([(Int.negSucc 3869999999999)], [(Int.negSucc 2249999999999)])⟩,
      ⟨8, ([(Int.negSucc 12869999999999)], [(Int.ofNat 3870000000000)])⟩,
      ⟨3, ([(Int.negSucc 7979999999999)], [(Int.ofNat 3990000000000)])⟩,
      ⟨3, ([(Int.negSucc 6749999999999)], [(Int.ofNat 3870000000000)])⟩,
      ⟨3, ([(Int.negSucc 4874999999999)], [(Int.ofNat 4110000000000)])⟩,
      ⟨5, ([(Int.negSucc 1499999999999)], [(Int.negSucc 6989999999999)])⟩,
      ⟨0, ([(Int.negSucc 509999999999)], [(Int.negSucc 389999999999)])⟩,
      ⟨8, ([(Int.negSucc 14114999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.negSucc 179999999999)])⟩,
      ⟨4, ([(Int.negSucc 3968999999999)], [(Int.negSucc 440999999999)])⟩,
      ⟨2, ([(Int.negSucc 3764999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 509999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨0, ([(Int.ofNat 3750000000000)], [(Int.negSucc 5279999999999)])⟩,
      ⟨0, ([(Int.ofNat 6555000000000)], [(Int.negSucc 6374999999999)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3879000000000)])⟩,
      ⟨3, ([(Int.negSucc 6959999999999)], [(Int.ofNat 8250000000000)])⟩,
      ⟨3, ([(Int.negSucc 4409999999999)], [(Int.ofNat 3969000000000)])⟩,
      ⟨4, ([(Int.negSucc 3059999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 389999999999)], [(Int.ofNat 900000000000)])⟩,
      ⟨7, ([(Int.ofNat 5370000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 7365000000000)], [(Int.negSucc 4124999999999)])⟩,
      ⟨8, ([(Int.negSucc 12374999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨8, ([(Int.negSucc 11378999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3300000000000)])⟩,
      ⟨2, ([(Int.negSucc 5120999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 440999999999)], [(Int.ofNat 4410000000000)])⟩,
      ⟨7, ([(Int.ofNat 8379000000000)], [(Int.ofNat 3375000000000)])⟩,
      ⟨0, ([(Int.ofNat 3879000000000)], [(Int.ofNat 5121000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
