import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_280000_290000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_280000_290000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 7) 25), hi := (mkRat (Int.ofNat 29) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1259999999999)], [(Int.ofNat 510000000000)])⟩,
      ⟨0, ([(Int.negSucc 1259999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 1214999999999)], [(Int.ofNat 840000000000)])⟩,
      ⟨0, ([(Int.negSucc 839999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 509999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 1260000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 840000000000)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 510000000000)])⟩,
      ⟨0, ([(Int.ofNat 5250000000000)], [(Int.negSucc 5039999999999)])⟩,
      ⟨0, ([(Int.ofNat 5640000000000)], [(Int.negSucc 5264999999999)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.negSucc 5039999999999)])⟩,
      ⟨9, ([(Int.ofNat 7875000000000)], [(Int.negSucc 10394999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10664999999999)])⟩,
      ⟨3, ([(Int.negSucc 2579999999999)], [(Int.ofNat 2580000000000)])⟩,
      ⟨5, ([(Int.ofNat 4665000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨5, ([(Int.ofNat 5070000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12674999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 6269999999999)], [(Int.ofNat 2520000000000)])⟩,
      ⟨4, ([(Int.negSucc 5219999999999)], [(Int.negSucc 3779999999999)])⟩,
      ⟨4, ([(Int.negSucc 4535999999999)], [(Int.ofNat 1911000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 1910999999999)], [(Int.ofNat 4536000000000)])⟩,
      ⟨2, ([(Int.negSucc 1874999999999)], [(Int.ofNat 4464000000000)])⟩,
      ⟨2, ([(Int.negSucc 1487999999999)], [(Int.ofNat 4464000000000)])⟩,
      ⟨8, ([(Int.negSucc 13424999999999)], [(Int.ofNat 4425000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 6300000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 4290000000000)])⟩,
      ⟨3, ([(Int.negSucc 4874999999999)], [(Int.ofNat 7320000000000)])⟩,
      ⟨0, ([(Int.negSucc 1838999999999)], [(Int.ofNat 0)])⟩,
      ⟨8, ([(Int.negSucc 9809999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4410000000000)])⟩,
      ⟨4, ([(Int.negSucc 3554999999999)], [(Int.ofNat 1680000000000)])⟩,
      ⟨2, ([(Int.negSucc 3359999999999)], [(Int.ofNat 5985000000000)])⟩,
      ⟨0, ([(Int.negSucc 827999999999)], [(Int.ofNat 1440000000000)])⟩,
      ⟨5, ([(Int.ofNat 3780000000000)], [(Int.negSucc 5999999999999)])⟩,
      ⟨8, ([(Int.negSucc 9734999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4395000000000)])⟩,
      ⟨2, ([(Int.negSucc 5534999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.ofNat 2520000000000)])⟩,
      ⟨4, ([(Int.negSucc 4088999999999)], [(Int.negSucc 4910999999999)])⟩,
      ⟨0, ([(Int.negSucc 2519999999999)], [(Int.negSucc 4604999999999)])⟩,
      ⟨0, ([(Int.negSucc 2519999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 2286000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
