import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_240000_250000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_240000_250000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 6) 25), hi := (mkRat (Int.ofNat 1) 4), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 405000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 720000000000)])⟩,
      ⟨0, ([(Int.negSucc 719999999999)], [(Int.negSucc 404999999999)])⟩,
      ⟨0, ([(Int.negSucc 719999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨0, ([(Int.negSucc 404999999999)], [(Int.negSucc 719999999999)])⟩,
      ⟨0, ([(Int.negSucc 404999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨0, ([(Int.ofNat 405000000000)], [(Int.ofNat 720000000000)])⟩,
      ⟨0, ([(Int.ofNat 720000000000)], [(Int.ofNat 405000000000)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.negSucc 5639999999999)])⟩,
      ⟨0, ([(Int.ofNat 6150000000000)], [(Int.negSucc 5399999999999)])⟩,
      ⟨9, ([(Int.ofNat 8190000000000)], [(Int.negSucc 10439999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10364999999999)])⟩,
      ⟨5, ([(Int.ofNat 5025000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨5, ([(Int.ofNat 5505000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 4784999999999)], [(Int.negSucc 4214999999999)])⟩,
      ⟨4, ([(Int.negSucc 4139999999999)], [(Int.negSucc 359999999999)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.negSucc 719999999999)])⟩,
      ⟨8, ([(Int.negSucc 13319999999999)], [(Int.ofNat 5820000000000)])⟩,
      ⟨8, ([(Int.negSucc 13229999999999)], [(Int.ofNat 4230000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 4320000000000)])⟩,
      ⟨3, ([(Int.negSucc 8084999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨3, ([(Int.negSucc 4679999999999)], [(Int.ofNat 4212000000000)])⟩,
      ⟨5, ([(Int.negSucc 1904999999999)], [(Int.negSucc 6374999999999)])⟩,
      ⟨8, ([(Int.negSucc 13814999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.negSucc 194999999999)])⟩,
      ⟨2, ([(Int.negSucc 3809999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 5625000000000)], [(Int.negSucc 5399999999999)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 6240000000000)])⟩,
      ⟨3, ([(Int.negSucc 8444999999999)], [(Int.ofNat 4320000000000)])⟩,
      ⟨3, ([(Int.negSucc 8279999999999)], [(Int.ofNat 4155000000000)])⟩,
      ⟨3, ([(Int.negSucc 2384999999999)], [(Int.ofNat 2385000000000)])⟩,
      ⟨8, ([(Int.negSucc 10754999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5909999999999)], [(Int.ofNat 2160000000000)])⟩,
      ⟨2, ([(Int.negSucc 5624999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 1605000000000)])⟩,
      ⟨2, ([(Int.negSucc 3887999999999)], [(Int.ofNat 6513000000000)])⟩,
      ⟨2, ([(Int.negSucc 3239999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨2, ([(Int.negSucc 1874999999999)], [(Int.ofNat 4320000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4170000000000)])⟩,
      ⟨0, ([(Int.negSucc 1814999999999)], [(Int.ofNat 0)])⟩,
      ⟨1, ([(Int.ofNat 2385000000000)], [(Int.ofNat 5175000000000)])⟩,
      ⟨7, ([(Int.ofNat 2388000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 2505000000000)], [(Int.ofNat 6120000000000)])⟩,
      ⟨0, ([(Int.ofNat 6615000000000)], [(Int.negSucc 3239999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
