import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_160000_170000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_160000_170000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 4) 25), hi := (mkRat (Int.ofNat 17) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 659999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 659999999999)], [(Int.ofNat 660000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 660000000000)])⟩,
      ⟨0, ([(Int.ofNat 480000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 6750000000000)], [(Int.negSucc 6269999999999)])⟩,
      ⟨9, ([(Int.ofNat 8625000000000)], [(Int.negSucc 9959999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 9884999999999)])⟩,
      ⟨3, ([(Int.negSucc 7559999999999)], [(Int.ofNat 7560000000000)])⟩,
      ⟨5, ([(Int.ofNat 4530000000000)], [(Int.negSucc 8279999999999)])⟩,
      ⟨5, ([(Int.ofNat 6465000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 3824999999999)], [(Int.negSucc 5174999999999)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 569999999999)])⟩,
      ⟨0, ([(Int.ofNat 3750000000000)], [(Int.negSucc 4709999999999)])⟩,
      ⟨8, ([(Int.negSucc 12764999999999)], [(Int.ofNat 3765000000000)])⟩,
      ⟨8, ([(Int.negSucc 12599999999999)], [(Int.ofNat 3825000000000)])⟩,
      ⟨3, ([(Int.negSucc 8069999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨3, ([(Int.negSucc 4319999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨4, ([(Int.negSucc 3599999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨5, ([(Int.negSucc 1439999999999)], [(Int.negSucc 7124999999999)])⟩,
      ⟨0, ([(Int.negSucc 479999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨8, ([(Int.negSucc 11639999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8099999999999)], [(Int.ofNat 3600000000000)])⟩,
      ⟨4, ([(Int.negSucc 5399999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨2, ([(Int.negSucc 4589999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 4349999999999)], [(Int.ofNat 3600000000000)])⟩,
      ⟨4, ([(Int.negSucc 3254999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 719999999999)], [(Int.ofNat 5595000000000)])⟩,
      ⟨0, ([(Int.ofNat 3735000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨5, ([(Int.ofNat 5040000000000)], [(Int.negSucc 8039999999999)])⟩,
      ⟨8, ([(Int.negSucc 12419999999999)], [(Int.ofNat 3420000000000)])⟩,
      ⟨8, ([(Int.negSucc 11384999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3420000000000)])⟩,
      ⟨3, ([(Int.negSucc 8519999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨3, ([(Int.negSucc 7184999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨3, ([(Int.negSucc 6749999999999)], [(Int.ofNat 8040000000000)])⟩,
      ⟨2, ([(Int.negSucc 5399999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 5249999999999)])⟩,
      ⟨3, ([(Int.negSucc 3749999999999)], [(Int.ofNat 3270000000000)])⟩,
      ⟨4, ([(Int.negSucc 3464999999999)], [(Int.negSucc 5534999999999)])⟩,
      ⟨4, ([(Int.negSucc 2564999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 959999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 884999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 209999999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 855000000000)])⟩,
      ⟨1, ([(Int.ofNat 4665000000000)], [(Int.ofNat 960000000000)])⟩,
      ⟨8, ([(Int.negSucc 12014999999999)], [(Int.ofNat 3015000000000)])⟩,
      ⟨8, ([(Int.negSucc 10919999999999)], [(Int.ofNat 7545000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 2910000000000)])⟩,
      ⟨3, ([(Int.negSucc 6749999999999)], [(Int.ofNat 2592000000000)])⟩,
      ⟨2, ([(Int.negSucc 5744999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 1919999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨7, ([(Int.ofNat 3600000000000)], [(Int.ofNat 8625000000000)])⟩,
      ⟨1, ([(Int.ofNat 3750000000000)], [(Int.ofNat 4290000000000)])⟩,
      ⟨0, ([(Int.ofNat 7080000000000)], [(Int.negSucc 5579999999999)])⟩,
      ⟨1, ([(Int.ofNat 7125000000000)], [(Int.negSucc 4244999999999)])⟩,
      ⟨0, ([(Int.ofNat 2160000000000)], [(Int.ofNat 0)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
