import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_250000_252500.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_250000_252500 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 1) 4), hi := (mkRat (Int.ofNat 101) 400), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨9, ([(Int.ofNat 8250000000000)], [(Int.negSucc 10499999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10424999999999)])⟩,
      ⟨3, ([(Int.negSucc 2399999999999)], [(Int.ofNat 2400000000000)])⟩,
      ⟨5, ([(Int.ofNat 4950000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨5, ([(Int.ofNat 5400000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12674999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 2250000000000)])⟩,
      ⟨4, ([(Int.negSucc 4949999999999)], [(Int.negSucc 4049999999999)])⟩,
      ⟨4, ([(Int.negSucc 4199999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨4, ([(Int.negSucc 4049999999999)], [(Int.ofNat 1050000000000)])⟩,
      ⟨2, ([(Int.negSucc 1874999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨2, ([(Int.negSucc 1499999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨2, ([(Int.negSucc 374999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨8, ([(Int.negSucc 13499999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨3, ([(Int.negSucc 8174999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨7, ([(Int.ofNat 3300000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 10049999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4425000000000)])⟩,
      ⟨2, ([(Int.negSucc 5624999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 3374999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨2, ([(Int.negSucc 2474999999999)], [(Int.ofNat 4950000000000)])⟩,
      ⟨1, ([(Int.ofNat 6675000000000)], [(Int.negSucc 2624999999999)])⟩,
      ⟨1, ([(Int.ofNat 2475000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨7, ([(Int.ofNat 2475000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨7, ([(Int.ofNat 9000000000000)], [(Int.ofNat 4050000000000)])⟩,
      ⟨0, ([(Int.ofNat 2625000000000)], [(Int.ofNat 6375000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
