import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_310000_320000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_310000_320000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 31) 100), hi := (mkRat (Int.ofNat 8) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1394999999999)], [(Int.ofNat 645000000000)])⟩,
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 644999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 1395000000000)])⟩,
      ⟨0, ([(Int.negSucc 644999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.negSucc 644999999999)], [(Int.ofNat 1395000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1080000000000)])⟩,
      ⟨0, ([(Int.ofNat 645000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.ofNat 5175000000000)], [(Int.negSucc 5021999999999)])⟩,
      ⟨0, ([(Int.ofNat 5772000000000)], [(Int.negSucc 5021999999999)])⟩,
      ⟨0, ([(Int.ofNat 5805000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨9, ([(Int.ofNat 6750000000000)], [(Int.negSucc 12329999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10844999999999)])⟩,
      ⟨3, ([(Int.negSucc 2729999999999)], [(Int.ofNat 2730000000000)])⟩,
      ⟨5, ([(Int.ofNat 3978000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨5, ([(Int.ofNat 4770000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12494999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 6974999999999)], [(Int.ofNat 2850000000000)])⟩,
      ⟨4, ([(Int.negSucc 6374999999999)], [(Int.ofNat 2790000000000)])⟩,
      ⟨4, ([(Int.negSucc 5396999999999)], [(Int.negSucc 3602999999999)])⟩,
      ⟨4, ([(Int.negSucc 4289999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 2894999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 2084999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨2, ([(Int.negSucc 1874999999999)], [(Int.ofNat 4665000000000)])⟩,
      ⟨8, ([(Int.negSucc 13619999999999)], [(Int.ofNat 4620000000000)])⟩,
      ⟨3, ([(Int.negSucc 8684999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨3, ([(Int.negSucc 5789999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 5249999999999)], [(Int.ofNat 8370000000000)])⟩,
      ⟨8, ([(Int.negSucc 9434999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4560000000000)])⟩,
      ⟨2, ([(Int.negSucc 5396999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 2954999999999)], [(Int.ofNat 5580000000000)])⟩],
    last := 2 }

end ConwaySoifer.Simplified.Certificates.Data
