import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_270000_280000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_270000_280000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 27) 100), hi := (mkRat (Int.ofNat 7) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.negSucc 1214999999999)], [(Int.ofNat 465000000000)])⟩,
      ⟨0, ([(Int.negSucc 1214999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 1004999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 809999999999)], [(Int.ofNat 1185000000000)])⟩,
      ⟨0, ([(Int.negSucc 464999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.negSucc 464999999999)], [(Int.ofNat 1215000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 1005000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 810000000000)])⟩,
      ⟨0, ([(Int.ofNat 465000000000)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 465000000000)])⟩,
      ⟨0, ([(Int.ofNat 5625000000000)], [(Int.negSucc 5354999999999)])⟩,
      ⟨0, ([(Int.ofNat 5760000000000)], [(Int.negSucc 5384999999999)])⟩,
      ⟨0, ([(Int.ofNat 5970000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨0, ([(Int.ofNat 6075000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨9, ([(Int.ofNat 7290000000000)], [(Int.negSucc 12464999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 10574999999999)])⟩,
      ⟨3, ([(Int.negSucc 2519999999999)], [(Int.ofNat 2520000000000)])⟩,
      ⟨5, ([(Int.ofNat 4374000000000)], [(Int.negSucc 8498999999999)])⟩,
      ⟨5, ([(Int.ofNat 5190000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨8, ([(Int.negSucc 12719999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 2430000000000)])⟩,
      ⟨4, ([(Int.negSucc 5144999999999)], [(Int.negSucc 3854999999999)])⟩,
      ⟨4, ([(Int.negSucc 4625999999999)], [(Int.ofNat 1875000000000)])⟩,
      ⟨4, ([(Int.negSucc 4139999999999)], [(Int.negSucc 359999999999)])⟩,
      ⟨2, ([(Int.negSucc 1748999999999)], [(Int.ofNat 4374000000000)])⟩,
      ⟨2, ([(Int.negSucc 374999999999)], [(Int.ofNat 4626000000000)])⟩,
      ⟨8, ([(Int.negSucc 13373999999999)], [(Int.ofNat 4374000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 6435000000000)])⟩,
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 4140000000000)])⟩,
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 6750000000000)])⟩,
      ⟨0, ([(Int.negSucc 1709999999999)], [(Int.negSucc 164999999999)])⟩,
      ⟨8, ([(Int.negSucc 9809999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4365000000000)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.ofNat 2430000000000)])⟩,
      ⟨0, ([(Int.negSucc 1139999999999)], [(Int.ofNat 1140000000000)])⟩,
      ⟨5, ([(Int.ofNat 3750000000000)], [(Int.negSucc 6179999999999)])⟩,
      ⟨5, ([(Int.ofNat 4374000000000)], [(Int.negSucc 6248999999999)])⟩,
      ⟨1, ([(Int.ofNat 6375000000000)], [(Int.negSucc 2729999999999)])⟩,
      ⟨4, ([(Int.negSucc 4004999999999)], [(Int.negSucc 4994999999999)])⟩,
      ⟨0, ([(Int.negSucc 2429999999999)], [(Int.negSucc 4874999999999)])⟩,
      ⟨0, ([(Int.ofNat 2430000000000)], [(Int.ofNat 0)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
