import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_130000_140000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_130000_140000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 13) 100), hi := (mkRat (Int.ofNat 7) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 540000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 360000000000)])⟩,
      ⟨0, ([(Int.ofNat 1170000000000)], [(Int.negSucc 1169999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 9734999999999)])⟩,
      ⟨5, ([(Int.ofNat 6840000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 5879999999999)], [(Int.negSucc 3119999999999)])⟩,
      ⟨0, ([(Int.ofNat 4365000000000)], [(Int.negSucc 5489999999999)])⟩,
      ⟨0, ([(Int.ofNat 4875000000000)], [(Int.negSucc 5264999999999)])⟩,
      ⟨0, ([(Int.ofNat 4875000000000)], [(Int.negSucc 5234999999999)])⟩,
      ⟨8, ([(Int.negSucc 14894999999999)], [(Int.ofNat 5895000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 6894000000000)])⟩,
      ⟨3, ([(Int.negSucc 6893999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨4, ([(Int.negSucc 5174999999999)], [(Int.negSucc 779999999999)])⟩,
      ⟨4, ([(Int.negSucc 3509999999999)], [(Int.negSucc 5114999999999)])⟩,
      ⟨4, ([(Int.negSucc 3359999999999)], [(Int.negSucc 5639999999999)])⟩,
      ⟨8, ([(Int.negSucc 15893999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 12359999999999)], [(Int.ofNat 3360000000000)])⟩,
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 4320000000000)])⟩,
      ⟨3, ([(Int.negSucc 4874999999999)], [(Int.ofNat 4095000000000)])⟩,
      ⟨5, ([(Int.negSucc 1169999999999)], [(Int.negSucc 7454999999999)])⟩,
      ⟨8, ([(Int.negSucc 14489999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8219999999999)], [(Int.ofNat 4095000000000)])⟩,
      ⟨4, ([(Int.negSucc 5174999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 3254999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 584999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨0, ([(Int.negSucc 359999999999)], [(Int.ofNat 735000000000)])⟩,
      ⟨0, ([(Int.ofNat 4005000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨0, ([(Int.ofNat 4875000000000)], [(Int.negSucc 6044999999999)])⟩,
      ⟨0, ([(Int.ofNat 5490000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨8, ([(Int.negSucc 14144999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3405000000000)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.ofNat 0)])⟩,
      ⟨3, ([(Int.negSucc 4709999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨2, ([(Int.negSucc 779999999999)], [(Int.ofNat 5955000000000)])⟩,
      ⟨8, ([(Int.negSucc 11759999999999)], [(Int.ofNat 8250000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3360000000000)])⟩,
      ⟨2, ([(Int.negSucc 5594999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 3915000000000)])⟩,
      ⟨2, ([(Int.negSucc 1169999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨2, ([(Int.negSucc 779999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨7, ([(Int.ofNat 5145000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 5490000000000)], [(Int.ofNat 2385000000000)])⟩,
      ⟨0, ([(Int.ofNat 7020000000000)], [(Int.negSucc 6644999999999)])⟩,
      ⟨3, ([(Int.negSucc 5954999999999)], [(Int.ofNat 7125000000000)])⟩,
      ⟨2, ([(Int.negSucc 5639999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.ofNat 1170000000000)])⟩,
      ⟨2, ([(Int.negSucc 5249999999999)], [(Int.ofNat 8610000000000)])⟩,
      ⟨3, ([(Int.negSucc 3539999999999)], [(Int.ofNat 3540000000000)])⟩,
      ⟨2, ([(Int.negSucc 1559999999999)], [(Int.ofNat 5310000000000)])⟩,
      ⟨0, ([(Int.negSucc 824999999999)], [(Int.ofNat 0)])⟩,
      ⟨1, ([(Int.ofNat 3510000000000)], [(Int.ofNat 3990000000000)])⟩,
      ⟨7, ([(Int.ofNat 3510000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 7680000000000)], [(Int.negSucc 4679999999999)])⟩,
      ⟨0, ([(Int.ofNat 3375000000000)], [(Int.ofNat 4680000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
