import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_110000_120000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_110000_120000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 11) 100), hi := (mkRat (Int.ofNat 3) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 468000000000)])⟩,
      ⟨0, ([(Int.ofNat 990000000000)], [(Int.negSucc 989999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 9599999999999)])⟩,
      ⟨5, ([(Int.ofNat 7125000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 6344999999999)], [(Int.negSucc 2654999999999)])⟩,
      ⟨0, ([(Int.ofNat 4500000000000)], [(Int.negSucc 5489999999999)])⟩,
      ⟨0, ([(Int.ofNat 5010000000000)], [(Int.negSucc 5999999999999)])⟩,
      ⟨0, ([(Int.ofNat 5250000000000)], [(Int.negSucc 5939999999999)])⟩,
      ⟨0, ([(Int.ofNat 5295000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨8, ([(Int.negSucc 15419999999999)], [(Int.ofNat 6420000000000)])⟩,
      ⟨3, ([(Int.negSucc 8339999999999)], [(Int.ofNat 7215000000000)])⟩,
      ⟨3, ([(Int.negSucc 7217999999999)], [(Int.ofNat 6750000000000)])⟩,
      ⟨4, ([(Int.negSucc 5189999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.negSucc 989999999999)])⟩,
      ⟨4, ([(Int.negSucc 2999999999999)], [(Int.negSucc 5999999999999)])⟩,
      ⟨8, ([(Int.negSucc 16217999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 12044999999999)], [(Int.ofNat 3045000000000)])⟩,
      ⟨3, ([(Int.negSucc 7919999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨3, ([(Int.negSucc 4859999999999)], [(Int.ofNat 3960000000000)])⟩,
      ⟨3, ([(Int.negSucc 4739999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨5, ([(Int.negSucc 989999999999)], [(Int.negSucc 7634999999999)])⟩,
      ⟨8, ([(Int.negSucc 13919999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8339999999999)], [(Int.ofNat 3465000000000)])⟩,
      ⟨4, ([(Int.negSucc 4739999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 764999999999)], [(Int.ofNat 5940000000000)])⟩,
      ⟨0, ([(Int.ofNat 4125000000000)], [(Int.negSucc 5114999999999)])⟩,
      ⟨0, ([(Int.ofNat 5385000000000)], [(Int.negSucc 6374999999999)])⟩,
      ⟨0, ([(Int.ofNat 6045000000000)], [(Int.negSucc 6374999999999)])⟩,
      ⟨8, ([(Int.negSucc 12044999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3000000000000)])⟩,
      ⟨2, ([(Int.negSucc 5279999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 4005000000000)])⟩,
      ⟨3, ([(Int.negSucc 4409999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 989999999999)], [(Int.ofNat 5490000000000)])⟩,
      ⟨8, ([(Int.negSucc 11459999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8339999999999)], [(Int.ofNat 3000000000000)])⟩,
      ⟨2, ([(Int.negSucc 5999999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 4919999999999)], [(Int.ofNat 7920000000000)])⟩,
      ⟨3, ([(Int.negSucc 4334999999999)], [(Int.ofNat 3960000000000)])⟩,
      ⟨3, ([(Int.negSucc 4124999999999)], [(Int.ofNat 3630000000000)])⟩,
      ⟨4, ([(Int.negSucc 3869999999999)], [(Int.ofNat 495000000000)])⟩,
      ⟨2, ([(Int.negSucc 989999999999)], [(Int.ofNat 4740000000000)])⟩,
      ⟨2, ([(Int.negSucc 899999999999)], [(Int.ofNat 4860000000000)])⟩,
      ⟨1, ([(Int.ofNat 4125000000000)], [(Int.ofNat 3390000000000)])⟩,
      ⟨0, ([(Int.ofNat 7218000000000)], [(Int.negSucc 6842999999999)])⟩,
      ⟨3, ([(Int.negSucc 8009999999999)], [(Int.ofNat 3000000000000)])⟩,
      ⟨3, ([(Int.negSucc 5009999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨4, ([(Int.negSucc 4739999999999)], [(Int.ofNat 990000000000)])⟩,
      ⟨2, ([(Int.negSucc 4514999999999)], [(Int.ofNat 7515000000000)])⟩,
      ⟨3, ([(Int.negSucc 3359999999999)], [(Int.ofNat 3360000000000)])⟩,
      ⟨2, ([(Int.negSucc 1079999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨0, ([(Int.negSucc 809999999999)], [(Int.ofNat 0)])⟩,
      ⟨1, ([(Int.ofNat 3000000000000)], [(Int.ofNat 3960000000000)])⟩,
      ⟨0, ([(Int.ofNat 7680000000000)], [(Int.negSucc 5429999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
