import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sext_120000_130000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sext_120000_130000 : CertData :=
  { case := Case.Sext,
    lo := (mkRat (Int.ofNat 3) 25), hi := (mkRat (Int.ofNat 13) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨0, ([(Int.ofNat 1080000000000)], [(Int.negSucc 1079999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 9659999999999)])⟩,
      ⟨5, ([(Int.ofNat 6990000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨4, ([(Int.negSucc 6119999999999)], [(Int.negSucc 2879999999999)])⟩,
      ⟨0, ([(Int.ofNat 4500000000000)], [(Int.negSucc 5579999999999)])⟩,
      ⟨0, ([(Int.ofNat 5085000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨0, ([(Int.ofNat 5175000000000)], [(Int.negSucc 5534999999999)])⟩,
      ⟨8, ([(Int.negSucc 15479999999999)], [(Int.ofNat 6750000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 7056000000000)])⟩,
      ⟨3, ([(Int.negSucc 7124999999999)], [(Int.ofNat 6585000000000)])⟩,
      ⟨4, ([(Int.negSucc 5009999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨4, ([(Int.negSucc 3239999999999)], [(Int.negSucc 5624999999999)])⟩,
      ⟨4, ([(Int.negSucc 3164999999999)], [(Int.negSucc 5834999999999)])⟩,
      ⟨8, ([(Int.negSucc 16139999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 12239999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨8, ([(Int.negSucc 12194999999999)], [(Int.ofNat 3195000000000)])⟩,
      ⟨3, ([(Int.negSucc 7919999999999)], [(Int.ofNat 3960000000000)])⟩,
      ⟨3, ([(Int.negSucc 5174999999999)], [(Int.ofNat 4095000000000)])⟩,
      ⟨3, ([(Int.negSucc 5174999999999)], [(Int.ofNat 4320000000000)])⟩,
      ⟨5, ([(Int.negSucc 1079999999999)], [(Int.negSucc 7499999999999)])⟩,
      ⟨8, ([(Int.negSucc 14624999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8279999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨4, ([(Int.negSucc 5174999999999)], [(Int.ofNat 0)])⟩,
      ⟨2, ([(Int.negSucc 3599999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨2, ([(Int.negSucc 749999999999)], [(Int.ofNat 6300000000000)])⟩,
      ⟨2, ([(Int.negSucc 674999999999)], [(Int.ofNat 6300000000000)])⟩,
      ⟨0, ([(Int.ofNat 4095000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨0, ([(Int.ofNat 5295000000000)], [(Int.negSucc 6374999999999)])⟩,
      ⟨0, ([(Int.ofNat 6000000000000)], [(Int.negSucc 6299999999999)])⟩,
      ⟨8, ([(Int.negSucc 14264999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3180000000000)])⟩,
      ⟨3, ([(Int.negSucc 7055999999999)], [(Int.ofNat 7875000000000)])⟩,
      ⟨3, ([(Int.negSucc 4679999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨2, ([(Int.negSucc 4334999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.negSucc 194999999999)])⟩,
      ⟨2, ([(Int.negSucc 749999999999)], [(Int.ofNat 5760000000000)])⟩,
      ⟨7, ([(Int.ofNat 5580000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 6000000000000)], [(Int.ofNat 1920000000000)])⟩,
      ⟨8, ([(Int.negSucc 11444999999999)], [(Int.ofNat 7125000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3165000000000)])⟩,
      ⟨2, ([(Int.negSucc 5819999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 4289999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨2, ([(Int.negSucc 1619999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨2, ([(Int.negSucc 929999999999)], [(Int.ofNat 4680000000000)])⟩,
      ⟨7, ([(Int.ofNat 4680000000000)], [(Int.ofNat 9000000000000)])⟩,
      ⟨1, ([(Int.ofNat 5175000000000)], [(Int.ofNat 2700000000000)])⟩,
      ⟨0, ([(Int.ofNat 7125000000000)], [(Int.negSucc 6839999999999)])⟩,
      ⟨2, ([(Int.negSucc 5834999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨3, ([(Int.negSucc 5249999999999)], [(Int.ofNat 6330000000000)])⟩,
      ⟨4, ([(Int.negSucc 5204999999999)], [(Int.ofNat 1080000000000)])⟩,
      ⟨0, ([(Int.negSucc 824999999999)], [(Int.ofNat 0)])⟩,
      ⟨1, ([(Int.ofNat 3195000000000)], [(Int.ofNat 4680000000000)])⟩,
      ⟨0, ([(Int.ofNat 7500000000000)], [(Int.negSucc 5339999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
