import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_190000_200000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_190000_200000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 19) 100), hi := (mkRat (Int.ofNat 1) 5), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 2894999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 944999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 944999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 6060000000000)])⟩,
      ⟨0, ([(Int.ofNat 435000000000)], [(Int.ofNat 6000000000000)])⟩,
      ⟨0, ([(Int.ofNat 570000000000)], [(Int.negSucc 944999999999)])⟩,
      ⟨0, ([(Int.ofNat 570000000000)], [(Int.ofNat 5805000000000)])⟩,
      ⟨0, ([(Int.ofNat 945000000000)], [(Int.negSucc 569999999999)])⟩,
      ⟨8, ([(Int.negSucc 12014999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8144999999999)], [(Int.ofNat 3825000000000)])⟩,
      ⟨4, ([(Int.negSucc 5249999999999)], [(Int.ofNat 1380000000000)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.ofNat 1005000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.ofNat 570000000000)])⟩,
      ⟨3, ([(Int.negSucc 3419999999999)], [(Int.ofNat 8250000000000)])⟩,
      ⟨8, ([(Int.negSucc 13679999999999)], [(Int.ofNat 4680000000000)])⟩,
      ⟨5, ([(Int.negSucc 3734999999999)], [(Int.negSucc 5264999999999)])⟩,
      ⟨5, ([(Int.negSucc 749999999999)], [(Int.negSucc 5129999999999)])⟩,
      ⟨5, ([(Int.negSucc 494999999999)], [(Int.negSucc 5129999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4953000000000)])⟩,
      ⟨4, ([(Int.negSucc 4274999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨6, ([(Int.ofNat 5329800000000)], [(Int.negSucc 5921999999999)])⟩,
      ⟨8, ([(Int.negSucc 11249999999999)], [(Int.ofNat 2250000000000)])⟩,
      ⟨3, ([(Int.negSucc 8459999999999)], [(Int.ofNat 6750000000000)])⟩,
      ⟨5, ([(Int.negSucc 5129999999999)], [(Int.negSucc 3869999999999)])⟩,
      ⟨5, ([(Int.negSucc 1004999999999)], [(Int.negSucc 3869999999999)])⟩,
      ⟨5, ([(Int.negSucc 569999999999)], [(Int.negSucc 3929999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 15179999999999)])⟩,
      ⟨4, ([(Int.negSucc 4664999999999)], [(Int.negSucc 1709999999999)])⟩,
      ⟨0, ([(Int.negSucc 1709999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨9, ([(Int.ofNat 3870000000000)], [(Int.negSucc 12869999999999)])⟩,
      ⟨6, ([(Int.ofNat 3870000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨6, ([(Int.ofNat 3870000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨6, ([(Int.ofNat 3930000000000)], [(Int.negSucc 4499999999999)])⟩,
      ⟨0, ([(Int.negSucc 1229999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 854999999999)], [(Int.negSucc 269999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5129999999999)])⟩,
      ⟨0, ([(Int.ofNat 2715000000000)], [(Int.ofNat 4125000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
