import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_130000_140000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_130000_140000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 13) 100), hi := (mkRat (Int.ofNat 7) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨4, ([(Int.negSucc 8039999999999)], [(Int.ofNat 0)])⟩,
      ⟨3, ([(Int.negSucc 2159999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 735000000000)], [(Int.negSucc 359999999999)])⟩,
      ⟨8, ([(Int.negSucc 11174999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 5490000000000)])⟩,
      ⟨0, ([(Int.negSucc 389999999999)], [(Int.ofNat 5265000000000)])⟩,
      ⟨0, ([(Int.negSucc 359999999999)], [(Int.ofNat 5235000000000)])⟩,
      ⟨4, ([(Int.negSucc 7829999999999)], [(Int.ofNat 3000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5954999999999)], [(Int.ofNat 780000000000)])⟩,
      ⟨8, ([(Int.negSucc 15644999999999)], [(Int.ofNat 6645000000000)])⟩,
      ⟨3, ([(Int.negSucc 8414999999999)], [(Int.ofNat 7573500000000)])⟩,
      ⟨5, ([(Int.negSucc 2114999999999)], [(Int.negSucc 6884999999999)])⟩,
      ⟨5, ([(Int.negSucc 644999999999)], [(Int.negSucc 6374999999999)])⟩,
      ⟨5, ([(Int.negSucc 518999999999)], [(Int.negSucc 6374999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5640000000000)])⟩,
      ⟨4, ([(Int.negSucc 5834999999999)], [(Int.ofNat 585000000000)])⟩,
      ⟨0, ([(Int.negSucc 1169999999999)], [(Int.ofNat 5670000000000)])⟩,
      ⟨0, ([(Int.negSucc 584999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.negSucc 239999999999)], [(Int.ofNat 5490000000000)])⟩,
      ⟨6, ([(Int.ofNat 6735000000000)], [(Int.negSucc 7124999999999)])⟩,
      ⟨6, ([(Int.ofNat 6750000000000)], [(Int.negSucc 7109999999999)])⟩,
      ⟨6, ([(Int.ofNat 7020000000000)], [(Int.negSucc 8144999999999)])⟩,
      ⟨8, ([(Int.negSucc 14894999999999)], [(Int.ofNat 5895000000000)])⟩,
      ⟨3, ([(Int.negSucc 8624999999999)], [(Int.ofNat 7455000000000)])⟩,
      ⟨4, ([(Int.negSucc 5489999999999)], [(Int.ofNat 615000000000)])⟩,
      ⟨5, ([(Int.negSucc 5459999999999)], [(Int.negSucc 3539999999999)])⟩,
      ⟨5, ([(Int.negSucc 779999999999)], [(Int.negSucc 4094999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 734999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 16109999999999)])⟩,
      ⟨5, ([(Int.negSucc 5624999999999)], [(Int.negSucc 3374999999999)])⟩,
      ⟨4, ([(Int.negSucc 5174999999999)], [(Int.negSucc 1169999999999)])⟩,
      ⟨4, ([(Int.negSucc 4394999999999)], [(Int.negSucc 779999999999)])⟩,
      ⟨0, ([(Int.negSucc 1169999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨0, ([(Int.negSucc 1169999999999)], [(Int.ofNat 6045000000000)])⟩,
      ⟨0, ([(Int.negSucc 359999999999)], [(Int.ofNat 5985000000000)])⟩,
      ⟨9, ([(Int.ofNat 3555000000000)], [(Int.negSucc 12554999999999)])⟩,
      ⟨6, ([(Int.ofNat 3570000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨6, ([(Int.ofNat 4005000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨6, ([(Int.ofNat 4095000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨5, ([(Int.negSucc 5639999999999)], [(Int.negSucc 3359999999999)])⟩,
      ⟨0, ([(Int.negSucc 779999999999)], [(Int.ofNat 0)])⟩,
      ⟨5, ([(Int.negSucc 389999999999)], [(Int.negSucc 3734999999999)])⟩,
      ⟨9, ([(Int.ofNat 3375000000000)], [(Int.negSucc 12374999999999)])⟩,
      ⟨6, ([(Int.ofNat 3375000000000)], [(Int.negSucc 8414999999999)])⟩,
      ⟨1, ([(Int.ofNat 7440000000000)], [(Int.negSucc 2624999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 4619999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 6645000000000)])⟩,
      ⟨0, ([(Int.ofNat 3000000000000)], [(Int.ofNat 4440000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
