import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_240000_250000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_240000_250000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 6) 25), hi := (mkRat (Int.ofNat 1) 4), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 3494999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 405000000000)])⟩,
      ⟨0, ([(Int.ofNat 360000000000)], [(Int.ofNat 5640000000000)])⟩,
      ⟨0, ([(Int.ofNat 405000000000)], [(Int.negSucc 1124999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 5400000000000)])⟩,
      ⟨0, ([(Int.ofNat 930000000000)], [(Int.negSucc 929999999999)])⟩,
      ⟨0, ([(Int.ofNat 1125000000000)], [(Int.negSucc 719999999999)])⟩,
      ⟨8, ([(Int.negSucc 12512999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8279999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨4, ([(Int.negSucc 4844999999999)], [(Int.ofNat 720000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.ofNat 360000000000)])⟩,
      ⟨3, ([(Int.negSucc 3599999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨8, ([(Int.negSucc 13889999999999)], [(Int.ofNat 4890000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 6480000000000)])⟩,
      ⟨5, ([(Int.negSucc 374999999999)], [(Int.negSucc 4736999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4215000000000)])⟩,
      ⟨4, ([(Int.negSucc 4319999999999)], [(Int.ofNat 195000000000)])⟩,
      ⟨5, ([(Int.negSucc 3329999999999)], [(Int.negSucc 5669999999999)])⟩,
      ⟨0, ([(Int.ofNat 225000000000)], [(Int.ofNat 5400000000000)])⟩,
      ⟨9, ([(Int.ofNat 4860000000000)], [(Int.negSucc 13859999999999)])⟩,
      ⟨9, ([(Int.ofNat 5400000000000)], [(Int.negSucc 13649999999999)])⟩,
      ⟨6, ([(Int.ofNat 5625000000000)], [(Int.negSucc 8279999999999)])⟩,
      ⟨5, ([(Int.negSucc 4214999999999)], [(Int.negSucc 4784999999999)])⟩,
      ⟨5, ([(Int.negSucc 4124999999999)], [(Int.negSucc 4154999999999)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2384999999999)])⟩,
      ⟨6, ([(Int.ofNat 4890000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨9, ([(Int.ofNat 7875000000000)], [(Int.negSucc 14354999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 14759999999999)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 2159999999999)])⟩,
      ⟨4, ([(Int.negSucc 2519999999999)], [(Int.negSucc 1604999999999)])⟩,
      ⟨6, ([(Int.ofNat 2385000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨6, ([(Int.ofNat 2520000000000)], [(Int.negSucc 4124999999999)])⟩,
      ⟨6, ([(Int.ofNat 2625000000000)], [(Int.negSucc 6512999999999)])⟩,
      ⟨6, ([(Int.ofNat 3240000000000)], [(Int.negSucc 8489999999999)])⟩,
      ⟨9, ([(Int.ofNat 3375000000000)], [(Int.negSucc 12374999999999)])⟩,
      ⟨6, ([(Int.ofNat 3375000000000)], [(Int.negSucc 8774999999999)])⟩,
      ⟨5, ([(Int.negSucc 4829999999999)], [(Int.negSucc 4169999999999)])⟩,
      ⟨0, ([(Int.negSucc 1814999999999)], [(Int.ofNat 0)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 6614999999999)])⟩,
      ⟨0, ([(Int.ofNat 3375000000000)], [(Int.ofNat 3240000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
