import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_120000_130000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_120000_130000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 3) 25), hi := (mkRat (Int.ofNat 13) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨4, ([(Int.negSucc 8084999999999)], [(Int.ofNat 0)])⟩,
      ⟨3, ([(Int.negSucc 2009999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 11069999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 5580000000000)])⟩,
      ⟨0, ([(Int.negSucc 539999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.negSucc 359999999999)], [(Int.ofNat 5535000000000)])⟩,
      ⟨4, ([(Int.negSucc 7874999999999)], [(Int.ofNat 3240000000000)])⟩,
      ⟨4, ([(Int.negSucc 5759999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨8, ([(Int.negSucc 15299999999999)], [(Int.ofNat 6300000000000)])⟩,
      ⟨3, ([(Int.negSucc 8639999999999)], [(Int.ofNat 7740000000000)])⟩,
      ⟨5, ([(Int.negSucc 2429999999999)], [(Int.negSucc 6569999999999)])⟩,
      ⟨5, ([(Int.negSucc 539999999999)], [(Int.negSucc 6209999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5835000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.ofNat 540000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 5760000000000)])⟩,
      ⟨9, ([(Int.ofNat 6300000000000)], [(Int.negSucc 15299999999999)])⟩,
      ⟨6, ([(Int.ofNat 6585000000000)], [(Int.negSucc 7124999999999)])⟩,
      ⟨6, ([(Int.ofNat 6840000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨8, ([(Int.negSucc 13319999999999)], [(Int.ofNat 4320000000000)])⟩,
      ⟨3, ([(Int.negSucc 8579999999999)], [(Int.ofNat 7500000000000)])⟩,
      ⟨5, ([(Int.negSucc 5768999999999)], [(Int.negSucc 3230999999999)])⟩,
      ⟨4, ([(Int.negSucc 5594999999999)], [(Int.ofNat 720000000000)])⟩,
      ⟨5, ([(Int.negSucc 1079999999999)], [(Int.negSucc 4094999999999)])⟩,
      ⟨5, ([(Int.negSucc 854999999999)], [(Int.negSucc 4319999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 16139999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 1289999999999)])⟩,
      ⟨5, ([(Int.negSucc 5834999999999)], [(Int.negSucc 3164999999999)])⟩,
      ⟨4, ([(Int.negSucc 5174999999999)], [(Int.negSucc 1079999999999)])⟩,
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨0, ([(Int.ofNat 285000000000)], [(Int.ofNat 6840000000000)])⟩,
      ⟨9, ([(Int.ofNat 3240000000000)], [(Int.negSucc 12239999999999)])⟩,
      ⟨6, ([(Int.ofNat 3240000000000)], [(Int.negSucc 8414999999999)])⟩,
      ⟨6, ([(Int.ofNat 4095000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 30000000000)])⟩,
      ⟨1, ([(Int.ofNat 8250000000000)], [(Int.negSucc 4319999999999)])⟩,
      ⟨0, ([(Int.ofNat 2250000000000)], [(Int.ofNat 5310000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
