import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_140000_150000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_140000_150000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 7) 50), hi := (mkRat (Int.ofNat 3) 20), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨4, ([(Int.negSucc 7964999999999)], [(Int.ofNat 0)])⟩,
      ⟨3, ([(Int.negSucc 2267999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 330000000000)])⟩,
      ⟨0, ([(Int.negSucc 419999999999)], [(Int.negSucc 329999999999)])⟩,
      ⟨0, ([(Int.ofNat 330000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 420000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.negSucc 419999999999)])⟩,
      ⟨8, ([(Int.negSucc 11519999999999)], [(Int.ofNat 8895000000000)])⟩,
      ⟨8, ([(Int.negSucc 11267999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1094999999999)], [(Int.ofNat 5220000000000)])⟩,
      ⟨0, ([(Int.negSucc 839999999999)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 5040000000000)])⟩,
      ⟨4, ([(Int.negSucc 7874999999999)], [(Int.ofNat 2655000000000)])⟩,
      ⟨4, ([(Int.negSucc 6374999999999)], [(Int.ofNat 840000000000)])⟩,
      ⟨8, ([(Int.negSucc 15659999999999)], [(Int.ofNat 6660000000000)])⟩,
      ⟨3, ([(Int.negSucc 8624999999999)], [(Int.ofNat 7560000000000)])⟩,
      ⟨3, ([(Int.negSucc 8369999999999)], [(Int.ofNat 7470000000000)])⟩,
      ⟨5, ([(Int.negSucc 1709999999999)], [(Int.negSucc 7289999999999)])⟩,
      ⟨5, ([(Int.negSucc 419999999999)], [(Int.negSucc 6329999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5505000000000)])⟩,
      ⟨4, ([(Int.negSucc 8624999999999)], [(Int.ofNat 5040000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 420000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 5415000000000)])⟩,
      ⟨0, ([(Int.negSucc 209999999999)], [(Int.ofNat 5250000000000)])⟩,
      ⟨6, ([(Int.ofNat 6705000000000)], [(Int.negSucc 7124999999999)])⟩,
      ⟨6, ([(Int.ofNat 6735000000000)], [(Int.negSucc 7109999999999)])⟩,
      ⟨8, ([(Int.negSucc 15059999999999)], [(Int.ofNat 6060000000000)])⟩,
      ⟨3, ([(Int.negSucc 8624999999999)], [(Int.ofNat 7365000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.ofNat 585000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.ofNat 630000000000)])⟩,
      ⟨5, ([(Int.negSucc 5114999999999)], [(Int.negSucc 3884999999999)])⟩,
      ⟨5, ([(Int.negSucc 749999999999)], [(Int.negSucc 4289999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 16109999999999)])⟩,
      ⟨5, ([(Int.negSucc 5444999999999)], [(Int.negSucc 3554999999999)])⟩,
      ⟨4, ([(Int.negSucc 5114999999999)], [(Int.negSucc 1259999999999)])⟩,
      ⟨4, ([(Int.negSucc 4664999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 1259999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨0, ([(Int.negSucc 1259999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨0, ([(Int.negSucc 794999999999)], [(Int.ofNat 420000000000)])⟩,
      ⟨0, ([(Int.ofNat 270000000000)], [(Int.ofNat 6480000000000)])⟩,
      ⟨9, ([(Int.ofNat 3915000000000)], [(Int.negSucc 12914999999999)])⟩,
      ⟨6, ([(Int.ofNat 3960000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨6, ([(Int.ofNat 4290000000000)], [(Int.negSucc 5039999999999)])⟩,
      ⟨5, ([(Int.negSucc 5504999999999)], [(Int.negSucc 3494999999999)])⟩,
      ⟨3, ([(Int.negSucc 3374999999999)], [(Int.ofNat 8370000000000)])⟩,
      ⟨4, ([(Int.negSucc 3149999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 809999999999)], [(Int.ofNat 0)])⟩,
      ⟨5, ([(Int.negSucc 209999999999)], [(Int.negSucc 3749999999999)])⟩,
      ⟨6, ([(Int.ofNat 3660000000000)], [(Int.negSucc 8159999999999)])⟩,
      ⟨9, ([(Int.ofNat 3705000000000)], [(Int.negSucc 12704999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 14204999999999)])⟩,
      ⟨8, ([(Int.negSucc 10619999999999)], [(Int.ofNat 1620000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5535000000000)])⟩,
      ⟨5, ([(Int.negSucc 5999999999999)], [(Int.negSucc 2999999999999)])⟩,
      ⟨5, ([(Int.negSucc 3959999999999)], [(Int.negSucc 2789999999999)])⟩,
      ⟨1, ([(Int.ofNat 3000000000000)], [(Int.ofNat 4560000000000)])⟩,
      ⟨6, ([(Int.ofNat 3495000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨6, ([(Int.ofNat 3495000000000)], [(Int.negSucc 8369999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 4319999999999)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
