import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_210000_220000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_210000_220000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 21) 100), hi := (mkRat (Int.ofNat 11) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 3134999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1004999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 330000000000)], [(Int.ofNat 5670000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 5790000000000)])⟩,
      ⟨0, ([(Int.ofNat 630000000000)], [(Int.negSucc 1004999999999)])⟩,
      ⟨0, ([(Int.ofNat 705000000000)], [(Int.ofNat 5670000000000)])⟩,
      ⟨0, ([(Int.ofNat 1005000000000)], [(Int.negSucc 629999999999)])⟩,
      ⟨8, ([(Int.negSucc 12224999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8099999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨4, ([(Int.negSucc 8054999999999)], [(Int.ofNat 3423375000000)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.ofNat 945000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.ofNat 630000000000)])⟩,
      ⟨3, ([(Int.negSucc 3401999999999)], [(Int.ofNat 8652000000000)])⟩,
      ⟨8, ([(Int.negSucc 13919999999999)], [(Int.ofNat 4920000000000)])⟩,
      ⟨5, ([(Int.negSucc 3269999999999)], [(Int.negSucc 5729999999999)])⟩,
      ⟨5, ([(Int.negSucc 494999999999)], [(Int.negSucc 5174999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4530000000000)])⟩,
      ⟨4, ([(Int.negSucc 6554999999999)], [(Int.negSucc 1499999999999)])⟩,
      ⟨4, ([(Int.negSucc 4274999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨9, ([(Int.ofNat 5220000000000)], [(Int.negSucc 14219999999999)])⟩,
      ⟨6, ([(Int.ofNat 5598000000000)], [(Int.negSucc 5999999999999)])⟩,
      ⟨8, ([(Int.negSucc 11474999999999)], [(Int.ofNat 2475000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 6480000000000)])⟩,
      ⟨5, ([(Int.negSucc 5054999999999)], [(Int.negSucc 3944999999999)])⟩,
      ⟨5, ([(Int.negSucc 4724999999999)], [(Int.negSucc 3899999999999)])⟩,
      ⟨5, ([(Int.negSucc 2249999999999)], [(Int.negSucc 3914999999999)])⟩,
      ⟨5, ([(Int.negSucc 749999999999)], [(Int.negSucc 3974999999999)])⟩,
      ⟨5, ([(Int.negSucc 374999999999)], [(Int.negSucc 4349999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 15059999999999)])⟩,
      ⟨0, ([(Int.negSucc 1544999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨6, ([(Int.ofNat 3900000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨6, ([(Int.ofNat 4125000000000)], [(Int.negSucc 4724999999999)])⟩,
      ⟨4, ([(Int.negSucc 3374999999999)], [(Int.ofNat 45000000000)])⟩,
      ⟨5, ([(Int.ofNat 1650000000000)], [(Int.negSucc 6374999999999)])⟩,
      ⟨1, ([(Int.ofNat 8850000000000)], [(Int.negSucc 4724999999999)])⟩,
      ⟨5, ([(Int.negSucc 5279999999999)], [(Int.negSucc 3719999999999)])⟩,
      ⟨4, ([(Int.negSucc 2984999999999)], [(Int.negSucc 1889999999999)])⟩,
      ⟨0, ([(Int.ofNat 2250000000000)], [(Int.ofNat 4725000000000)])⟩,
      ⟨0, ([(Int.negSucc 1889999999999)], [(Int.ofNat 0)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
