import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_300000_310000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_300000_310000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 3) 10), hi := (mkRat (Int.ofNat 31) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 8550000000000)])⟩,
      ⟨3, ([(Int.negSucc 4124999999999)], [(Int.ofNat 8985000000000)])⟩,
      ⟨3, ([(Int.negSucc 4124999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 600000000000)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 599999999999)])⟩,
      ⟨0, ([(Int.negSucc 599999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 225000000000)], [(Int.ofNat 5175000000000)])⟩,
      ⟨0, ([(Int.ofNat 600000000000)], [(Int.negSucc 1349999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.negSucc 1349999999999)])⟩,
      ⟨0, ([(Int.ofNat 1050000000000)], [(Int.ofNat 4950000000000)])⟩,
      ⟨0, ([(Int.ofNat 1350000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨8, ([(Int.negSucc 13124999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8249999999999)], [(Int.ofNat 2700000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2609999999999)])⟩,
      ⟨4, ([(Int.negSucc 6149999999999)], [(Int.negSucc 2849999999999)])⟩,
      ⟨4, ([(Int.negSucc 4049999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 3674999999999)], [(Int.negSucc 2699999999999)])⟩,
      ⟨4, ([(Int.negSucc 2624999999999)], [(Int.negSucc 1799999999999)])⟩,
      ⟨6, ([(Int.ofNat 2625000000000)], [(Int.negSucc 4424999999999)])⟩,
      ⟨9, ([(Int.ofNat 3525000000000)], [(Int.negSucc 12524999999999)])⟩,
      ⟨6, ([(Int.ofNat 3750000000000)], [(Int.negSucc 4649999999999)])⟩,
      ⟨8, ([(Int.negSucc 10724999999999)], [(Int.ofNat 1725000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 6150000000000)])⟩,
      ⟨5, ([(Int.negSucc 3764999999999)], [(Int.negSucc 5234999999999)])⟩,
      ⟨0, ([(Int.ofNat 150000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨5, ([(Int.ofNat 2925000000000)], [(Int.negSucc 7874999999999)])⟩,
      ⟨5, ([(Int.ofNat 3000000000000)], [(Int.negSucc 8099999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3450000000000)])⟩,
      ⟨4, ([(Int.negSucc 5024999999999)], [(Int.negSucc 3974999999999)])⟩,
      ⟨4, ([(Int.negSucc 3599999999999)], [(Int.negSucc 3599999999999)])⟩,
      ⟨4, ([(Int.negSucc 3149999999999)], [(Int.negSucc 3149999999999)])⟩,
      ⟨4, ([(Int.negSucc 1874999999999)], [(Int.negSucc 1724999999999)])⟩,
      ⟨8, ([(Int.negSucc 9599999999999)], [(Int.ofNat 600000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4575000000000)])⟩,
      ⟨3, ([(Int.negSucc 6374999999999)], [(Int.ofNat 2235000000000)])⟩],
    last := 3 }

end ConwaySoifer.Simplified.Certificates.Data
