import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_250000_260000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_250000_260000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 1) 4), hi := (mkRat (Int.ofNat 13) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 3674999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1124999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 1125000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨8, ([(Int.negSucc 13049999999999)], [(Int.ofNat 7425000000000)])⟩,
      ⟨8, ([(Int.negSucc 12674999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8249999999999)], [(Int.ofNat 3075000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨4, ([(Int.negSucc 5174999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨4, ([(Int.negSucc 4949999999999)], [(Int.ofNat 495000000000)])⟩,
      ⟨3, ([(Int.negSucc 3674999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨8, ([(Int.negSucc 14624999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨8, ([(Int.negSucc 11249999999999)], [(Int.ofNat 7500000000000)])⟩,
      ⟨5, ([(Int.negSucc 299999999999)], [(Int.negSucc 4949999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4050000000000)])⟩,
      ⟨5, ([(Int.negSucc 3074999999999)], [(Int.negSucc 5924999999999)])⟩,
      ⟨6, ([(Int.ofNat 5250000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨5, ([(Int.negSucc 3824999999999)], [(Int.negSucc 5174999999999)])⟩,
      ⟨5, ([(Int.negSucc 374999999999)], [(Int.negSucc 4574999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 14849999999999)])⟩,
      ⟨9, ([(Int.ofNat 4875000000000)], [(Int.negSucc 13874999999999)])⟩,
      ⟨6, ([(Int.ofNat 4950000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨6, ([(Int.ofNat 5175000000000)], [(Int.negSucc 8549999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3074999999999)])⟩,
      ⟨0, ([(Int.ofNat 1125000000000)], [(Int.ofNat 5175000000000)])⟩,
      ⟨0, ([(Int.ofNat 1425000000000)], [(Int.ofNat 4950000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.ofNat 450000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2549999999999)])⟩,
      ⟨5, ([(Int.negSucc 4049999999999)], [(Int.negSucc 4949999999999)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 2249999999999)])⟩,
      ⟨4, ([(Int.negSucc 3599999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 2249999999999)], [(Int.negSucc 1499999999999)])⟩,
      ⟨6, ([(Int.ofNat 2587500000000)], [(Int.negSucc 4499999999999)])⟩,
      ⟨6, ([(Int.ofNat 3750000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨9, ([(Int.ofNat 4050000000000)], [(Int.negSucc 13049999999999)])⟩,
      ⟨6, ([(Int.ofNat 4125000000000)], [(Int.negSucc 4499999999999)])⟩,
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨5, ([(Int.negSucc 4874999999999)], [(Int.negSucc 4124999999999)])⟩,
      ⟨0, ([(Int.negSucc 1799999999999)], [(Int.ofNat 0)])⟩,
      ⟨5, ([(Int.ofNat 1875000000000)], [(Int.negSucc 6374999999999)])⟩,
      ⟨6, ([(Int.ofNat 3000000000000)], [(Int.negSucc 7499999999999)])⟩,
      ⟨6, ([(Int.ofNat 3375000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨1, ([(Int.ofNat 7125000000000)], [(Int.negSucc 4499999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 3750000000000)])⟩,
      ⟨0, ([(Int.ofNat 225000000000)], [(Int.negSucc 1124999999999)])⟩,
      ⟨0, ([(Int.ofNat 3375000000000)], [(Int.ofNat 3000000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
