import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_180000_190000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_180000_190000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 9) 50), hi := (mkRat (Int.ofNat 19) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 2915999999999)], [(Int.ofNat 8916000000000)])⟩,
      ⟨3, ([(Int.negSucc 2789999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 914999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 539999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 914999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 6105000000000)])⟩,
      ⟨0, ([(Int.ofNat 540000000000)], [(Int.negSucc 914999999999)])⟩,
      ⟨0, ([(Int.ofNat 570000000000)], [(Int.ofNat 6000000000000)])⟩,
      ⟨0, ([(Int.ofNat 915000000000)], [(Int.negSucc 539999999999)])⟩,
      ⟨8, ([(Int.negSucc 11864999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 7919999999999)], [(Int.ofNat 3420000000000)])⟩,
      ⟨4, ([(Int.negSucc 4859999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨4, ([(Int.negSucc 4289999999999)], [(Int.ofNat 540000000000)])⟩,
      ⟨3, ([(Int.negSucc 3239999999999)], [(Int.ofNat 8115000000000)])⟩,
      ⟨8, ([(Int.negSucc 13709999999999)], [(Int.ofNat 4710000000000)])⟩,
      ⟨4, ([(Int.negSucc 8174999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨5, ([(Int.negSucc 3329999999999)], [(Int.negSucc 5669999999999)])⟩,
      ⟨5, ([(Int.negSucc 509999999999)], [(Int.negSucc 5249999999999)])⟩,
      ⟨8, ([(Int.negSucc 13334999999999)], [(Int.ofNat 4335000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5184000000000)])⟩,
      ⟨4, ([(Int.negSucc 4139999999999)], [(Int.ofNat 414000000000)])⟩,
      ⟨5, ([(Int.negSucc 4079999999999)], [(Int.negSucc 4919999999999)])⟩,
      ⟨6, ([(Int.ofNat 5460000000000)], [(Int.negSucc 5999999999999)])⟩,
      ⟨8, ([(Int.negSucc 11159999999999)], [(Int.ofNat 2160000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 6630000000000)])⟩,
      ⟨5, ([(Int.negSucc 5249999999999)], [(Int.negSucc 3749999999999)])⟩,
      ⟨5, ([(Int.negSucc 4139999999999)], [(Int.negSucc 3734999999999)])⟩,
      ⟨5, ([(Int.negSucc 539999999999)], [(Int.negSucc 3749999999999)])⟩,
      ⟨9, ([(Int.ofNat 4710000000000)], [(Int.negSucc 12959999999999)])⟩,
      ⟨6, ([(Int.ofNat 5010000000000)], [(Int.negSucc 5759999999999)])⟩,
      ⟨6, ([(Int.ofNat 5085000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨9, ([(Int.ofNat 8625000000000)], [(Int.negSucc 15104999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 15344999999999)])⟩,
      ⟨4, ([(Int.negSucc 3239999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.negSucc 1619999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨5, ([(Int.negSucc 413999999999)], [(Int.negSucc 3725999999999)])⟩,
      ⟨9, ([(Int.ofNat 3735000000000)], [(Int.negSucc 12734999999999)])⟩,
      ⟨6, ([(Int.ofNat 3735000000000)], [(Int.negSucc 7874999999999)])⟩,
      ⟨6, ([(Int.ofNat 3750000000000)], [(Int.negSucc 8609999999999)])⟩,
      ⟨6, ([(Int.ofNat 3750000000000)], [(Int.negSucc 4289999999999)])⟩,
      ⟨6, ([(Int.ofNat 3765000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 2369999999999)])⟩,
      ⟨5, ([(Int.negSucc 5333999999999)], [(Int.negSucc 3665999999999)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.negSucc 1619999999999)])⟩,
      ⟨0, ([(Int.negSucc 1184999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 809999999999)], [(Int.negSucc 314999999999)])⟩,
      ⟨0, ([(Int.ofNat 990000000000)], [(Int.ofNat 5760000000000)])⟩,
      ⟨1, ([(Int.ofNat 4845000000000)], [(Int.negSucc 719999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5249999999999)])⟩,
      ⟨0, ([(Int.ofNat 2625000000000)], [(Int.ofNat 3855000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
