import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_330000_340000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_330000_340000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 33) 100), hi := (mkRat (Int.ofNat 17) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 8460000000000)])⟩,
      ⟨3, ([(Int.negSucc 4454999999999)], [(Int.ofNat 8580000000000)])⟩,
      ⟨3, ([(Int.negSucc 4454999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1484999999999)], [(Int.ofNat 735000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 1124999999999)])⟩,
      ⟨0, ([(Int.ofNat 210000000000)], [(Int.ofNat 5040000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 4971000000000)])⟩,
      ⟨0, ([(Int.ofNat 735000000000)], [(Int.negSucc 1484999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 4596000000000)])⟩,
      ⟨0, ([(Int.ofNat 1485000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨8, ([(Int.negSucc 13454999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5345999999999)], [(Int.ofNat 471000000000)])⟩,
      ⟨4, ([(Int.negSucc 5039999999999)], [(Int.ofNat 165000000000)])⟩,
      ⟨3, ([(Int.negSucc 4454999999999)], [(Int.ofNat 8205000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2759999999999)])⟩,
      ⟨8, ([(Int.negSucc 14174999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨4, ([(Int.negSucc 8594999999999)], [(Int.ofNat 2970000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.negSucc 3374999999999)])⟩,
      ⟨4, ([(Int.negSucc 4739999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 3959999999999)], [(Int.negSucc 3164999999999)])⟩,
      ⟨4, ([(Int.negSucc 2789999999999)], [(Int.negSucc 2249999999999)])⟩,
      ⟨4, ([(Int.negSucc 2624999999999)], [(Int.negSucc 1979999999999)])⟩,
      ⟨6, ([(Int.ofNat 2790000000000)], [(Int.negSucc 5039999999999)])⟩,
      ⟨6, ([(Int.ofNat 2880000000000)], [(Int.negSucc 4754999999999)])⟩,
      ⟨9, ([(Int.ofNat 3285000000000)], [(Int.negSucc 12284999999999)])⟩,
      ⟨8, ([(Int.negSucc 10709999999999)], [(Int.ofNat 1710000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨3, ([(Int.negSucc 7844999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨5, ([(Int.negSucc 4109999999999)], [(Int.negSucc 4889999999999)])⟩,
      ⟨0, ([(Int.negSucc 1574999999999)], [(Int.ofNat 450000000000)])⟩,
      ⟨0, ([(Int.ofNat 90000000000)], [(Int.ofNat 5160000000000)])⟩,
      ⟨5, ([(Int.ofNat 3375000000000)], [(Int.negSucc 8720999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3405000000000)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 3959999999999)])⟩,
      ⟨4, ([(Int.negSucc 2969999999999)], [(Int.negSucc 2999999999999)])⟩,
      ⟨0, ([(Int.negSucc 2639999999999)], [(Int.ofNat 4125000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2639999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.negSucc 1574999999999)])⟩,
      ⟨0, ([(Int.negSucc 3419999999999)], [(Int.ofNat 0)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
