import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_260000_270000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_260000_270000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 13) 50), hi := (mkRat (Int.ofNat 27) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 3749999999999)], [(Int.ofNat 8790000000000)])⟩,
      ⟨3, ([(Int.negSucc 3689999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1169999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 240000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1169999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 5475000000000)])⟩,
      ⟨0, ([(Int.ofNat 780000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 795000000000)], [(Int.negSucc 1169999999999)])⟩,
      ⟨0, ([(Int.ofNat 1170000000000)], [(Int.negSucc 794999999999)])⟩,
      ⟨0, ([(Int.ofNat 1170000000000)], [(Int.negSucc 374999999999)])⟩,
      ⟨8, ([(Int.negSucc 12734999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8369999999999)], [(Int.ofNat 3120000000000)])⟩,
      ⟨4, ([(Int.negSucc 8249999999999)], [(Int.ofNat 3150000000000)])⟩,
      ⟨4, ([(Int.negSucc 4586999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨3, ([(Int.negSucc 3836999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2504999999999)])⟩,
      ⟨4, ([(Int.negSucc 4154999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 3659999999999)], [(Int.negSucc 2339999999999)])⟩,
      ⟨5, ([(Int.negSucc 3089999999999)], [(Int.negSucc 5909999999999)])⟩,
      ⟨4, ([(Int.negSucc 2804999999999)], [(Int.negSucc 1874999999999)])⟩,
      ⟨6, ([(Int.ofNat 2625000000000)], [(Int.negSucc 4319999999999)])⟩,
      ⟨6, ([(Int.ofNat 4305000000000)], [(Int.negSucc 4679999999999)])⟩,
      ⟨8, ([(Int.negSucc 10844999999999)], [(Int.ofNat 1845000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3990000000000)])⟩,
      ⟨5, ([(Int.negSucc 4589999999999)], [(Int.negSucc 4409999999999)])⟩,
      ⟨0, ([(Int.negSucc 1559999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 809999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨5, ([(Int.ofNat 2160000000000)], [(Int.negSucc 6659999999999)])⟩,
      ⟨5, ([(Int.ofNat 2250000000000)], [(Int.negSucc 6929999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 14414999999999)])⟩,
      ⟨3, ([(Int.negSucc 8099999999999)], [(Int.ofNat 6120000000000)])⟩,
      ⟨5, ([(Int.negSucc 4679999999999)], [(Int.negSucc 4319999999999)])⟩,
      ⟨4, ([(Int.negSucc 2534999999999)], [(Int.negSucc 2339999999999)])⟩,
      ⟨3, ([(Int.negSucc 2162999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨4, ([(Int.negSucc 2069999999999)], [(Int.negSucc 2249999999999)])⟩,
      ⟨0, ([(Int.negSucc 1739999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 1559999999999)], [(Int.negSucc 1814999999999)])⟩,
      ⟨0, ([(Int.negSucc 659999999999)], [(Int.negSucc 899999999999)])⟩,
      ⟨9, ([(Int.ofNat 2760000000000)], [(Int.negSucc 11759999999999)])⟩,
      ⟨6, ([(Int.ofNat 3435000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3509999999999)])⟩,
      ⟨8, ([(Int.negSucc 10184999999999)], [(Int.ofNat 1185000000000)])⟩,
      ⟨8, ([(Int.negSucc 9974999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5055000000000)])⟩,
      ⟨3, ([(Int.negSucc 7964999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.negSucc 7214999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨5, ([(Int.negSucc 4787999999999)], [(Int.negSucc 4211999999999)])⟩,
      ⟨2, ([(Int.negSucc 2774999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1499999999999)], [(Int.negSucc 839999999999)])⟩,
      ⟨0, ([(Int.ofNat 1560000000000)], [(Int.ofNat 4875000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
