import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_350000_360000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_350000_360000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 7) 20), hi := (mkRat (Int.ofNat 9) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 4724999999999)], [(Int.ofNat 8475000000000)])⟩,
      ⟨3, ([(Int.negSucc 4649999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 150000000000)], [(Int.ofNat 4725000000000)])⟩,
      ⟨0, ([(Int.ofNat 450000000000)], [(Int.ofNat 4875000000000)])⟩,
      ⟨0, ([(Int.ofNat 825000000000)], [(Int.ofNat 4800000000000)])⟩,
      ⟨0, ([(Int.ofNat 900000000000)], [(Int.ofNat 4770000000000)])⟩,
      ⟨8, ([(Int.negSucc 13724999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2954999999999)])⟩,
      ⟨4, ([(Int.negSucc 5474999999999)], [(Int.negSucc 3524999999999)])⟩,
      ⟨4, ([(Int.negSucc 4274999999999)], [(Int.negSucc 224999999999)])⟩,
      ⟨4, ([(Int.negSucc 3794999999999)], [(Int.negSucc 3329999999999)])⟩,
      ⟨4, ([(Int.negSucc 3149999999999)], [(Int.negSucc 2624999999999)])⟩,
      ⟨4, ([(Int.negSucc 2774999999999)], [(Int.negSucc 2099999999999)])⟩,
      ⟨4, ([(Int.negSucc 2699999999999)], [(Int.negSucc 1799999999999)])⟩,
      ⟨6, ([(Int.ofNat 2775000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨9, ([(Int.ofNat 3150000000000)], [(Int.negSucc 12149999999999)])⟩,
      ⟨8, ([(Int.negSucc 10424999999999)], [(Int.ofNat 1425000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5670000000000)])⟩,
      ⟨5, ([(Int.negSucc 4049999999999)], [(Int.negSucc 4949999999999)])⟩,
      ⟨0, ([(Int.negSucc 1574999999999)], [(Int.ofNat 675000000000)])⟩,
      ⟨0, ([(Int.ofNat 1575000000000)], [(Int.negSucc 899999999999)])⟩,
      ⟨5, ([(Int.ofNat 3750000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨3, ([(Int.negSucc 7574999999999)], [(Int.ofNat 4200000000000)])⟩,
      ⟨3, ([(Int.negSucc 4724999999999)], [(Int.ofNat 8100000000000)])⟩,
      ⟨4, ([(Int.negSucc 4274999999999)], [(Int.negSucc 4724999999999)])⟩,
      ⟨4, ([(Int.negSucc 2924999999999)], [(Int.negSucc 2924999999999)])⟩,
      ⟨0, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3525000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
