import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_160000_170000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_160000_170000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 4) 25), hi := (mkRat (Int.ofNat 17) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 2591999999999)], [(Int.ofNat 8967000000000)])⟩,
      ⟨3, ([(Int.negSucc 2534999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 659999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.ofNat 480000000000)], [(Int.ofNat 6270000000000)])⟩,
      ⟨0, ([(Int.ofNat 660000000000)], [(Int.negSucc 659999999999)])⟩,
      ⟨0, ([(Int.ofNat 855000000000)], [(Int.negSucc 374999999999)])⟩,
      ⟨8, ([(Int.negSucc 11591999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8039999999999)], [(Int.ofNat 4020000000000)])⟩,
      ⟨4, ([(Int.negSucc 4319999999999)], [(Int.ofNat 570000000000)])⟩,
      ⟨0, ([(Int.negSucc 959999999999)], [(Int.ofNat 4710000000000)])⟩,
      ⟨8, ([(Int.negSucc 13394999999999)], [(Int.ofNat 4395000000000)])⟩,
      ⟨4, ([(Int.negSucc 4349999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨5, ([(Int.negSucc 3974999999999)], [(Int.negSucc 5024999999999)])⟩,
      ⟨0, ([(Int.negSucc 854999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨5, ([(Int.negSucc 749999999999)], [(Int.negSucc 5009999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5160000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 480000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 525000000000)])⟩,
      ⟨3, ([(Int.negSucc 2999999999999)], [(Int.ofNat 8040000000000)])⟩,
      ⟨9, ([(Int.ofNat 5010000000000)], [(Int.negSucc 14009999999999)])⟩,
      ⟨6, ([(Int.ofNat 5175000000000)], [(Int.negSucc 5894999999999)])⟩,
      ⟨6, ([(Int.ofNat 5175000000000)], [(Int.negSucc 5759999999999)])⟩,
      ⟨6, ([(Int.ofNat 5360000000000)], [(Int.negSucc 8039999999999)])⟩,
      ⟨8, ([(Int.negSucc 11384999999999)], [(Int.ofNat 2385000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5535000000000)])⟩,
      ⟨3, ([(Int.negSucc 8564999999999)], [(Int.ofNat 7125000000000)])⟩,
      ⟨5, ([(Int.negSucc 5369999999999)], [(Int.negSucc 3629999999999)])⟩,
      ⟨5, ([(Int.negSucc 524999999999)], [(Int.negSucc 3599999999999)])⟩,
      ⟨5, ([(Int.negSucc 479999999999)], [(Int.negSucc 3644999999999)])⟩,
      ⟨0, ([(Int.ofNat 480000000000)], [(Int.negSucc 854999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 15389999999999)])⟩,
      ⟨5, ([(Int.negSucc 5534999999999)], [(Int.negSucc 3464999999999)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.negSucc 1439999999999)])⟩,
      ⟨4, ([(Int.negSucc 2999999999999)], [(Int.negSucc 239999999999)])⟩,
      ⟨3, ([(Int.negSucc 2519999999999)], [(Int.ofNat 7695000000000)])⟩,
      ⟨0, ([(Int.negSucc 1439999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨9, ([(Int.ofNat 3600000000000)], [(Int.negSucc 12599999999999)])⟩,
      ⟨6, ([(Int.ofNat 3600000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨6, ([(Int.ofNat 3750000000000)], [(Int.negSucc 4319999999999)])⟩,
      ⟨8, ([(Int.negSucc 11519999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 10841999999999)], [(Int.ofNat 1842000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5835000000000)])⟩,
      ⟨5, ([(Int.negSucc 5684999999999)], [(Int.negSucc 3314999999999)])⟩,
      ⟨0, ([(Int.negSucc 974999999999)], [(Int.ofNat 0)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2564999999999)])⟩,
      ⟨6, ([(Int.ofNat 3465000000000)], [(Int.negSucc 8639999999999)])⟩,
      ⟨6, ([(Int.ofNat 3495000000000)], [(Int.negSucc 6374999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5399999999999)])⟩,
      ⟨0, ([(Int.ofNat 2580000000000)], [(Int.ofNat 4500000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
