import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_270000_280000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_270000_280000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 27) 100), hi := (mkRat (Int.ofNat 7) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 3998999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨3, ([(Int.negSucc 3809999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1214999999999)], [(Int.ofNat 465000000000)])⟩,
      ⟨0, ([(Int.negSucc 1214999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 1004999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.ofNat 270000000000)], [(Int.ofNat 5355000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1184999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 5385000000000)])⟩,
      ⟨0, ([(Int.ofNat 465000000000)], [(Int.negSucc 1214999999999)])⟩,
      ⟨0, ([(Int.ofNat 720000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.negSucc 1214999999999)])⟩,
      ⟨0, ([(Int.ofNat 900000000000)], [(Int.ofNat 5175000000000)])⟩,
      ⟨0, ([(Int.ofNat 1185000000000)], [(Int.negSucc 809999999999)])⟩,
      ⟨0, ([(Int.ofNat 1215000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 1215000000000)], [(Int.negSucc 464999999999)])⟩,
      ⟨8, ([(Int.negSucc 12824999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8414999999999)], [(Int.ofNat 3240000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.ofNat 360000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2519999999999)])⟩,
      ⟨4, ([(Int.negSucc 3569999999999)], [(Int.negSucc 2429999999999)])⟩,
      ⟨4, ([(Int.negSucc 3239999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨5, ([(Int.negSucc 3194999999999)], [(Int.negSucc 5804999999999)])⟩,
      ⟨6, ([(Int.ofNat 2625000000000)], [(Int.negSucc 4373999999999)])⟩,
      ⟨6, ([(Int.ofNat 4251000000000)], [(Int.negSucc 4625999999999)])⟩,
      ⟨8, ([(Int.negSucc 10619999999999)], [(Int.ofNat 1620000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3855000000000)])⟩,
      ⟨5, ([(Int.negSucc 4589999999999)], [(Int.negSucc 4409999999999)])⟩,
      ⟨4, ([(Int.negSucc 2249999999999)], [(Int.negSucc 1619999999999)])⟩,
      ⟨0, ([(Int.negSucc 1709999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 809999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨5, ([(Int.ofNat 2250000000000)], [(Int.negSucc 6749999999999)])⟩,
      ⟨6, ([(Int.ofNat 2610000000000)], [(Int.negSucc 4859999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 14174999999999)])⟩,
      ⟨3, ([(Int.negSucc 8189999999999)], [(Int.ofNat 5940000000000)])⟩,
      ⟨5, ([(Int.negSucc 4634999999999)], [(Int.negSucc 4364999999999)])⟩,
      ⟨3, ([(Int.negSucc 2624999999999)], [(Int.ofNat 6270000000000)])⟩,
      ⟨4, ([(Int.negSucc 2444999999999)], [(Int.negSucc 2429999999999)])⟩,
      ⟨0, ([(Int.negSucc 1934999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 1874999999999)], [(Int.negSucc 2264999999999)])⟩,
      ⟨3, ([(Int.negSucc 1709999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨4, ([(Int.negSucc 1214999999999)], [(Int.negSucc 1784999999999)])⟩,
      ⟨0, ([(Int.negSucc 569999999999)], [(Int.negSucc 1139999999999)])⟩,
      ⟨9, ([(Int.ofNat 2790000000000)], [(Int.negSucc 11789999999999)])⟩,
      ⟨6, ([(Int.ofNat 3435000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3764999999999)])⟩,
      ⟨8, ([(Int.negSucc 9929999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 9824999999999)], [(Int.ofNat 825000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4980000000000)])⟩,
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 5445000000000)])⟩,
      ⟨0, ([(Int.negSucc 7304999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨5, ([(Int.negSucc 4784999999999)], [(Int.negSucc 4214999999999)])⟩,
      ⟨2, ([(Int.negSucc 2939999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1529999999999)], [(Int.negSucc 899999999999)])⟩,
      ⟨0, ([(Int.ofNat 1515000000000)], [(Int.ofNat 4860000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
