import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_290000_300000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_290000_300000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 29) 100), hi := (mkRat (Int.ofNat 3) 10), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 4301999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨3, ([(Int.negSucc 4019999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1304999999999)], [(Int.ofNat 555000000000)])⟩,
      ⟨0, ([(Int.negSucc 554999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 270000000000)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.ofNat 870000000000)], [(Int.ofNat 4875000000000)])⟩,
      ⟨0, ([(Int.ofNat 1305000000000)], [(Int.negSucc 554999999999)])⟩,
      ⟨8, ([(Int.negSucc 13064999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8249999999999)], [(Int.ofNat 2730000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2594999999999)])⟩,
      ⟨4, ([(Int.negSucc 6359999999999)], [(Int.negSucc 2639999999999)])⟩,
      ⟨4, ([(Int.negSucc 4334999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 3899999999999)], [(Int.negSucc 2624999999999)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 2609999999999)])⟩,
      ⟨4, ([(Int.negSucc 3479999999999)], [(Int.negSucc 2519999999999)])⟩,
      ⟨4, ([(Int.negSucc 2999999999999)], [(Int.negSucc 2219999999999)])⟩,
      ⟨5, ([(Int.negSucc 2654999999999)], [(Int.negSucc 6344999999999)])⟩,
      ⟨4, ([(Int.negSucc 2624999999999)], [(Int.negSucc 1676999999999)])⟩,
      ⟨6, ([(Int.ofNat 2610000000000)], [(Int.negSucc 4499999999999)])⟩,
      ⟨6, ([(Int.ofNat 2610000000000)], [(Int.negSucc 4484999999999)])⟩,
      ⟨6, ([(Int.ofNat 3750000000000)], [(Int.negSucc 4697999999999)])⟩,
      ⟨8, ([(Int.negSucc 10979999999999)], [(Int.ofNat 1980000000000)])⟩,
      ⟨4, ([(Int.negSucc 8624999999999)], [(Int.ofNat 3105000000000)])⟩,
      ⟨5, ([(Int.ofNat 2610000000000)], [(Int.negSucc 7484999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 14399999999999)])⟩,
      ⟨8, ([(Int.negSucc 10844999999999)], [(Int.ofNat 1845000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3585000000000)])⟩,
      ⟨4, ([(Int.negSucc 6239999999999)], [(Int.negSucc 2759999999999)])⟩,
      ⟨5, ([(Int.negSucc 4319999999999)], [(Int.negSucc 4679999999999)])⟩,
      ⟨4, ([(Int.negSucc 2894999999999)], [(Int.negSucc 2624999999999)])⟩,
      ⟨4, ([(Int.negSucc 2639999999999)], [(Int.negSucc 2609999999999)])⟩,
      ⟨0, ([(Int.ofNat 720000000000)], [(Int.negSucc 1439999999999)])⟩,
      ⟨6, ([(Int.ofNat 2565000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨5, ([(Int.negSucc 4394999999999)], [(Int.negSucc 4604999999999)])⟩,
      ⟨0, ([(Int.negSucc 2654999999999)], [(Int.ofNat 0)])⟩,
      ⟨9, ([(Int.ofNat 1650000000000)], [(Int.negSucc 10649999999999)])⟩,
      ⟨6, ([(Int.ofNat 3645000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨1, ([(Int.ofNat 3915000000000)], [(Int.ofNat 2250000000000)])⟩,
      ⟨1, ([(Int.ofNat 7260000000000)], [(Int.negSucc 5009999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5984999999999)])⟩],
    last := 1 }

end ConwaySoifer.Simplified.Certificates.Data
