import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_110000_120000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_110000_120000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 11) 100), hi := (mkRat (Int.ofNat 3) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 1874999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 990000000000)])⟩,
      ⟨4, ([(Int.negSucc 8339999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 989999999999)], [(Int.ofNat 5490000000000)])⟩,
      ⟨0, ([(Int.negSucc 989999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨0, ([(Int.negSucc 689999999999)], [(Int.ofNat 5940000000000)])⟩,
      ⟨0, ([(Int.negSucc 329999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨8, ([(Int.negSucc 10919999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 7919999999999)], [(Int.ofNat 3420000000000)])⟩,
      ⟨4, ([(Int.negSucc 5939999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨4, ([(Int.negSucc 5864999999999)], [(Int.ofNat 990000000000)])⟩,
      ⟨8, ([(Int.negSucc 15419999999999)], [(Int.ofNat 6420000000000)])⟩,
      ⟨5, ([(Int.negSucc 2624999999999)], [(Int.negSucc 6374999999999)])⟩,
      ⟨5, ([(Int.negSucc 644999999999)], [(Int.negSucc 6374999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.ofNat 660000000000)])⟩,
      ⟨9, ([(Int.ofNat 6420000000000)], [(Int.negSucc 15419999999999)])⟩,
      ⟨6, ([(Int.ofNat 6630000000000)], [(Int.negSucc 7124999999999)])⟩,
      ⟨6, ([(Int.ofNat 6930000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨8, ([(Int.negSucc 13064999999999)], [(Int.ofNat 4065000000000)])⟩,
      ⟨3, ([(Int.negSucc 8624999999999)], [(Int.ofNat 7635000000000)])⟩,
      ⟨5, ([(Int.negSucc 5999999999999)], [(Int.negSucc 2999999999999)])⟩,
      ⟨5, ([(Int.negSucc 989999999999)], [(Int.negSucc 3749999999999)])⟩,
      ⟨5, ([(Int.negSucc 899999999999)], [(Int.negSucc 3959999999999)])⟩,
      ⟨1, ([(Int.ofNat 8250000000000)], [(Int.negSucc 734999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 16169999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 1259999999999)])⟩,
      ⟨4, ([(Int.negSucc 5009999999999)], [(Int.negSucc 989999999999)])⟩,
      ⟨0, ([(Int.negSucc 989999999999)], [(Int.ofNat 5115000000000)])⟩,
      ⟨0, ([(Int.negSucc 989999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 6843000000000)])⟩,
      ⟨9, ([(Int.ofNat 3000000000000)], [(Int.negSucc 11969999999999)])⟩,
      ⟨6, ([(Int.ofNat 3000000000000)], [(Int.negSucc 8339999999999)])⟩,
      ⟨6, ([(Int.ofNat 3750000000000)], [(Int.negSucc 4739999999999)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.ofNat 90000000000)])⟩,
      ⟨5, ([(Int.negSucc 329999999999)], [(Int.negSucc 3374999999999)])⟩,
      ⟨6, ([(Int.ofNat 3000000000000)], [(Int.negSucc 7919999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 5504999999999)])⟩,
      ⟨0, ([(Int.ofNat 2430000000000)], [(Int.ofNat 5250000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
