import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_100000_110000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_100000_110000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 1) 10), hi := (mkRat (Int.ofNat 11) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 1754999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 900000000000)])⟩,
      ⟨7, ([(Int.ofNat 8100000000000)], [(Int.ofNat 8100000000000)])⟩,
      ⟨4, ([(Int.negSucc 8099999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 5400000000000)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 6150000000000)])⟩,
      ⟨0, ([(Int.negSucc 449999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨8, ([(Int.negSucc 10799999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 7874999999999)], [(Int.ofNat 3375000000000)])⟩,
      ⟨4, ([(Int.negSucc 5624999999999)], [(Int.ofNat 900000000000)])⟩,
      ⟨8, ([(Int.negSucc 15299999999999)], [(Int.ofNat 6300000000000)])⟩,
      ⟨5, ([(Int.negSucc 2699999999999)], [(Int.negSucc 6299999999999)])⟩,
      ⟨5, ([(Int.negSucc 599999999999)], [(Int.negSucc 6374999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 6150000000000)])⟩,
      ⟨4, ([(Int.negSucc 5399999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨9, ([(Int.ofNat 6300000000000)], [(Int.negSucc 15299999999999)])⟩,
      ⟨6, ([(Int.ofNat 6750000000000)], [(Int.negSucc 7649999999999)])⟩,
      ⟨6, ([(Int.ofNat 6750000000000)], [(Int.negSucc 7349999999999)])⟩,
      ⟨6, ([(Int.ofNat 6900000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨8, ([(Int.negSucc 12524999999999)], [(Int.ofNat 3525000000000)])⟩,
      ⟨3, ([(Int.negSucc 8699999999999)], [(Int.ofNat 7800000000000)])⟩,
      ⟨5, ([(Int.negSucc 6149999999999)], [(Int.negSucc 2849999999999)])⟩,
      ⟨5, ([(Int.negSucc 899999999999)], [(Int.negSucc 3599999999999)])⟩,
      ⟨1, ([(Int.ofNat 8250000000000)], [(Int.negSucc 599999999999)])⟩,
      ⟨1, ([(Int.ofNat 8550000000000)], [(Int.negSucc 854999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 16379999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 1124999999999)])⟩,
      ⟨4, ([(Int.negSucc 5099999999999)], [(Int.negSucc 899999999999)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 5025000000000)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 6525000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 7005000000000)])⟩,
      ⟨6, ([(Int.ofNat 2850000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨6, ([(Int.ofNat 3375000000000)], [(Int.negSucc 4724999999999)])⟩,
      ⟨0, ([(Int.negSucc 629999999999)], [(Int.ofNat 0)])⟩,
      ⟨1, ([(Int.ofNat 7500000000000)], [(Int.negSucc 3899999999999)])⟩,
      ⟨0, ([(Int.ofNat 2550000000000)], [(Int.ofNat 5250000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
