import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_310000_320000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_310000_320000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 31) 100), hi := (mkRat (Int.ofNat 8) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 4439999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨3, ([(Int.negSucc 4229999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1394999999999)], [(Int.ofNat 645000000000)])⟩,
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 644999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 1079999999999)])⟩,
      ⟨0, ([(Int.ofNat 153000000000)], [(Int.ofNat 5022000000000)])⟩,
      ⟨0, ([(Int.ofNat 645000000000)], [(Int.negSucc 1394999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.negSucc 1394999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 5022000000000)])⟩,
      ⟨0, ([(Int.ofNat 930000000000)], [(Int.ofNat 4875000000000)])⟩,
      ⟨0, ([(Int.ofNat 1395000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 1395000000000)], [(Int.negSucc 644999999999)])⟩,
      ⟨8, ([(Int.negSucc 13244999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5021999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨3, ([(Int.negSucc 4271999999999)], [(Int.ofNat 8250000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2729999999999)])⟩,
      ⟨8, ([(Int.negSucc 14279999999999)], [(Int.ofNat 5280000000000)])⟩,
      ⟨4, ([(Int.negSucc 8369999999999)], [(Int.ofNat 3000000000000)])⟩,
      ⟨3, ([(Int.negSucc 8369999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨4, ([(Int.negSucc 6104999999999)], [(Int.negSucc 2894999999999)])⟩,
      ⟨4, ([(Int.negSucc 4289999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.negSucc 2849999999999)])⟩,
      ⟨4, ([(Int.negSucc 3584999999999)], [(Int.negSucc 2789999999999)])⟩,
      ⟨4, ([(Int.negSucc 2999999999999)], [(Int.negSucc 2279999999999)])⟩,
      ⟨4, ([(Int.negSucc 2789999999999)], [(Int.negSucc 2084999999999)])⟩,
      ⟨4, ([(Int.negSucc 2729999999999)], [(Int.negSucc 1394999999999)])⟩,
      ⟨6, ([(Int.ofNat 2790000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨9, ([(Int.ofNat 3495000000000)], [(Int.negSucc 12494999999999)])⟩,
      ⟨6, ([(Int.ofNat 4185000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨8, ([(Int.negSucc 10859999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨8, ([(Int.negSucc 10559999999999)], [(Int.ofNat 1560000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 6105000000000)])⟩,
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 5580000000000)])⟩,
      ⟨5, ([(Int.negSucc 4379999999999)], [(Int.negSucc 4619999999999)])⟩,
      ⟨0, ([(Int.negSucc 1499999999999)], [(Int.ofNat 570000000000)])⟩,
      ⟨0, ([(Int.ofNat 105000000000)], [(Int.ofNat 5175000000000)])⟩,
      ⟨5, ([(Int.ofNat 3000000000000)], [(Int.negSucc 8021999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 14279999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3603000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2579999999999)])⟩,
      ⟨9, ([(Int.ofNat 1020000000000)], [(Int.negSucc 10019999999999)])⟩,
      ⟨6, ([(Int.ofNat 2475000000000)], [(Int.negSucc 4499999999999)])⟩,
      ⟨6, ([(Int.ofNat 3645000000000)], [(Int.negSucc 8999999999999)])⟩],
    last := 6 }

end ConwaySoifer.Simplified.Certificates.Data
