import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_170000_180000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_170000_180000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 17) 100), hi := (mkRat (Int.ofNat 9) 50), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 2654999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 884999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 509999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 884999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 6120000000000)])⟩,
      ⟨0, ([(Int.ofNat 885000000000)], [(Int.negSucc 509999999999)])⟩,
      ⟨9, ([(Int.ofNat 7875000000000)], [(Int.negSucc 15749999999999)])⟩,
      ⟨8, ([(Int.negSucc 11684999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8099999999999)], [(Int.ofNat 3690000000000)])⟩,
      ⟨4, ([(Int.negSucc 7979999999999)], [(Int.ofNat 3855000000000)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 2040000000000)])⟩,
      ⟨4, ([(Int.negSucc 5174999999999)], [(Int.ofNat 1125000000000)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.ofNat 765000000000)])⟩,
      ⟨3, ([(Int.negSucc 2753999999999)], [(Int.ofNat 8754000000000)])⟩,
      ⟨8, ([(Int.negSucc 14114999999999)], [(Int.ofNat 5115000000000)])⟩,
      ⟨3, ([(Int.negSucc 8234999999999)], [(Int.ofNat 7110000000000)])⟩,
      ⟨4, ([(Int.negSucc 6119999999999)], [(Int.ofNat 2250000000000)])⟩,
      ⟨5, ([(Int.negSucc 3620999999999)], [(Int.negSucc 5378999999999)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 390000000000)])⟩,
      ⟨5, ([(Int.negSucc 509999999999)], [(Int.negSucc 5489999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5121000000000)])⟩,
      ⟨4, ([(Int.negSucc 4409999999999)], [(Int.ofNat 441000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 4950000000000)])⟩,
      ⟨6, ([(Int.ofNat 5625000000000)], [(Int.negSucc 6134999999999)])⟩,
      ⟨6, ([(Int.ofNat 5625000000000)], [(Int.negSucc 6119999999999)])⟩,
      ⟨6, ([(Int.ofNat 5835000000000)], [(Int.negSucc 7874999999999)])⟩,
      ⟨8, ([(Int.negSucc 11369999999999)], [(Int.ofNat 2370000000000)])⟩,
      ⟨3, ([(Int.negSucc 8489999999999)], [(Int.ofNat 6990000000000)])⟩,
      ⟨5, ([(Int.negSucc 5120999999999)], [(Int.negSucc 3878999999999)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 510000000000)])⟩,
      ⟨5, ([(Int.negSucc 509999999999)], [(Int.negSucc 3989999999999)])⟩,
      ⟨9, ([(Int.ofNat 8370000000000)], [(Int.negSucc 15119999999999)])⟩,
      ⟨1, ([(Int.ofNat 8490000000000)], [(Int.negSucc 1499999999999)])⟩,
      ⟨5, ([(Int.negSucc 5345999999999)], [(Int.negSucc 3653999999999)])⟩,
      ⟨4, ([(Int.negSucc 4844999999999)], [(Int.negSucc 1529999999999)])⟩,
      ⟨4, ([(Int.negSucc 3404999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 1529999999999)], [(Int.ofNat 5280000000000)])⟩,
      ⟨5, ([(Int.negSucc 509999999999)], [(Int.negSucc 3749999999999)])⟩,
      ⟨0, ([(Int.ofNat 180000000000)], [(Int.ofNat 6375000000000)])⟩,
      ⟨9, ([(Int.ofNat 3870000000000)], [(Int.negSucc 12869999999999)])⟩,
      ⟨5, ([(Int.negSucc 5459999999999)], [(Int.negSucc 3539999999999)])⟩,
      ⟨4, ([(Int.negSucc 2534999999999)], [(Int.ofNat 0)])⟩,
      ⟨5, ([(Int.negSucc 2524499999999)], [(Int.negSucc 3415499999999)])⟩,
      ⟨0, ([(Int.negSucc 1019999999999)], [(Int.ofNat 120000000000)])⟩,
      ⟨6, ([(Int.ofNat 3660000000000)], [(Int.negSucc 8249999999999)])⟩,
      ⟨6, ([(Int.ofNat 3660000000000)], [(Int.negSucc 4409999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 4424999999999)])⟩,
      ⟨0, ([(Int.ofNat 2535000000000)], [(Int.ofNat 4590000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
