import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_150000_160000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_150000_160000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 3) 20), hi := (mkRat (Int.ofNat 4) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 2399999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.ofNat 825000000000)], [(Int.negSucc 374999999999)])⟩,
      ⟨8, ([(Int.negSucc 11399999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 4950000000000)])⟩,
      ⟨0, ([(Int.negSucc 449999999999)], [(Int.ofNat 4575000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.ofNat 4425000000000)])⟩,
      ⟨4, ([(Int.negSucc 8099999999999)], [(Int.ofNat 2475000000000)])⟩,
      ⟨4, ([(Int.negSucc 7649999999999)], [(Int.ofNat 2025000000000)])⟩,
      ⟨4, ([(Int.negSucc 6569999999999)], [(Int.ofNat 570000000000)])⟩,
      ⟨8, ([(Int.negSucc 15569999999999)], [(Int.ofNat 6570000000000)])⟩,
      ⟨3, ([(Int.negSucc 8549999999999)], [(Int.ofNat 7425000000000)])⟩,
      ⟨5, ([(Int.negSucc 1574999999999)], [(Int.negSucc 7424999999999)])⟩,
      ⟨5, ([(Int.negSucc 449999999999)], [(Int.negSucc 6374999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5325000000000)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨0, ([(Int.negSucc 449999999999)], [(Int.ofNat 5175000000000)])⟩,
      ⟨0, ([(Int.negSucc 374999999999)], [(Int.negSucc 449999999999)])⟩,
      ⟨6, ([(Int.ofNat 6825000000000)], [(Int.negSucc 7199999999999)])⟩,
      ⟨4, ([(Int.negSucc 5999999999999)], [(Int.ofNat 450000000000)])⟩,
      ⟨5, ([(Int.negSucc 4349999999999)], [(Int.negSucc 4649999999999)])⟩,
      ⟨5, ([(Int.negSucc 674999999999)], [(Int.negSucc 4499999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 16199999999999)])⟩,
      ⟨8, ([(Int.negSucc 15224999999999)], [(Int.ofNat 6225000000000)])⟩,
      ⟨3, ([(Int.negSucc 8474999999999)], [(Int.ofNat 7125000000000)])⟩,
      ⟨4, ([(Int.negSucc 5444999999999)], [(Int.ofNat 0)])⟩,
      ⟨5, ([(Int.negSucc 4874999999999)], [(Int.negSucc 4124999999999)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 5250000000000)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 5850000000000)])⟩,
      ⟨0, ([(Int.negSucc 224999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.ofNat 5550000000000)])⟩,
      ⟨6, ([(Int.ofNat 4650000000000)], [(Int.negSucc 5399999999999)])⟩,
      ⟨6, ([(Int.ofNat 4695000000000)], [(Int.negSucc 6569999999999)])⟩,
      ⟨4, ([(Int.negSucc 5249999999999)], [(Int.ofNat 0)])⟩,
      ⟨5, ([(Int.negSucc 5174999999999)], [(Int.negSucc 3824999999999)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.ofNat 450000000000)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 5100000000000)])⟩,
      ⟨0, ([(Int.negSucc 1349999999999)], [(Int.ofNat 6000000000000)])⟩,
      ⟨5, ([(Int.negSucc 374999999999)], [(Int.negSucc 4049999999999)])⟩,
      ⟨0, ([(Int.ofNat 180000000000)], [(Int.ofNat 6570000000000)])⟩,
      ⟨0, ([(Int.ofNat 450000000000)], [(Int.negSucc 824999999999)])⟩,
      ⟨9, ([(Int.ofNat 4125000000000)], [(Int.negSucc 13049999999999)])⟩,
      ⟨6, ([(Int.ofNat 4275000000000)], [(Int.negSucc 8099999999999)])⟩,
      ⟨9, ([(Int.ofNat 4425000000000)], [(Int.negSucc 13049999999999)])⟩,
      ⟨6, ([(Int.ofNat 4500000000000)], [(Int.negSucc 5624999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 15224999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 2804999999999)])⟩,
      ⟨5, ([(Int.negSucc 5324999999999)], [(Int.negSucc 3674999999999)])⟩,
      ⟨4, ([(Int.negSucc 4649999999999)], [(Int.negSucc 1349999999999)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 1500000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨1, ([(Int.ofNat 3375000000000)], [(Int.ofNat 4125000000000)])⟩,
      ⟨9, ([(Int.ofNat 3900000000000)], [(Int.negSucc 12899999999999)])⟩,
      ⟨6, ([(Int.ofNat 3900000000000)], [(Int.negSucc 7649999999999)])⟩,
      ⟨6, ([(Int.ofNat 4050000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3374999999999)])⟩,
      ⟨0, ([(Int.ofNat 1680000000000)], [(Int.ofNat 750000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
