import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_320000_330000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_320000_330000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 8) 25), hi := (mkRat (Int.ofNat 33) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 4499999999999)], [(Int.ofNat 8640000000000)])⟩,
      ⟨3, ([(Int.negSucc 4319999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1439999999999)], [(Int.ofNat 690000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 689999999999)])⟩,
      ⟨0, ([(Int.ofNat 195000000000)], [(Int.ofNat 4680000000000)])⟩,
      ⟨0, ([(Int.ofNat 285000000000)], [(Int.ofNat 4875000000000)])⟩,
      ⟨0, ([(Int.ofNat 360000000000)], [(Int.ofNat 4890000000000)])⟩,
      ⟨0, ([(Int.ofNat 690000000000)], [(Int.negSucc 1439999999999)])⟩,
      ⟨0, ([(Int.ofNat 960000000000)], [(Int.ofNat 4875000000000)])⟩,
      ⟨0, ([(Int.ofNat 1440000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨9, ([(Int.ofNat 6750000000000)], [(Int.negSucc 13319999999999)])⟩,
      ⟨8, ([(Int.negSucc 13319999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8504999999999)], [(Int.ofNat 2880000000000)])⟩,
      ⟨3, ([(Int.negSucc 4409999999999)], [(Int.ofNat 8250000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2834999999999)])⟩,
      ⟨4, ([(Int.negSucc 6044999999999)], [(Int.negSucc 2954999999999)])⟩,
      ⟨4, ([(Int.negSucc 4334999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 3815999999999)], [(Int.negSucc 2933999999999)])⟩,
      ⟨4, ([(Int.negSucc 2879999999999)], [(Int.negSucc 2249999999999)])⟩,
      ⟨4, ([(Int.negSucc 2819999999999)], [(Int.negSucc 1499999999999)])⟩,
      ⟨6, ([(Int.ofNat 2880000000000)], [(Int.negSucc 5129999999999)])⟩,
      ⟨6, ([(Int.ofNat 3240000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨9, ([(Int.ofNat 3510000000000)], [(Int.negSucc 12509999999999)])⟩,
      ⟨6, ([(Int.ofNat 4875000000000)], [(Int.negSucc 5159999999999)])⟩,
      ⟨6, ([(Int.ofNat 5160000000000)], [(Int.negSucc 8099999999999)])⟩,
      ⟨8, ([(Int.negSucc 10634999999999)], [(Int.ofNat 1635000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3495000000000)])⟩,
      ⟨3, ([(Int.negSucc 8999999999999)], [(Int.ofNat 6045000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 5760000000000)])⟩,
      ⟨0, ([(Int.ofNat 90000000000)], [(Int.ofNat 5160000000000)])⟩,
      ⟨5, ([(Int.ofNat 3375000000000)], [(Int.negSucc 8558999999999)])⟩,
      ⟨5, ([(Int.ofNat 3390000000000)], [(Int.negSucc 8639999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 2939999999999)])⟩,
      ⟨8, ([(Int.negSucc 10514999999999)], [(Int.ofNat 1515000000000)])⟩,
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 5184000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.negSucc 4319999999999)])⟩,
      ⟨5, ([(Int.negSucc 4379999999999)], [(Int.negSucc 4619999999999)])⟩,
      ⟨4, ([(Int.negSucc 4184999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 3134999999999)], [(Int.negSucc 3239999999999)])⟩,
      ⟨0, ([(Int.negSucc 1919999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2558999999999)])⟩,
      ⟨0, ([(Int.ofNat 66000000000)], [(Int.ofNat 5184000000000)])⟩,
      ⟨9, ([(Int.ofNat 795000000000)], [(Int.negSucc 9794999999999)])⟩,
      ⟨6, ([(Int.ofNat 2430000000000)], [(Int.negSucc 4679999999999)])⟩,
      ⟨5, ([(Int.ofNat 3540000000000)], [(Int.negSucc 8999999999999)])⟩,
      ⟨0, ([(Int.negSucc 4439999999999)], [(Int.negSucc 4559999999999)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
