import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_340000_350000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_340000_350000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 17) 50), hi := (mkRat (Int.ofNat 7) 20), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 4544999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨3, ([(Int.negSucc 4529999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1529999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 779999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 180000000000)], [(Int.ofNat 4875000000000)])⟩,
      ⟨0, ([(Int.ofNat 330000000000)], [(Int.ofNat 4920000000000)])⟩,
      ⟨0, ([(Int.ofNat 633000000000)], [(Int.ofNat 4875000000000)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.negSucc 1529999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 4758000000000)])⟩,
      ⟨0, ([(Int.ofNat 1530000000000)], [(Int.negSucc 779999999999)])⟩,
      ⟨0, ([(Int.ofNat 1530000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨8, ([(Int.negSucc 13589999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 5054999999999)], [(Int.ofNat 180000000000)])⟩,
      ⟨3, ([(Int.negSucc 4589999999999)], [(Int.ofNat 8250000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2834999999999)])⟩,
      ⟨8, ([(Int.negSucc 14219999999999)], [(Int.ofNat 5220000000000)])⟩,
      ⟨4, ([(Int.negSucc 8624999999999)], [(Int.ofNat 2880000000000)])⟩,
      ⟨4, ([(Int.negSucc 5507999999999)], [(Int.negSucc 3491999999999)])⟩,
      ⟨4, ([(Int.negSucc 4664999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 3239999999999)])⟩,
      ⟨4, ([(Int.negSucc 2999999999999)], [(Int.negSucc 2507999999999)])⟩,
      ⟨4, ([(Int.negSucc 2879999999999)], [(Int.negSucc 2369999999999)])⟩,
      ⟨4, ([(Int.negSucc 2879999999999)], [(Int.negSucc 1619999999999)])⟩,
      ⟨6, ([(Int.ofNat 2835000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨9, ([(Int.ofNat 3330000000000)], [(Int.negSucc 12329999999999)])⟩,
      ⟨8, ([(Int.negSucc 10559999999999)], [(Int.ofNat 1560000000000)])⟩,
      ⟨3, ([(Int.negSucc 7739999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨3, ([(Int.negSucc 7649999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨5, ([(Int.negSucc 4079999999999)], [(Int.negSucc 4919999999999)])⟩,
      ⟨5, ([(Int.ofNat 3240000000000)], [(Int.negSucc 8414999999999)])⟩,
      ⟨5, ([(Int.ofNat 3375000000000)], [(Int.negSucc 8882999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3480000000000)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 3899999999999)])⟩,
      ⟨4, ([(Int.negSucc 3491999999999)], [(Int.negSucc 3632999999999)])⟩,
      ⟨0, ([(Int.negSucc 3239999999999)], [(Int.ofNat 4365000000000)])⟩,
      ⟨0, ([(Int.negSucc 3464999999999)], [(Int.ofNat 0)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
