import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_280000_290000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_280000_290000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 7) 25), hi := (mkRat (Int.ofNat 29) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 3959999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨3, ([(Int.negSucc 3914999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1259999999999)], [(Int.ofNat 510000000000)])⟩,
      ⟨0, ([(Int.negSucc 1259999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨0, ([(Int.negSucc 839999999999)], [(Int.negSucc 374999999999)])⟩,
      ⟨0, ([(Int.ofNat 210000000000)], [(Int.ofNat 5040000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1214999999999)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.ofNat 5265000000000)])⟩,
      ⟨0, ([(Int.ofNat 840000000000)], [(Int.negSucc 1214999999999)])⟩,
      ⟨0, ([(Int.ofNat 960000000000)], [(Int.ofNat 5040000000000)])⟩,
      ⟨0, ([(Int.ofNat 1215000000000)], [(Int.negSucc 839999999999)])⟩,
      ⟨0, ([(Int.ofNat 1260000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 1260000000000)], [(Int.negSucc 509999999999)])⟩,
      ⟨8, ([(Int.negSucc 12914999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8249999999999)], [(Int.ofNat 3030000000000)])⟩,
      ⟨4, ([(Int.negSucc 5219999999999)], [(Int.ofNat 720000000000)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.ofNat 339000000000)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2579999999999)])⟩,
      ⟨8, ([(Int.negSucc 14399999999999)], [(Int.ofNat 5400000000000)])⟩,
      ⟨3, ([(Int.negSucc 7994999999999)], [(Int.ofNat 6120000000000)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 2519999999999)])⟩,
      ⟨5, ([(Int.negSucc 2879999999999)], [(Int.negSucc 6119999999999)])⟩,
      ⟨4, ([(Int.negSucc 2639999999999)], [(Int.negSucc 1319999999999)])⟩,
      ⟨4, ([(Int.negSucc 2624999999999)], [(Int.negSucc 1910999999999)])⟩,
      ⟨6, ([(Int.ofNat 2589000000000)], [(Int.negSucc 4463999999999)])⟩,
      ⟨6, ([(Int.ofNat 2976000000000)], [(Int.negSucc 4463999999999)])⟩,
      ⟨8, ([(Int.negSucc 10769999999999)], [(Int.ofNat 1770000000000)])⟩,
      ⟨4, ([(Int.negSucc 8624999999999)], [(Int.ofNat 3405000000000)])⟩,
      ⟨5, ([(Int.negSucc 4514999999999)], [(Int.negSucc 4484999999999)])⟩,
      ⟨0, ([(Int.negSucc 1679999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 839999999999)], [(Int.negSucc 659999999999)])⟩,
      ⟨5, ([(Int.ofNat 2445000000000)], [(Int.negSucc 7319999999999)])⟩,
      ⟨8, ([(Int.negSucc 10664999999999)], [(Int.ofNat 1665000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 3780000000000)])⟩,
      ⟨5, ([(Int.negSucc 4535999999999)], [(Int.negSucc 4463999999999)])⟩,
      ⟨4, ([(Int.negSucc 2624999999999)], [(Int.negSucc 2519999999999)])⟩,
      ⟨3, ([(Int.negSucc 2249999999999)], [(Int.ofNat 6300000000000)])⟩,
      ⟨4, ([(Int.negSucc 1874999999999)], [(Int.negSucc 1679999999999)])⟩,
      ⟨0, ([(Int.negSucc 1874999999999)], [(Int.ofNat 195000000000)])⟩,
      ⟨0, ([(Int.negSucc 839999999999)], [(Int.negSucc 749999999999)])⟩,
      ⟨6, ([(Int.ofNat 3000000000000)], [(Int.negSucc 7319999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3239999999999)])⟩,
      ⟨8, ([(Int.negSucc 10259999999999)], [(Int.ofNat 1260000000000)])⟩,
      ⟨8, ([(Int.negSucc 10124999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4860000000000)])⟩,
      ⟨3, ([(Int.negSucc 7874999999999)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.negSucc 7124999999999)], [(Int.ofNat 4605000000000)])⟩,
      ⟨5, ([(Int.negSucc 4604999999999)], [(Int.negSucc 4394999999999)])⟩,
      ⟨2, ([(Int.negSucc 2834999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 2519999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.ofNat 1425000000000)], [(Int.ofNat 4875000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
