import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_200000_210000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_200000_210000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 1) 5), hi := (mkRat (Int.ofNat 21) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 3239999999999)], [(Int.ofNat 8865000000000)])⟩,
      ⟨3, ([(Int.negSucc 3074999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 974999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.ofNat 300000000000)], [(Int.ofNat 6000000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 974999999999)])⟩,
      ⟨0, ([(Int.ofNat 600000000000)], [(Int.negSucc 974999999999)])⟩,
      ⟨0, ([(Int.ofNat 600000000000)], [(Int.ofNat 5775000000000)])⟩,
      ⟨0, ([(Int.ofNat 975000000000)], [(Int.negSucc 599999999999)])⟩,
      ⟨8, ([(Int.negSucc 12074999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8099999999999)], [(Int.ofNat 3600000000000)])⟩,
      ⟨4, ([(Int.negSucc 5174999999999)], [(Int.ofNat 1200000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.ofNat 600000000000)])⟩,
      ⟨8, ([(Int.negSucc 13799999999999)], [(Int.ofNat 4800000000000)])⟩,
      ⟨5, ([(Int.negSucc 3449999999999)], [(Int.negSucc 5549999999999)])⟩,
      ⟨5, ([(Int.negSucc 575999999999)], [(Int.negSucc 5183999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨9, ([(Int.ofNat 5325000000000)], [(Int.negSucc 14324999999999)])⟩,
      ⟨6, ([(Int.ofNat 5400000000000)], [(Int.negSucc 5999999999999)])⟩,
      ⟨6, ([(Int.ofNat 5760000000000)], [(Int.negSucc 8099999999999)])⟩,
      ⟨8, ([(Int.negSucc 11774999999999)], [(Int.ofNat 2775000000000)])⟩,
      ⟨3, ([(Int.negSucc 8249999999999)], [(Int.ofNat 6600000000000)])⟩,
      ⟨5, ([(Int.negSucc 4499999999999)], [(Int.negSucc 4499999999999)])⟩,
      ⟨5, ([(Int.negSucc 4499999999999)], [(Int.negSucc 3899999999999)])⟩,
      ⟨5, ([(Int.negSucc 599999999999)], [(Int.negSucc 4124999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 15149999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 2024999999999)])⟩,
      ⟨4, ([(Int.negSucc 4874999999999)], [(Int.negSucc 1799999999999)])⟩,
      ⟨0, ([(Int.negSucc 1274999999999)], [(Int.ofNat 4875000000000)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 5550000000000)])⟩,
      ⟨9, ([(Int.ofNat 3900000000000)], [(Int.negSucc 12899999999999)])⟩,
      ⟨6, ([(Int.ofNat 4275000000000)], [(Int.negSucc 8399999999999)])⟩,
      ⟨6, ([(Int.ofNat 4275000000000)], [(Int.negSucc 4874999999999)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 525000000000)])⟩,
      ⟨0, ([(Int.negSucc 1199999999999)], [(Int.ofNat 300000000000)])⟩,
      ⟨0, ([(Int.negSucc 749999999999)], [(Int.negSucc 449999999999)])⟩,
      ⟨5, ([(Int.negSucc 374999999999)], [(Int.negSucc 4124999999999)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 4874999999999)])⟩,
      ⟨1, ([(Int.ofNat 7500000000000)], [(Int.negSucc 2399999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3989999999999)])⟩,
      ⟨5, ([(Int.negSucc 5174999999999)], [(Int.negSucc 3824999999999)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.negSucc 1799999999999)])⟩,
      ⟨4, ([(Int.negSucc 3374999999999)], [(Int.ofNat 0)])⟩,
      ⟨3, ([(Int.negSucc 2399999999999)], [(Int.ofNat 6900000000000)])⟩,
      ⟨0, ([(Int.ofNat 1800000000000)], [(Int.ofNat 4950000000000)])⟩,
      ⟨0, ([(Int.ofNat 1875000000000)], [(Int.ofNat 4500000000000)])⟩,
      ⟨1, ([(Int.ofNat 3240000000000)], [(Int.ofNat 3750000000000)])⟩,
      ⟨8, ([(Int.negSucc 11399999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 10799999999999)], [(Int.ofNat 1800000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5550000000000)])⟩,
      ⟨5, ([(Int.negSucc 5249999999999)], [(Int.negSucc 3749999999999)])⟩,
      ⟨3, ([(Int.negSucc 4424999999999)], [(Int.ofNat 2625000000000)])⟩,
      ⟨2, ([(Int.negSucc 1799999999999)], [(Int.ofNat 8550000000000)])⟩,
      ⟨6, ([(Int.ofNat 1725000000000)], [(Int.negSucc 1724999999999)])⟩,
      ⟨0, ([(Int.ofNat 2400000000000)], [(Int.ofNat 4725000000000)])⟩,
      ⟨0, ([(Int.ofNat 4050000000000)], [(Int.ofNat 0)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
