import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_230000_240000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_230000_240000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 23) 100), hi := (mkRat (Int.ofNat 6) 25), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 3359999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1064999999999)], [(Int.ofNat 375000000000)])⟩,
      ⟨0, ([(Int.negSucc 1064999999999)], [(Int.ofNat 690000000000)])⟩,
      ⟨0, ([(Int.negSucc 899999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.ofNat 0)], [(Int.negSucc 899999999999)])⟩,
      ⟨0, ([(Int.ofNat 270000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.ofNat 375000000000)], [(Int.negSucc 1064999999999)])⟩,
      ⟨0, ([(Int.ofNat 690000000000)], [(Int.negSucc 1064999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.negSucc 1034999999999)])⟩,
      ⟨0, ([(Int.ofNat 750000000000)], [(Int.ofNat 5490000000000)])⟩,
      ⟨0, ([(Int.ofNat 1035000000000)], [(Int.negSucc 749999999999)])⟩,
      ⟨0, ([(Int.ofNat 1125000000000)], [(Int.negSucc 434999999999)])⟩,
      ⟨8, ([(Int.negSucc 12374999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8294999999999)], [(Int.ofNat 3420000000000)])⟩,
      ⟨4, ([(Int.negSucc 5159999999999)], [(Int.ofNat 1035000000000)])⟩,
      ⟨4, ([(Int.negSucc 4859999999999)], [(Int.ofNat 750000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.ofNat 360000000000)])⟩,
      ⟨3, ([(Int.negSucc 3449999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨8, ([(Int.negSucc 13859999999999)], [(Int.ofNat 4860000000000)])⟩,
      ⟨5, ([(Int.negSucc 3314999999999)], [(Int.negSucc 5684999999999)])⟩,
      ⟨0, ([(Int.negSucc 1124999999999)], [(Int.ofNat 435000000000)])⟩,
      ⟨5, ([(Int.negSucc 374999999999)], [(Int.negSucc 4799999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4374000000000)])⟩,
      ⟨9, ([(Int.ofNat 4860000000000)], [(Int.negSucc 13859999999999)])⟩,
      ⟨6, ([(Int.ofNat 5175000000000)], [(Int.negSucc 5549999999999)])⟩,
      ⟨6, ([(Int.ofNat 5625000000000)], [(Int.negSucc 8279999999999)])⟩,
      ⟨8, ([(Int.negSucc 13529999999999)], [(Int.ofNat 4530000000000)])⟩,
      ⟨3, ([(Int.negSucc 8279999999999)], [(Int.ofNat 6375000000000)])⟩,
      ⟨5, ([(Int.negSucc 4373999999999)], [(Int.negSucc 4625999999999)])⟩,
      ⟨5, ([(Int.negSucc 4184999999999)], [(Int.negSucc 4124999999999)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 2384999999999)])⟩,
      ⟨0, ([(Int.ofNat 690000000000)], [(Int.negSucc 1124999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 14834999999999)])⟩,
      ⟨4, ([(Int.negSucc 3929999999999)], [(Int.ofNat 0)])⟩,
      ⟨4, ([(Int.negSucc 3749999999999)], [(Int.negSucc 2069999999999)])⟩,
      ⟨3, ([(Int.negSucc 3725999999999)], [(Int.ofNat 8226000000000)])⟩,
      ⟨4, ([(Int.negSucc 2369999999999)], [(Int.negSucc 1379999999999)])⟩,
      ⟨0, ([(Int.negSucc 1394999999999)], [(Int.ofNat 4500000000000)])⟩,
      ⟨6, ([(Int.ofNat 2385000000000)], [(Int.negSucc 5174999999999)])⟩,
      ⟨6, ([(Int.ofNat 2520000000000)], [(Int.negSucc 5894999999999)])⟩,
      ⟨6, ([(Int.ofNat 2625000000000)], [(Int.negSucc 4139999999999)])⟩,
      ⟨9, ([(Int.ofNat 3351000000000)], [(Int.negSucc 12350999999999)])⟩,
      ⟨6, ([(Int.ofNat 3351000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨8, ([(Int.negSucc 10850999999999)], [(Int.ofNat 1851000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4440000000000)])⟩,
      ⟨5, ([(Int.negSucc 4898999999999)], [(Int.negSucc 4100999999999)])⟩,
      ⟨4, ([(Int.negSucc 1874999999999)], [(Int.negSucc 1229999999999)])⟩,
      ⟨0, ([(Int.negSucc 1709999999999)], [(Int.ofNat 0)])⟩,
      ⟨1, ([(Int.ofNat 8625000000000)], [(Int.negSucc 6239999999999)])⟩,
      ⟨0, ([(Int.ofNat 2070000000000)], [(Int.ofNat 4305000000000)])⟩],
    last := 0 }

end ConwaySoifer.Simplified.Certificates.Data
