import ConwaySoifer.Certificates.Model

/-! Generated by tools/export_lean_cert.py from drafts/simplification/certificates/Sint_220000_230000.json -- do not edit. -/

set_option autoImplicit false
set_option maxRecDepth 100000

namespace ConwaySoifer.Simplified.Certificates.Data

open ConwaySoifer.Certificates

def Sint_220000_230000 : CertData :=
  { case := Case.Sint,
    lo := (mkRat (Int.ofNat 11) 50), hi := (mkRat (Int.ofNat 23) 100), den := (Int.ofNat 9000000000000),
    steps := [
      ⟨3, ([(Int.negSucc 3269999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 459000000000)])⟩,
      ⟨0, ([(Int.negSucc 458999999999)], [(Int.negSucc 620999999999)])⟩,
      ⟨0, ([(Int.ofNat 315000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.ofNat 540000000000)], [(Int.negSucc 1079999999999)])⟩,
      ⟨0, ([(Int.ofNat 621000000000)], [(Int.negSucc 1079999999999)])⟩,
      ⟨0, ([(Int.ofNat 660000000000)], [(Int.ofNat 5625000000000)])⟩,
      ⟨0, ([(Int.ofNat 1080000000000)], [(Int.negSucc 539999999999)])⟩,
      ⟨8, ([(Int.negSucc 12314999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨4, ([(Int.negSucc 8249999999999)], [(Int.ofNat 3564000000000)])⟩,
      ⟨4, ([(Int.negSucc 4949999999999)], [(Int.ofNat 900000000000)])⟩,
      ⟨4, ([(Int.negSucc 4499999999999)], [(Int.ofNat 450000000000)])⟩,
      ⟨3, ([(Int.negSucc 3563999999999)], [(Int.ofNat 8625000000000)])⟩,
      ⟨8, ([(Int.negSucc 13814999999999)], [(Int.ofNat 4815000000000)])⟩,
      ⟨5, ([(Int.negSucc 3479999999999)], [(Int.negSucc 5519999999999)])⟩,
      ⟨5, ([(Int.negSucc 374999999999)], [(Int.negSucc 4949999999999)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 4410000000000)])⟩,
      ⟨6, ([(Int.ofNat 5175000000000)], [(Int.negSucc 5834999999999)])⟩,
      ⟨5, ([(Int.negSucc 4409999999999)], [(Int.negSucc 4589999999999)])⟩,
      ⟨5, ([(Int.negSucc 4199999999999)], [(Int.negSucc 4049999999999)])⟩,
      ⟨5, ([(Int.negSucc 659999999999)], [(Int.negSucc 4124999999999)])⟩,
      ⟨9, ([(Int.ofNat 9000000000000)], [(Int.negSucc 15029999999999)])⟩,
      ⟨4, ([(Int.negSucc 4949999999999)], [(Int.negSucc 1799999999999)])⟩,
      ⟨4, ([(Int.negSucc 4124999999999)], [(Int.ofNat 75000000000)])⟩,
      ⟨9, ([(Int.ofNat 4050000000000)], [(Int.negSucc 13049999999999)])⟩,
      ⟨6, ([(Int.ofNat 4290000000000)], [(Int.negSucc 5039999999999)])⟩,
      ⟨6, ([(Int.ofNat 4500000000000)], [(Int.negSucc 4949999999999)])⟩,
      ⟨6, ([(Int.ofNat 4665000000000)], [(Int.negSucc 8624999999999)])⟩,
      ⟨5, ([(Int.negSucc 4904999999999)], [(Int.negSucc 4094999999999)])⟩,
      ⟨0, ([(Int.negSucc 1079999999999)], [(Int.ofNat 108000000000)])⟩,
      ⟨0, ([(Int.negSucc 1019999999999)], [(Int.ofNat 0)])⟩,
      ⟨0, ([(Int.negSucc 659999999999)], [(Int.negSucc 464999999999)])⟩,
      ⟨5, ([(Int.ofNat 0)], [(Int.negSucc 4949999999999)])⟩,
      ⟨1, ([(Int.ofNat 9000000000000)], [(Int.negSucc 3839999999999)])⟩,
      ⟨4, ([(Int.negSucc 4769999999999)], [(Int.negSucc 1979999999999)])⟩,
      ⟨3, ([(Int.negSucc 2879999999999)], [(Int.ofNat 7380000000000)])⟩,
      ⟨0, ([(Int.ofNat 1875000000000)], [(Int.ofNat 4950000000000)])⟩,
      ⟨0, ([(Int.ofNat 1980000000000)], [(Int.ofNat 4770000000000)])⟩,
      ⟨8, ([(Int.negSucc 11879999999999)], [(Int.ofNat 9000000000000)])⟩,
      ⟨8, ([(Int.negSucc 11069999999999)], [(Int.ofNat 2070000000000)])⟩,
      ⟨4, ([(Int.negSucc 8999999999999)], [(Int.ofNat 5115000000000)])⟩,
      ⟨3, ([(Int.negSucc 5174999999999)], [(Int.ofNat 3195000000000)])⟩,
      ⟨3, ([(Int.negSucc 1319999999999)], [(Int.ofNat 6570000000000)])⟩],
    last := 3 }

end ConwaySoifer.Simplified.Certificates.Data
